ExUnit.start()

Code.require_file("support/validation/orbital_reference_fixtures.ex", __DIR__)
Code.require_file("support/validation/campaign_artifact_fixtures.ex", __DIR__)
Code.require_file("support/validation/policy_bundle_fixtures.ex", __DIR__)
Code.require_file("support/validation/activity_artifact_fixtures.ex", __DIR__)
Code.require_file("support/validation/contact_window_fixtures.ex", __DIR__)
Code.require_file("support/validation/state_maneuver_fixtures.ex", __DIR__)
Code.require_file("support/validation/policy_evidence_fixtures.ex", __DIR__)
Code.require_file("support/validation/timeline_activity_state_fixtures.ex", __DIR__)
Code.require_file("support/validation/timeline_preservation_fixtures.ex", __DIR__)
Code.require_file("support/validation/timeline_transition_fixtures.ex", __DIR__)
Code.require_file("support/validation/timeline_handoff_fixtures.ex", __DIR__)
Code.require_file("support/validation/operational_planning_fixtures.ex", __DIR__)
Code.require_file("support/validation/provider_capacity_pack_fixtures.ex", __DIR__)
Code.require_file("support/validation/contact_contention_fixtures.ex", __DIR__)
Code.require_file("support/validation/link_capacity_fixtures.ex", __DIR__)
Code.require_file("support/validation/decision_support_fixtures.ex", __DIR__)
