defmodule OrbitalDynamics.CadenceImport.ContactAllocationManifestRow do
  @moduledoc false

  def build(row, rank, callbacks) when is_list(callbacks) do
    approval_status = Map.get(row, "approval_status", "operator_review_required")
    import_status = Map.get(row, "cadence_import_status", "present")
    import_action = contact_allocation_import_action(row)

    %{
      "id" => "cadence_import:contact_allocation:#{row["id"] || rank}",
      "rank" => rank,
      "import_action" => import_action,
      "import_status" => adapter_import_status(callbacks, import_status, approval_status),
      "import_side" => "source",
      "source_review_row_id" => row["id"],
      "source_review_type" => row["review_type"],
      "source_review_action" => source_review_action(callbacks, row),
      "subject_id" => row["subject_id"],
      "branch_id" => row["branch_id"],
      "activity_id" => row["activity_id"],
      "activity_type" => row["activity_type"],
      "contact_id" => row["contact_id"],
      "scenario_id" => row["scenario_id"],
      "spacecraft_id" => row["spacecraft_id"],
      "ground_station_id" => row["ground_station_id"],
      "direction" => row["direction"],
      "starts_at_s" => row["starts_at_s"],
      "ends_at_s" => row["ends_at_s"],
      "source_window_id" => row["source_window_id"],
      "source_window_type" => row["source_window_type"],
      "source_window" => row["source_window"],
      "actual_throughput_mb" => row["actual_throughput_mb"],
      "actual_data_rate_throughput_derivation" => row["actual_data_rate_throughput_derivation"],
      "completed_fraction" => row["completed_fraction"],
      "required_downlink_mb" => row["required_downlink_mb"],
      "candidate_downlink_mb" => row["candidate_downlink_mb"],
      "downlink_completion_ratio" => row["downlink_completion_ratio"],
      "selected_downlink_shortfall_mb" => row["selected_downlink_shortfall_mb"],
      "downlink_requirement_status" => row["downlink_requirement_status"],
      "downlink_completion_source" => row["downlink_completion_source"],
      "downlink_completion_sources" => row["downlink_completion_sources"],
      "required_capacity_fraction" => row["required_capacity_fraction"],
      "required_capacity_fraction_source" => row["required_capacity_fraction_source"],
      "contact_success" => row["contact_success"],
      "contact_success_factor" => row["contact_success_factor"],
      "contact_success_factor_source" => row["contact_success_factor_source"],
      "command_success" => row["command_success"],
      "contact_result" => provider_result_artifact_value(callbacks, row["contact_result"]),
      "command_result" => provider_result_artifact_value(callbacks, row["command_result"]),
      "command_success_factor" => row["command_success_factor"],
      "command_success_factor_source" => row["command_success_factor_source"],
      "allocation_status" => row["allocation_status"],
      "effective_allocation_status" => row["effective_allocation_status"],
      "allocation_reason" => row["allocation_reason"],
      "selected" => row["selected"],
      "contention_group_id" => row["contention_group_id"],
      "selected_contact_id" => row["selected_contact_id"],
      "deferred_contact_ids" => row["deferred_contact_ids"],
      "capacity_pack_group_id" => row["capacity_pack_group_id"],
      "capacity_pack_status" => row["capacity_pack_status"],
      "capacity_pack_capacity_fraction" => row["capacity_pack_capacity_fraction"],
      "capacity_pack_used_fraction" => row["capacity_pack_used_fraction"],
      "selected_priority" => row["selected_priority"],
      "selected_priority_source" => row["selected_priority_source"],
      "deferred_contact_priorities" => row["deferred_contact_priorities"],
      "requested_priority_fields" => row["requested_priority_fields"],
      "priority_field_evidence_counts" => row["priority_field_evidence_counts"],
      "priority_fields_without_numeric_evidence_count" =>
        row["priority_fields_without_numeric_evidence_count"],
      "priority_fields_without_numeric_evidence" =>
        row["priority_fields_without_numeric_evidence"],
      "resolution_priority_override_count" => row["resolution_priority_override_count"],
      "resolution_priority_override_contact_ids" =>
        row["resolution_priority_override_contact_ids"],
      "ignored_priority_override_count" => row["ignored_priority_override_count"],
      "ignored_priority_override_keys" => row["ignored_priority_override_keys"],
      "ignored_priority_override_contact_ids" => row["ignored_priority_override_contact_ids"],
      "ignored_priority_override_input" => row["ignored_priority_override_input"],
      "suppressed_reason" => row["suppressed_reason"],
      "duplicate_contact_id_collision" => row["duplicate_contact_id_collision"],
      "duplicate_contact_index" => row["duplicate_contact_index"],
      "duplicate_contact_candidate_count" => row["duplicate_contact_candidate_count"],
      "duplicate_contact_candidate_ids" => row["duplicate_contact_candidate_ids"],
      "duplicate_contact_candidates" => row["duplicate_contact_candidates"],
      "station_calendar_entry_id" => row["station_calendar_entry_id"],
      "station_calendar_provider_id" => row["station_calendar_provider_id"],
      "station_calendar_provider_entry_id" => row["station_calendar_provider_entry_id"],
      "station_calendar_directions" => row["station_calendar_directions"],
      "station_calendar_status" => row["station_calendar_status"],
      "station_calendar_overlap_count" => row["station_calendar_overlap_count"],
      "station_calendar_overlap_entry_ids" => row["station_calendar_overlap_entry_ids"],
      "station_calendar_overlap_availabilities" => row["station_calendar_overlap_availabilities"],
      "station_calendar_entry_ambiguous" => row["station_calendar_entry_ambiguous"],
      "station_calendar_ambiguous_entry_count" => row["station_calendar_ambiguous_entry_count"],
      "station_calendar_ambiguous_entry_ids" => row["station_calendar_ambiguous_entry_ids"],
      "station_calendar_reservation_overlap_count" =>
        row["station_calendar_reservation_overlap_count"],
      "station_calendar_reservation_ids" => row["station_calendar_reservation_ids"],
      "station_calendar_reserved_by" => row["station_calendar_reserved_by"],
      "station_calendar_reservation_statuses" => row["station_calendar_reservation_statuses"],
      "station_calendar_reservation_expires_at_s" =>
        row["station_calendar_reservation_expires_at_s"],
      "provider_counteroffer_id" => row["provider_counteroffer_id"],
      "provider_counteroffer_status" => row["provider_counteroffer_status"],
      "provider_counteroffer_negotiation_state" => row["provider_counteroffer_negotiation_state"],
      "provider_counteroffer_reason_code" => row["provider_counteroffer_reason_code"],
      "provider_counteroffer_cost_delta" => row["provider_counteroffer_cost_delta"],
      "provider_counteroffer_lock_deadline_s" => row["provider_counteroffer_lock_deadline_s"],
      "provider_counteroffer_starts_at_s" => row["provider_counteroffer_starts_at_s"],
      "provider_counteroffer_ends_at_s" => row["provider_counteroffer_ends_at_s"],
      "provider_counteroffer_start_delta_s" => row["provider_counteroffer_start_delta_s"],
      "provider_counteroffer_end_delta_s" => row["provider_counteroffer_end_delta_s"],
      "provider_counteroffer_duration_delta_s" => row["provider_counteroffer_duration_delta_s"],
      "station_calendar_trust_boundary_status" => row["station_calendar_trust_boundary_status"],
      "trust_boundary" => row["trust_boundary"],
      "provenance" => row["provenance"],
      "station_availability" => row["station_availability"],
      "capacity_fraction" => row["capacity_fraction"],
      "station_contention_status" => row["station_contention_status"],
      "station_reservation_id" => row["station_reservation_id"],
      "station_reservation_expires_at_s" => row["station_reservation_expires_at_s"],
      "station_reserved_by" => row["station_reserved_by"],
      "station_reservation_status" => row["station_reservation_status"],
      "station_reservation_match_status" => row["station_reservation_match_status"],
      "provider_reservation_request_status" => row["provider_reservation_request_status"],
      "provider_reservation_request_summary_model" =>
        row["provider_reservation_request_summary_model"],
      "provider_reservation_request_summary_schema_contract" =>
        row["provider_reservation_request_summary_schema_contract"],
      "provider_reservation_request_source_artifact_type" =>
        row["provider_reservation_request_source_artifact_type"],
      "provider_reservation_request_source" => row["provider_reservation_request_source"],
      "provider_reservation_request_execution_boundary" =>
        row["provider_reservation_request_execution_boundary"],
      "provider_reservation_execution" => row["provider_reservation_execution"],
      "resource_blocking_dimension" => row["resource_blocking_dimension"],
      "resource_source_quality" => row["resource_source_quality"],
      "resource_trust_boundary" => row["resource_trust_boundary"],
      "resource_trust_boundary_status" => row["resource_trust_boundary_status"],
      "resource_provenance" => row["resource_provenance"],
      "fuel_margin" => row["fuel_margin"],
      "thermal_margin_c" => row["thermal_margin_c"],
      "power_margin" => row["power_margin"],
      "storage_margin" => row["storage_margin"],
      "downlink_margin" => row["downlink_margin"],
      "battery_capacity_wh" => row["battery_capacity_wh"],
      "battery_energy_used_wh" => row["battery_energy_used_wh"],
      "battery_energy_generated_wh" => row["battery_energy_generated_wh"],
      "battery_state_of_charge" => row["battery_state_of_charge"],
      "spacecraft_available" => row["spacecraft_available"],
      "planned_spacecraft_available" => row["planned_spacecraft_available"],
      "realized_spacecraft_available" => row["realized_spacecraft_available"],
      "spacecraft_available_match_status" => row["spacecraft_available_match_status"],
      "payload_available" => row["payload_available"],
      "planned_payload_available" => row["planned_payload_available"],
      "realized_payload_available" => row["realized_payload_available"],
      "payload_available_match_status" => row["payload_available_match_status"],
      "antenna_available" => row["antenna_available"],
      "planned_antenna_available" => row["planned_antenna_available"],
      "realized_antenna_available" => row["realized_antenna_available"],
      "antenna_available_match_status" => row["antenna_available_match_status"],
      "degraded" => row["degraded"],
      "planned_degraded" => row["planned_degraded"],
      "realized_degraded" => row["realized_degraded"],
      "degraded_match_status" => row["degraded_match_status"],
      "mode" => row["mode"],
      "planned_mode" => row["planned_mode"],
      "realized_mode" => row["realized_mode"],
      "mode_match_status" => row["mode_match_status"],
      "incompatible_activity_types" => row["incompatible_activity_types"],
      "suppressed_activity_types" => row["suppressed_activity_types"],
      "base_station_calendar_row_id" => row["base_station_calendar_row_id"],
      "duplicate_station_calendar_row_id_collision" =>
        row["duplicate_station_calendar_row_id_collision"],
      "duplicate_station_calendar_row_index" => row["duplicate_station_calendar_row_index"],
      "duplicate_station_calendar_row_count" => row["duplicate_station_calendar_row_count"],
      "approval_status" => approval_status,
      "policy_classification" => row["policy_classification"],
      "required_operator_action" => row["required_operator_action"],
      "reason" => row["reason"],
      "requirement_type" => row["requirement_type"],
      "required_authority" => row["required_authority"],
      "policy_bundle_id" => row["policy_bundle_id"],
      "rule_id" => row["rule_id"],
      "escalation_level" => row["escalation_level"],
      "escalation_queue" => row["escalation_queue"],
      "escalation_role" => row["escalation_role"],
      "sla_s" => row["sla_s"],
      "approval_requirements" => row["approval_requirements"],
      "approval_rule_matches" => row["approval_rule_matches"],
      "cadence_import_status" => import_status,
      "has_cadence_import" => false,
      "source_contact_allocation" => row["source_contact_allocation"],
      "source_contact_candidate" => row["source_contact_candidate"],
      "source_resource_summary" => row["source_resource_summary"],
      "source_resource_suppression" => row["source_resource_suppression"],
      "source_contact_suppression" => row["source_contact_suppression"],
      "source_station_calendar_entry" => row["source_station_calendar_entry"],
      "source_station_calendar_overlaps" => row["source_station_calendar_overlaps"],
      "source_contention_recommendation" => row["source_contention_recommendation"],
      "source_provider_reservation_request_summary" =>
        row["source_provider_reservation_request_summary"],
      "source_policy_decision" => row["source_policy_decision"],
      "source_policy_escalation" => row["source_policy_escalation"],
      "source_review_row" => row
    }
    |> compact_map(callbacks)
  end

  defp contact_allocation_import_action(%{
         "provider_reservation_request_status" => "request_ready"
       }),
       do: "review_provider_reservation_request"

  defp contact_allocation_import_action(_row), do: "review_contact_allocation"

  defp source_review_action(callbacks, row),
    do: invoke(callbacks, :source_review_action, [row])

  defp adapter_import_status(callbacks, status, approval_status),
    do: invoke(callbacks, :adapter_import_status, [status, approval_status])

  defp provider_result_artifact_value(callbacks, value),
    do: invoke(callbacks, :provider_result_artifact_value, [value])

  defp compact_map(value, callbacks), do: invoke(callbacks, :compact_map, [value])

  defp invoke(callbacks, name, args), do: apply(Keyword.fetch!(callbacks, name), args)
end
