defmodule OrbitalDynamics.CadenceImport.OperationalTimelineManifestRow do
  @moduledoc false

  def build(row, rank, callbacks) when is_list(callbacks) do
    approval_status = Map.get(row, "approval_status", "operator_review_required")
    import_status = Map.get(row, "cadence_import_status", "present")
    has_cadence_import = cadence_import_present?(callbacks, row, import_status)

    %{
      "id" => "cadence_import:operational_timeline:#{row["id"] || rank}",
      "rank" => rank,
      "import_action" => "review_operational_timeline",
      "import_status" => adapter_import_status(callbacks, import_status, approval_status),
      "import_side" => "source",
      "source_review_row_id" => row["id"],
      "source_review_type" => row["review_type"],
      "source_review_action" => source_review_action(callbacks, row),
      "source" => row["source"],
      "subject_id" => row["subject_id"],
      "branch_id" => row["branch_id"],
      "activity_id" => row["activity_id"],
      "timeline_id" => row["timeline_id"],
      "scenario_id" => row["scenario_id"],
      "activity_type" => row["activity_type"],
      "operational_kind" => row["operational_kind"],
      "direction" => row["direction"],
      "spacecraft_id" => row["spacecraft_id"],
      "ground_station_id" => row["ground_station_id"],
      "target_id" => row["target_id"],
      "resource_id" => row["resource_id"],
      "collection_id" => row["collection_id"],
      "product_id" => row["product_id"],
      "product_ids" => row["product_ids"],
      "payload_id" => row["payload_id"],
      "instrument_id" => row["instrument_id"],
      "pointing_mode" => row["pointing_mode"],
      "pointing_target_id" => row["pointing_target_id"],
      "boresight_axis" => row["boresight_axis"],
      "off_nadir_angle_deg" => row["off_nadir_angle_deg"],
      "slew_angle_deg" => row["slew_angle_deg"],
      "slew_rate_deg_s" => row["slew_rate_deg_s"],
      "pointing_error_deg" => row["pointing_error_deg"],
      "pointing_status" => row["pointing_status"],
      "pointing_model" => row["pointing_model"],
      "pointing_source" => row["pointing_source"],
      "pointing_confidence" => row["pointing_confidence"],
      "attitude_mode" => row["attitude_mode"],
      "attitude_target_id" => row["attitude_target_id"],
      "roll_deg" => row["roll_deg"],
      "pitch_deg" => row["pitch_deg"],
      "yaw_deg" => row["yaw_deg"],
      "attitude_error_deg" => row["attitude_error_deg"],
      "attitude_status" => row["attitude_status"],
      "attitude_model" => row["attitude_model"],
      "attitude_source" => row["attitude_source"],
      "attitude_confidence" => row["attitude_confidence"],
      "starts_at_s" => row["starts_at_s"],
      "ends_at_s" => row["ends_at_s"],
      "status" => row["status"],
      "approval_status" => approval_status,
      "source_approval_status" => row["source_approval_status"],
      "locked" => row["locked"],
      "required_operator_action" => row["required_operator_action"],
      "reason" => row["reason"],
      "operator_action_reason" => row["operator_action_reason"],
      "precondition_status" => row["precondition_status"],
      "blocked_precondition_count" => row["blocked_precondition_count"],
      "review_precondition_count" => row["review_precondition_count"],
      "blocked_precondition_types" => row["blocked_precondition_types"],
      "review_precondition_types" => row["review_precondition_types"],
      "preconditions" => row["preconditions"],
      "execution_boundary" => row["execution_boundary"],
      "cadence_import_status" => import_status,
      "cadence_import_type" => row["cadence_import_type"],
      "cadence_import_id" => row["cadence_import_id"],
      "cadence_import_contract" => row["cadence_import_contract"],
      "cadence_import_provider" => row["cadence_import_provider"],
      "cadence_import_adapter" => row["cadence_import_adapter"],
      "cadence_import_adapter_version" => row["cadence_import_adapter_version"],
      "cadence_import_trust_boundary" => row["cadence_import_trust_boundary"],
      "cadence_import_provenance" => row["cadence_import_provenance"],
      "invalid_cadence_import" => row["invalid_cadence_import"],
      "invalid_cadence_import_reason" => row["invalid_cadence_import_reason"],
      "source_cadence_import" => row["source_cadence_import"],
      "execution_uncertainty_status" => row["execution_uncertainty_status"],
      "execution_uncertainty" => row["execution_uncertainty"],
      "timing_3sigma_s" => row["timing_3sigma_s"],
      "delta_v_3sigma_km_s" => row["delta_v_3sigma_km_s"],
      "delta_v_3sigma_magnitude_km_s" => row["delta_v_3sigma_magnitude_km_s"],
      "execution_uncertainty_source" => row["execution_uncertainty_source"],
      "link_protocol" => row["link_protocol"],
      "frequency_band" => row["frequency_band"],
      "modulation" => row["modulation"],
      "coding_scheme" => row["coding_scheme"],
      "polarization" => row["polarization"],
      "data_rate_mbps" => row["data_rate_mbps"],
      "downlink_rate_mbps" => row["downlink_rate_mbps"],
      "data_rate_mb_s" => row["data_rate_mb_s"],
      "downlink_rate_mb_s" => row["downlink_rate_mb_s"],
      "actual_data_rate_mbps" => row["actual_data_rate_mbps"],
      "actual_downlink_rate_mbps" => row["actual_downlink_rate_mbps"],
      "actual_data_rate_mb_s" => row["actual_data_rate_mb_s"],
      "actual_downlink_rate_mb_s" => row["actual_downlink_rate_mb_s"],
      "delivered_rate_mbps" => row["delivered_rate_mbps"],
      "received_rate_mbps" => row["received_rate_mbps"],
      "delivered_rate_mb_s" => row["delivered_rate_mb_s"],
      "received_rate_mb_s" => row["received_rate_mb_s"],
      "actual_duration_s" => row["actual_duration_s"],
      "actual_contact_duration_s" => row["actual_contact_duration_s"],
      "contact_duration_s" => row["contact_duration_s"],
      "link_margin_db" => row["link_margin_db"],
      "snr_db" => row["snr_db"],
      "eb_no_db" => row["eb_no_db"],
      "bit_error_rate" => row["bit_error_rate"],
      "packet_loss_rate" => row["packet_loss_rate"],
      "frame_loss_rate" => row["frame_loss_rate"],
      "carrier_lock" => row["carrier_lock"],
      "symbol_lock" => row["symbol_lock"],
      "link_quality_status" => row["link_quality_status"],
      "eclipse_overlap_fraction" => row["eclipse_overlap_fraction"],
      "planned_eclipse_overlap_fraction" => row["planned_eclipse_overlap_fraction"],
      "realized_eclipse_overlap_fraction" => row["realized_eclipse_overlap_fraction"],
      "eclipse_overlap_s" => row["eclipse_overlap_s"],
      "planned_eclipse_overlap_s" => row["planned_eclipse_overlap_s"],
      "realized_eclipse_overlap_s" => row["realized_eclipse_overlap_s"],
      "lighting_condition" => row["lighting_condition"],
      "planned_lighting_condition" => row["planned_lighting_condition"],
      "realized_lighting_condition" => row["realized_lighting_condition"],
      "lighting_condition_match_status" => row["lighting_condition_match_status"],
      "lighting_condition_detail" => row["lighting_condition_detail"],
      "lighting_condition_model" => row["lighting_condition_model"],
      "lighting_detail_model" => row["lighting_detail_model"],
      "lighting_confidence" => row["lighting_confidence"],
      "planned_estimated_throughput_mb" => row["planned_estimated_throughput_mb"],
      "actual_throughput_mb" => row["actual_throughput_mb"],
      "actual_data_rate_throughput_derivation" => row["actual_data_rate_throughput_derivation"],
      "throughput_delta_mb" => row["throughput_delta_mb"],
      "throughput_completion_fraction" => row["throughput_completion_fraction"],
      "data_volume_mb" => row["data_volume_mb"],
      "planned_data_volume_mb" => row["planned_data_volume_mb"],
      "actual_data_volume_mb" => row["actual_data_volume_mb"],
      "data_volume_delta_mb" => row["data_volume_delta_mb"],
      "data_volume_completion_fraction" => row["data_volume_completion_fraction"],
      "estimated_data_volume_mb" => row["estimated_data_volume_mb"],
      "estimated_storage_mb" => row["estimated_storage_mb"],
      "estimated_downlink_mb" => row["estimated_downlink_mb"],
      "required_downlink_mb" => row["required_downlink_mb"],
      "collection_ends_at_s" => row["collection_ends_at_s"],
      "planned_delivery_at_s" => row["planned_delivery_at_s"],
      "actual_delivery_at_s" => row["actual_delivery_at_s"],
      "max_latency_s" => row["max_latency_s"],
      "planned_latency_s" => row["planned_latency_s"],
      "actual_latency_s" => row["actual_latency_s"],
      "latency_delta_s" => row["latency_delta_s"],
      "latency_margin_s" => row["latency_margin_s"],
      "resource_source_quality" => row["resource_source_quality"],
      "resource_trust_boundary" => row["resource_trust_boundary"],
      "resource_trust_boundary_status" => row["resource_trust_boundary_status"],
      "resource_provenance" => row["resource_provenance"],
      "resource_blocking_dimension" => row["resource_blocking_dimension"],
      "fuel_margin" => row["fuel_margin"],
      "thermal_zone_id" => row["thermal_zone_id"],
      "temperature_c" => row["temperature_c"],
      "planned_temperature_c" => row["planned_temperature_c"],
      "actual_temperature_c" => row["actual_temperature_c"],
      "temperature_delta_c" => row["temperature_delta_c"],
      "min_operating_temperature_c" => row["min_operating_temperature_c"],
      "max_operating_temperature_c" => row["max_operating_temperature_c"],
      "thermal_margin_c" => row["thermal_margin_c"],
      "thermal_status" => row["thermal_status"],
      "thermal_model" => row["thermal_model"],
      "thermal_source" => row["thermal_source"],
      "thermal_confidence" => row["thermal_confidence"],
      "power_margin" => row["power_margin"],
      "storage_margin" => row["storage_margin"],
      "downlink_margin" => row["downlink_margin"],
      "battery_capacity_wh" => row["battery_capacity_wh"],
      "battery_energy_used_wh" => row["battery_energy_used_wh"],
      "battery_energy_generated_wh" => row["battery_energy_generated_wh"],
      "battery_state_of_charge" => row["battery_state_of_charge"],
      "spacecraft_available" => row["spacecraft_available"],
      "payload_available" => row["payload_available"],
      "antenna_available" => row["antenna_available"],
      "degraded" => row["degraded"],
      "mode" => row["mode"],
      "incompatible_activity_types" => row["incompatible_activity_types"],
      "suppressed_activity_types" => row["suppressed_activity_types"],
      "score" => row["score"],
      "score_terms" => row["score_terms"],
      "target_priority" => row["target_priority"],
      "target_priority_source" => row["target_priority_source"],
      "target_priority_objective_ids" => row["target_priority_objective_ids"],
      "target_priority_objective_type" => row["target_priority_objective_type"],
      "image_quality_score" => row["image_quality_score"],
      "image_quality_status" => row["image_quality_status"],
      "image_quality_source" => row["image_quality_source"],
      "cloud_cover_fraction" => row["cloud_cover_fraction"],
      "blur_score" => row["blur_score"],
      "contact_success" => row["contact_success"],
      "contact_success_factor" => row["contact_success_factor"],
      "contact_success_factor_source" => row["contact_success_factor_source"],
      "command_success" => row["command_success"],
      "contact_result" => provider_result_artifact_value(callbacks, row["contact_result"]),
      "command_result" => provider_result_artifact_value(callbacks, row["command_result"]),
      "command_authority_status" => row["command_authority_status"],
      "command_safety_status" => row["command_safety_status"],
      "command_authorized" => row["command_authorized"],
      "command_safety_checked" => row["command_safety_checked"],
      "command_success_factor" => row["command_success_factor"],
      "command_success_factor_source" => row["command_success_factor_source"],
      "observation_success" => row["observation_success"],
      "observation_result" =>
        provider_result_artifact_value(callbacks, row["observation_result"]),
      "observation_success_factor" => row["observation_success_factor"],
      "observation_success_factor_source" => row["observation_success_factor_source"],
      "feedback_weight" => row["feedback_weight"],
      "feedback_weight_source" => row["feedback_weight_source"],
      "maneuver_success" => row["maneuver_success"],
      "maneuver_result" => provider_result_artifact_value(callbacks, row["maneuver_result"]),
      "maneuver_success_factor" => row["maneuver_success_factor"],
      "maneuver_success_factor_source" => row["maneuver_success_factor_source"],
      "source_window_id" => row["source_window_id"],
      "source_window_type" => row["source_window_type"],
      "station_availability" => row["station_availability"],
      "station_contention_status" => row["station_contention_status"],
      "station_calendar_entry_id" => row["station_calendar_entry_id"],
      "station_calendar_status" => row["station_calendar_status"],
      "station_calendar_overlap_count" => row["station_calendar_overlap_count"],
      "station_calendar_overlap_entry_ids" => row["station_calendar_overlap_entry_ids"],
      "station_calendar_overlap_availabilities" => row["station_calendar_overlap_availabilities"],
      "station_calendar_entry_ambiguous" => row["station_calendar_entry_ambiguous"],
      "station_calendar_ambiguous_entry_count" => row["station_calendar_ambiguous_entry_count"],
      "station_calendar_ambiguous_entry_ids" => row["station_calendar_ambiguous_entry_ids"],
      "station_calendar_reservation_overlap_count" =>
        row["station_calendar_reservation_overlap_count"],
      "station_calendar_reservation_ids" => row["station_calendar_reservation_ids"],
      "station_calendar_reserved_by" => row["station_calendar_reserved_by"],
      "station_calendar_reservation_statuses" => row["station_calendar_reservation_statuses"],
      "station_calendar_reservation_expires_at_s" =>
        row["station_calendar_reservation_expires_at_s"],
      "station_calendar_trust_boundary_status" => row["station_calendar_trust_boundary_status"],
      "trust_boundary" => row["trust_boundary"],
      "provenance" => row["provenance"],
      "station_reservation_id" => row["station_reservation_id"],
      "station_reservation_expires_at_s" => row["station_reservation_expires_at_s"],
      "station_reserved_by" => row["station_reserved_by"],
      "station_reservation_status" => row["station_reservation_status"],
      "station_reservation_match_status" => row["station_reservation_match_status"],
      "schedule_conflict_status" => row["schedule_conflict_status"],
      "exclusivity_group" => row["exclusivity_group"],
      "timeline_integrity_status" => row["timeline_integrity_status"],
      "timeline_integrity_issue_count" => row["timeline_integrity_issue_count"],
      "timeline_integrity_issue_types" => row["timeline_integrity_issue_types"],
      "timeline_integrity_issues" => row["timeline_integrity_issues"],
      "missing_dependency_activity_ids" => row["missing_dependency_activity_ids"],
      "missing_dependency_timeline_ids" => row["missing_dependency_timeline_ids"],
      "self_dependency_activity_ids" => row["self_dependency_activity_ids"],
      "self_dependency_timeline_ids" => row["self_dependency_timeline_ids"],
      "dependency_cycle_activity_ids" => row["dependency_cycle_activity_ids"],
      "dependency_cycle_timeline_ids" => row["dependency_cycle_timeline_ids"],
      "dependency_order_violation_activity_ids" => row["dependency_order_violation_activity_ids"],
      "dependency_order_violation_timeline_ids" => row["dependency_order_violation_timeline_ids"],
      "exclusivity_violation_activity_ids" => row["exclusivity_violation_activity_ids"],
      "exclusivity_violation_timeline_ids" => row["exclusivity_violation_timeline_ids"],
      "exclusivity_violation_group" => row["exclusivity_violation_group"],
      "timeline_identity_collision" => row["timeline_identity_collision"],
      "duplicate_timeline_identity_activity_count" =>
        row["duplicate_timeline_identity_activity_count"],
      "duplicate_timeline_identity_activity_ids" =>
        row["duplicate_timeline_identity_activity_ids"],
      "duplicate_timeline_identity_activities" => row["duplicate_timeline_identity_activities"],
      "superseded_required_operator_action" => row["superseded_required_operator_action"],
      "superseded_operator_action_reason" => row["superseded_operator_action_reason"],
      "requirement_type" => row["requirement_type"],
      "required_authority" => row["required_authority"],
      "policy_bundle_id" => row["policy_bundle_id"],
      "rule_id" => row["rule_id"],
      "escalation_level" => row["escalation_level"],
      "escalation_queue" => row["escalation_queue"],
      "escalation_role" => row["escalation_role"],
      "sla_s" => row["sla_s"],
      "approval_requirements" => row["approval_requirements"],
      "approval_rule_matches" => row["approval_rule_matches"],
      "source_policy_decision" => row["source_policy_decision"],
      "source_policy_escalation" => row["source_policy_escalation"],
      "invalid_activity_input" => row["invalid_activity_input"],
      "invalid_activity_input_reason" => row["invalid_activity_input_reason"],
      "source_activity" => row["source_activity"],
      "dependency_activity_ids" => row["dependency_activity_ids"],
      "dependency_timeline_ids" => row["dependency_timeline_ids"],
      "exclusive_with_activity_ids" => row["exclusive_with_activity_ids"],
      "exclusive_with_timeline_ids" => row["exclusive_with_timeline_ids"],
      "has_source_window" => row["has_source_window"],
      "has_cadence_import" => has_cadence_import,
      "timeline_identity" => row["timeline_identity"],
      "import_activity_context" =>
        normalize_provider_result_artifact_fields(
          callbacks,
          row["source_activity_context"] || row["activity_context"]
        ),
      "source_activity_context" =>
        normalize_provider_result_artifact_fields(
          callbacks,
          row["source_activity_context"] || row["activity_context"]
        ),
      "source_station_calendar_entry" => row["source_station_calendar_entry"],
      "source_station_calendar_overlaps" => row["source_station_calendar_overlaps"],
      "source_operational_timeline" => row["source_operational_timeline"],
      "source_review_row" => row
    }
    |> compact_map(callbacks)
  end

  defp cadence_import_present?(callbacks, row, status),
    do: invoke(callbacks, :cadence_import_present?, [row, status])

  defp source_review_action(callbacks, row),
    do: invoke(callbacks, :source_review_action, [row])

  defp adapter_import_status(callbacks, status, approval_status),
    do: invoke(callbacks, :adapter_import_status, [status, approval_status])

  defp provider_result_artifact_value(callbacks, value),
    do: invoke(callbacks, :provider_result_artifact_value, [value])

  defp normalize_provider_result_artifact_fields(callbacks, value),
    do: invoke(callbacks, :normalize_provider_result_artifact_fields, [value])

  defp compact_map(value, callbacks), do: invoke(callbacks, :compact_map, [value])

  defp invoke(callbacks, name, args), do: apply(Keyword.fetch!(callbacks, name), args)
end
