defmodule OrbitalDynamics.Validation.ReferenceFixtures do
  @moduledoc false

  alias OrbitalDynamics.Validation.ReferenceFixtures.AcceptedPlanningState
  alias OrbitalDynamics.Validation.ReferenceFixtures.ActivityArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.BenchmarkArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.CapabilityCatalogArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateRefreshBase
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateRefreshCapacityFilter
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateRefreshContact
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateRefreshFilterRejection
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateRefreshFreshnessBudget
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateRefreshPlanningFeedback
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateRefreshReadiness
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateRefreshStationAllocation
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateRefreshTimeline
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateStateArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.CandidateStrategyArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.CampaignArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.CampaignPlanning
  alias OrbitalDynamics.Validation.ReferenceFixtures.ContactAllocationArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ContactContentionArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ContactIntentArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ContactWindowArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.CoreRunReports
  alias OrbitalDynamics.Validation.ReferenceFixtures.DecisionSupportArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.EnvironmentCapabilities
  alias OrbitalDynamics.Validation.ReferenceFixtures.LinkCapacityArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.Level5ContractArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ManifestArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ModelAcceptanceArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ObjectiveScoringArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.OperationalPlanningArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.OperationalReadinessArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.Orbital
  alias OrbitalDynamics.Validation.ReferenceFixtures.PolicyBundleArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.PolicyDecisions
  alias OrbitalDynamics.Validation.ReferenceFixtures.PolicyEvidenceArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ProviderCapacityPackArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.QualityGateArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ResourcePressureHandoffArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ResourceProjectionArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ResourceSafetyArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.ResourceSummaryArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.SchemaCompatibilityArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.StateManeuverArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.StationReservationArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.SubsystemModelCapabilities
  alias OrbitalDynamics.Validation.ReferenceFixtures.TimelineActivityStateArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.TimelineHandoffArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.TimelinePreservationArtifacts
  alias OrbitalDynamics.Validation.ReferenceFixtures.TimelineTransitionArtifacts

  @all_fixtures Orbital.all()
                |> Map.merge(AcceptedPlanningState.all())
                |> Map.merge(ActivityArtifacts.all())
                |> Map.merge(BenchmarkArtifacts.all())
                |> Map.merge(CandidateRefreshBase.all())
                |> Map.merge(CandidateRefreshCapacityFilter.all())
                |> Map.merge(CandidateRefreshContact.all())
                |> Map.merge(CandidateRefreshFilterRejection.all())
                |> Map.merge(CandidateRefreshFreshnessBudget.all())
                |> Map.merge(CandidateRefreshPlanningFeedback.all())
                |> Map.merge(CandidateRefreshReadiness.all())
                |> Map.merge(CandidateRefreshStationAllocation.all())
                |> Map.merge(CandidateRefreshTimeline.all())
                |> Map.merge(CandidateStateArtifacts.all())
                |> Map.merge(CandidateStrategyArtifacts.all())
                |> Map.merge(CampaignArtifacts.all())
                |> Map.merge(CampaignPlanning.all())
                |> Map.merge(ContactAllocationArtifacts.all())
                |> Map.merge(ContactContentionArtifacts.all())
                |> Map.merge(ContactIntentArtifacts.all())
                |> Map.merge(ContactWindowArtifacts.all())
                |> Map.merge(CoreRunReports.all())
                |> Map.merge(DecisionSupportArtifacts.all())
                |> Map.merge(EnvironmentCapabilities.all())
                |> Map.merge(LinkCapacityArtifacts.all())
                |> Map.merge(Level5ContractArtifacts.all())
                |> Map.merge(ManifestArtifacts.all())
                |> Map.merge(ModelAcceptanceArtifacts.all())
                |> Map.merge(ObjectiveScoringArtifacts.all())
                |> Map.merge(OperationalPlanningArtifacts.all())
                |> Map.merge(OperationalReadinessArtifacts.all())
                |> Map.merge(PolicyBundleArtifacts.all())
                |> Map.merge(PolicyDecisions.all())
                |> Map.merge(PolicyEvidenceArtifacts.all())
                |> Map.merge(ProviderCapacityPackArtifacts.all())
                |> Map.merge(QualityGateArtifacts.all())
                |> Map.merge(ResourcePressureHandoffArtifacts.all())
                |> Map.merge(ResourceProjectionArtifacts.all())
                |> Map.merge(ResourceSafetyArtifacts.all())
                |> Map.merge(ResourceSummaryArtifacts.all())
                |> Map.merge(SchemaCompatibilityArtifacts.all())
                |> Map.merge(StateManeuverArtifacts.all())
                |> Map.merge(StationReservationArtifacts.all())
                |> Map.merge(SubsystemModelCapabilities.all())
                |> Map.merge(TimelineActivityStateArtifacts.all())
                |> Map.merge(TimelineHandoffArtifacts.all())
                |> Map.merge(TimelinePreservationArtifacts.all())
                |> Map.merge(TimelineTransitionArtifacts.all())
                |> Map.merge(CapabilityCatalogArtifacts.all())

  def all, do: @all_fixtures

  def fetch(id) when is_binary(id), do: Map.fetch(@all_fixtures, id)
end
