defmodule OrbitalDynamics.Validation.ReferenceFixtures.CampaignPlanning do
  @moduledoc false

  @fixtures %{
    "fixture.artifact.campaign_repair.leo_constellation_v2" => %{
      "id" => "fixture.artifact.campaign_repair.leo_constellation_v2",
      "model_id" => "artifact.campaign_repair.v2",
      "reference_case" => "checked-in LEO constellation campaign repair artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/leo_constellation_campaign_repair_v2.json",
        "contract" => "campaign_repair.v2"
      },
      "expected" => %{
        "schema_version" => 2,
        "planner" => "OrbitalDynamics.CampaignPlanner.V2",
        "activity_count" => 0,
        "delta_count" => 1,
        "approval_requirement_count" => 1,
        "source_candidate_count" => 0,
        "source_candidate_rejection_report_count" => 1,
        "source_candidate_rejection_row_count" => 1,
        "source_candidate_rejection_rejected_count" => 1,
        "source_candidate_rejection_reviewable_count" => 1,
        "source_contact_intent_count" => 0,
        "source_resource_summary_count" => 1,
        "operator_review_candidate_rejection_review_count" => 1,
        "cadence_import_candidate_rejection_row_count" => 1,
        "warning_count" => 3,
        "policy_decision_contract" => "policy_decision.v1"
      },
      "tolerances" => %{
        "schema_version" => 0,
        "activity_count" => 0,
        "delta_count" => 0,
        "approval_requirement_count" => 0,
        "source_candidate_count" => 0,
        "source_candidate_rejection_report_count" => 0,
        "source_candidate_rejection_row_count" => 0,
        "source_candidate_rejection_rejected_count" => 0,
        "source_candidate_rejection_reviewable_count" => 0,
        "source_contact_intent_count" => 0,
        "source_resource_summary_count" => 0,
        "operator_review_candidate_rejection_review_count" => 0,
        "cadence_import_candidate_rejection_row_count" => 0,
        "warning_count" => 0
      },
      "evidence" => [
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2",
        "schema-linted by mix orbital_dynamics.schema.lint"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external mission validation",
        "checks contract shape and stable product counts only"
      ]
    },
    "fixture.artifact.campaign_request_lint.v1" => %{
      "id" => "fixture.artifact.campaign_request_lint.v1",
      "model_id" => "artifact.campaign_request_lint.v1",
      "reference_case" => "checked-in campaign request lint report artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/campaign_request_lint_v1.json",
        "contract" => "campaign_request_lint.v1"
      },
      "expected" => %{
        "schema_contract" => "campaign_request_lint.v1",
        "status" => "pass",
        "validation_mode" => "campaign_request_lint",
        "request_type" => "repair",
        "lint_task" => "mix orbital_dynamics.campaign.lint --type repair --request PATH",
        "semantic_validator" => "OrbitalDynamics.CampaignPlanner.request_validation_report/3",
        "error_count" => 0,
        "error_row_count" => 0,
        "source_plan_status" => "pass",
        "source_plan_contract" => "campaign_plan.v1"
      },
      "tolerances" => %{
        "error_count" => 0,
        "error_row_count" => 0
      },
      "evidence" => [
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2",
        "schema-linted by mix orbital_dynamics.schema.lint"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not full campaign request validation",
        "checks request lint status/counts and source-plan routing only"
      ]
    },
    "fixture.artifact.campaign_strategy.leo_constellation_v3" => %{
      "id" => "fixture.artifact.campaign_strategy.leo_constellation_v3",
      "model_id" => "artifact.campaign_strategy.v3",
      "reference_case" => "checked-in LEO constellation campaign strategy artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/leo_constellation_campaign_strategy_v3.json",
        "contract" => "campaign_strategy.v3"
      },
      "expected" => %{
        "schema_version" => 3,
        "planner" => "OrbitalDynamics.CampaignPlanner.V3",
        "branch_count" => 27,
        "recommended_branch_id" => "derived_urgent_target_target_hot",
        "ranked_branch_count" => 7,
        "approval_status" => "operator_review_required",
        "warning_count" => 0,
        "score_term_report_model" => "strategy_branch_score_terms",
        "score_term_report_source" => "campaign_strategy.branches.score_terms",
        "score_term_report_row_count" => 1674,
        "score_term_report_derived_row_count" => 1674,
        "score_term_report_selected_row_count" => 62,
        "score_term_report_key_count" => 62,
        "score_term_report_key_counts" => %{
          "approval_boundary_pressure_penalty" => 1,
          "approval_load_penalty" => 1,
          "asset_balance_score" => 1,
          "battery_depletion_pressure_penalty" => 1,
          "branch_probability" => 1,
          "candidate_diff_pressure_penalty" => 1,
          "candidate_rejection_pressure_penalty" => 1,
          "command_window_pressure_penalty" => 1,
          "contact_allocation_pressure_penalty" => 1,
          "contact_contention_pressure_penalty" => 1,
          "contact_filter_pressure_penalty" => 1,
          "contact_intent_pressure_penalty" => 1,
          "coverage_score" => 1,
          "downlink_completion_score" => 1,
          "execution_feedback_pressure_penalty" => 1,
          "expected_score" => 1,
          "feedback_adjustment_score" => 1,
          "fuel_preservation_score" => 1,
          "import_readiness_pressure_penalty" => 1,
          "latency_penalty" => 1,
          "link_capacity_pressure_penalty" => 1,
          "maneuver_review_pressure_penalty" => 1,
          "mission_value_score" => 1,
          "model_acceptance_pressure_penalty" => 1,
          "objective_gap_pressure_penalty" => 1,
          "operational_readiness_pressure_penalty" => 1,
          "operational_timeline_pressure_penalty" => 1,
          "operator_training_pressure_penalty" => 1,
          "priority_commitment_score" => 1,
          "provider_counteroffer_pressure_penalty" => 1,
          "provider_reservation_request_pressure_penalty" => 1,
          "quality_gate_pressure_penalty" => 1,
          "raw_score" => 1,
          "relay_data_path_pressure_penalty" => 1,
          "refresh_budget_pressure_penalty" => 1,
          "refresh_freshness_pressure_penalty" => 1,
          "resource_availability_pressure_penalty" => 1,
          "resource_filter_pressure_penalty" => 1,
          "resource_margin_pressure_penalty" => 1,
          "resource_projection_pressure_penalty" => 1,
          "resource_score" => 1,
          "revisit_score" => 1,
          "risk_penalty" => 1,
          "schedule_stability_penalty" => 1,
          "schema_validation_pressure_penalty" => 1,
          "station_calendar_pressure_penalty" => 1,
          "station_reservation_conflict_pressure_penalty" => 1,
          "station_reservation_expiration_pressure_penalty" => 1,
          "storage_downlink_pressure_penalty" => 1,
          "timeline_activity_state_pressure_penalty" => 1,
          "timeline_dependency_impact_pressure_penalty" => 1,
          "timeline_diff_pressure_penalty" => 1,
          "timeline_feedback_pressure_penalty" => 1,
          "timeline_integrity_pressure_penalty" => 1,
          "timeline_lifecycle_pressure_penalty" => 1,
          "timeline_precondition_pressure_penalty" => 1,
          "timeline_preservation_pressure_penalty" => 1,
          "timeline_pressure_penalty" => 1,
          "timeline_publication_pressure_penalty" => 1,
          "timeline_transition_application_pressure_penalty" => 1,
          "validation_refresh_pressure_penalty" => 1,
          "validation_safety_case_pressure_penalty" => 1
        },
        "score_term_report_row_derived_key_counts" => %{
          "approval_boundary_pressure_penalty" => 27,
          "approval_load_penalty" => 27,
          "asset_balance_score" => 27,
          "battery_depletion_pressure_penalty" => 27,
          "branch_probability" => 27,
          "candidate_diff_pressure_penalty" => 27,
          "candidate_rejection_pressure_penalty" => 27,
          "command_window_pressure_penalty" => 27,
          "contact_allocation_pressure_penalty" => 27,
          "contact_contention_pressure_penalty" => 27,
          "contact_filter_pressure_penalty" => 27,
          "contact_intent_pressure_penalty" => 27,
          "coverage_score" => 27,
          "downlink_completion_score" => 27,
          "execution_feedback_pressure_penalty" => 27,
          "expected_score" => 27,
          "feedback_adjustment_score" => 27,
          "fuel_preservation_score" => 27,
          "import_readiness_pressure_penalty" => 27,
          "latency_penalty" => 27,
          "link_capacity_pressure_penalty" => 27,
          "maneuver_review_pressure_penalty" => 27,
          "mission_value_score" => 27,
          "model_acceptance_pressure_penalty" => 27,
          "objective_gap_pressure_penalty" => 27,
          "operational_readiness_pressure_penalty" => 27,
          "operational_timeline_pressure_penalty" => 27,
          "operator_training_pressure_penalty" => 27,
          "priority_commitment_score" => 27,
          "provider_counteroffer_pressure_penalty" => 27,
          "provider_reservation_request_pressure_penalty" => 27,
          "quality_gate_pressure_penalty" => 27,
          "raw_score" => 27,
          "relay_data_path_pressure_penalty" => 27,
          "refresh_budget_pressure_penalty" => 27,
          "refresh_freshness_pressure_penalty" => 27,
          "resource_availability_pressure_penalty" => 27,
          "resource_filter_pressure_penalty" => 27,
          "resource_margin_pressure_penalty" => 27,
          "resource_projection_pressure_penalty" => 27,
          "resource_score" => 27,
          "revisit_score" => 27,
          "risk_penalty" => 27,
          "schedule_stability_penalty" => 27,
          "schema_validation_pressure_penalty" => 27,
          "station_calendar_pressure_penalty" => 27,
          "station_reservation_conflict_pressure_penalty" => 27,
          "station_reservation_expiration_pressure_penalty" => 27,
          "storage_downlink_pressure_penalty" => 27,
          "timeline_activity_state_pressure_penalty" => 27,
          "timeline_dependency_impact_pressure_penalty" => 27,
          "timeline_diff_pressure_penalty" => 27,
          "timeline_feedback_pressure_penalty" => 27,
          "timeline_integrity_pressure_penalty" => 27,
          "timeline_lifecycle_pressure_penalty" => 27,
          "timeline_precondition_pressure_penalty" => 27,
          "timeline_preservation_pressure_penalty" => 27,
          "timeline_pressure_penalty" => 27,
          "timeline_publication_pressure_penalty" => 27,
          "timeline_transition_application_pressure_penalty" => 27,
          "validation_refresh_pressure_penalty" => 27,
          "validation_safety_case_pressure_penalty" => 27
        },
        "score_term_report_validation_refresh_pressure_row_count" => 27,
        "score_term_report_score_term_source" => "campaign_strategy.branches.score_terms",
        "score_term_report_model_limit_count" => 4
      },
      "tolerances" => %{
        "schema_version" => 0,
        "branch_count" => 0,
        "ranked_branch_count" => 0,
        "warning_count" => 0,
        "score_term_report_row_count" => 0,
        "score_term_report_derived_row_count" => 0,
        "score_term_report_selected_row_count" => 0,
        "score_term_report_key_count" => 0,
        "score_term_report_validation_refresh_pressure_row_count" => 0,
        "score_term_report_model_limit_count" => 0
      },
      "evidence" => [
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2",
        "schema-linted by mix orbital_dynamics.schema.lint"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external mission validation",
        "checks contract shape and stable product counts only"
      ]
    }
  }

  def all, do: @fixtures
end
