defmodule OrbitalDynamics.Validation.ReferenceFixtures.Orbital do
  @moduledoc false

  @fixtures %{
    "fixture.event.access.equator_overhead_120s" => %{
      "id" => "fixture.event.access.equator_overhead_120s",
      "model_id" => "event.access_windows",
      "reference_case" => "manual three-sample equatorial overhead access window",
      "validation_level" => "analysis",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "ground_station" => %{
          "id" => "equator",
          "latitude_deg" => 0.0,
          "longitude_deg" => 0.0,
          "minimum_elevation_deg" => 0.0
        },
        "sample_epochs_s" => [0.0, 60.0, 120.0],
        "sample_positions" => [
          "overhead_station_500km",
          "overhead_station_500km",
          "opposite_earth_500km"
        ]
      },
      "expected" => %{
        "window_count" => 1,
        "first_window_starts_at_s" => 0.0,
        "first_window_ends_at_s" => 89.45807391804992,
        "first_window_duration_s" => 89.45807391804992,
        "first_window_sample_count" => 2,
        "first_window_max_elevation_deg" => 90.0
      },
      "tolerances" => %{
        "window_count" => 0,
        "first_window_starts_at_s" => 1.0e-12,
        "first_window_ends_at_s" => 1.0e-9,
        "first_window_duration_s" => 1.0e-9,
        "first_window_sample_count" => 0,
        "first_window_max_elevation_deg" => 1.0e-9
      },
      "evidence" => [
        "generated by OrbitalDynamics.EventDetectors.AccessWindows",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "covers simple spherical Earth access geometry only"
      ]
    },
    "fixture.event.eclipse.cylindrical_shadow_120s" => %{
      "id" => "fixture.event.eclipse.cylindrical_shadow_120s",
      "model_id" => "event.eclipses",
      "reference_case" => "manual three-sample cylindrical Earth-shadow interval",
      "validation_level" => "analysis",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "sun_direction" => [1.0, 0.0, 0.0],
        "sample_epochs_s" => [0.0, 60.0, 120.0],
        "sample_positions" => [
          "anti_sunward_inside_shadow_500km",
          "anti_sunward_inside_shadow_500km",
          "sunward_500km"
        ]
      },
      "expected" => %{
        "interval_count" => 1,
        "first_interval_starts_at_s" => 0.0,
        "first_interval_ends_at_s" => 88.8684602035115,
        "first_interval_duration_s" => 88.8684602035115,
        "first_interval_sample_count" => 2,
        "first_interval_minimum_shadow_axis_distance_km" => 0.0,
        "first_interval_maximum_shadow_margin_km" => 6378.1363
      },
      "tolerances" => %{
        "interval_count" => 0,
        "first_interval_starts_at_s" => 1.0e-12,
        "first_interval_ends_at_s" => 1.0e-9,
        "first_interval_duration_s" => 1.0e-9,
        "first_interval_sample_count" => 0,
        "first_interval_minimum_shadow_axis_distance_km" => 1.0e-12,
        "first_interval_maximum_shadow_margin_km" => 1.0e-9
      },
      "evidence" => [
        "generated by OrbitalDynamics.EventDetectors.Eclipses",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "covers cylindrical shadow geometry with fixed Sun direction only"
      ]
    },
    "fixture.event.target_visibility.equator_overhead_120s" => %{
      "id" => "fixture.event.target_visibility.equator_overhead_120s",
      "model_id" => "event.target_visibility",
      "reference_case" => "manual three-sample equatorial target visibility window",
      "validation_level" => "analysis",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "target" => %{
          "id" => "target_a",
          "latitude_deg" => 0.0,
          "longitude_deg" => 0.0,
          "minimum_elevation_deg" => 0.0,
          "priority" => 4.0
        },
        "sample_epochs_s" => [0.0, 60.0, 120.0],
        "sample_positions" => [
          "overhead_target_500km",
          "overhead_target_500km",
          "opposite_earth_500km"
        ]
      },
      "expected" => %{
        "window_count" => 1,
        "first_window_starts_at_s" => 0.0,
        "first_window_ends_at_s" => 89.45807391804992,
        "first_window_duration_s" => 89.45807391804992,
        "first_window_sample_count" => 2,
        "first_window_max_elevation_deg" => 90.0,
        "target_priority" => 4.0
      },
      "tolerances" => %{
        "window_count" => 0,
        "first_window_starts_at_s" => 1.0e-12,
        "first_window_ends_at_s" => 1.0e-9,
        "first_window_duration_s" => 1.0e-9,
        "first_window_sample_count" => 0,
        "first_window_max_elevation_deg" => 1.0e-9,
        "target_priority" => 0
      },
      "evidence" => [
        "generated by OrbitalDynamics.EventDetectors.TargetVisibility",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "covers simple spherical Earth target geometry only"
      ]
    },
    "fixture.event.ground_track.latitude_equator_60s" => %{
      "id" => "fixture.event.ground_track.latitude_equator_60s",
      "model_id" => "event.ground_track_crossings",
      "reference_case" => "manual two-sample geocentric equator crossing",
      "validation_level" => "analysis",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "crossing" => "latitude",
        "latitude_deg" => 0.0,
        "sample_epochs_s" => [0.0, 60.0],
        "sample_positions" => [
          "unit_radius_latitude_minus_45_deg",
          "unit_radius_latitude_plus_45_deg"
        ]
      },
      "expected" => %{
        "crossing_count" => 1,
        "first_crossing_epoch_s" => 30.0,
        "first_crossing_target_deg" => 0.0,
        "first_crossing_direction" => "northbound"
      },
      "tolerances" => %{
        "crossing_count" => 0,
        "first_crossing_epoch_s" => 1.0e-12,
        "first_crossing_target_deg" => 0,
        "first_crossing_direction" => 0
      },
      "evidence" => [
        "generated by OrbitalDynamics.EventDetectors.GroundTrackCrossings",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "geocentric inertial crossing only"
      ]
    },
    "fixture.force_model.atmospheric_drag.earth_400km" => %{
      "id" => "fixture.force_model.atmospheric_drag.earth_400km",
      "model_id" => "force_model.atmospheric_drag",
      "reference_case" =>
        "400 km equatorial Earth/J2000 state with constant co-rotation and reference atmosphere density",
      "validation_level" => "educational",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "altitude_km" => 400.0,
        "velocity_km_s" => [0.0, 7.67, 0.0],
        "dry_mass_kg" => 100.0,
        "propellant_mass_kg" => 20.0,
        "drag_area_m2" => 4.0,
        "drag_coefficient" => 2.2,
        "atmosphere_provider_id" => "environment.provider.atmosphere.exponential_reference",
        "earth_rotation_provider_id" => "environment.provider.earth_rotation.constant_rate"
      },
      "expected" => %{
        "altitude_km" => 400.0,
        "density_kg_m3" => 3.89e-12,
        "spacecraft_mass_kg" => 120.0,
        "atmosphere_velocity_km_s" => [0.0, 0.494269493852745, 0.0],
        "relative_velocity_km_s" => [0.0, 7.175730506147255, 0.0],
        "relative_speed_km_s" => 7.175730506147255,
        "acceleration_km_s2" => [0.0, -7.3443484134077065e-9, 0.0],
        "acceleration_magnitude_km_s2" => 7.3443484134077065e-9,
        "atmosphere_provider_id" => "environment.provider.atmosphere.exponential_reference",
        "earth_rotation_provider_id" => "environment.provider.earth_rotation.constant_rate",
        "model_limit_count" => 7
      },
      "tolerances" => %{
        "altitude_km" => 1.0e-12,
        "density_kg_m3" => 1.0e-18,
        "spacecraft_mass_kg" => 1.0e-12,
        "atmosphere_velocity_km_s" => 1.0e-12,
        "relative_velocity_km_s" => 1.0e-12,
        "relative_speed_km_s" => 1.0e-12,
        "acceleration_km_s2" => 1.0e-15,
        "acceleration_magnitude_km_s2" => 1.0e-15,
        "atmosphere_provider_id" => 0,
        "earth_rotation_provider_id" => 0,
        "model_limit_count" => 0
      },
      "evidence" => [
        "generated through OrbitalDynamics.atmospheric_drag_acceleration/4",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "covers one 400 km equatorial LEO state only",
        "acceleration is integrated only by the opt-in scalar two-body-drag and J2-drag propagators"
      ]
    },
    "fixture.propagator.two_body_drag.earth_400km_600s" => %{
      "id" => "fixture.propagator.two_body_drag.earth_400km_600s",
      "model_id" => "propagator.two_body_drag",
      "reference_case" =>
        "600 second 400 km circular Earth/J2000 propagation with point-mass gravity and reference atmospheric drag",
      "validation_level" => "educational",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "altitude_km" => 400.0,
        "duration_s" => 600.0,
        "output_step_s" => 600.0,
        "max_step_s" => 10.0,
        "dry_mass_kg" => 100.0,
        "propellant_mass_kg" => 20.0,
        "drag_area_m2" => 4.0,
        "drag_coefficient" => 2.2,
        "atmosphere_provider_id" => "environment.provider.atmosphere.exponential_reference"
      },
      "expected" => %{
        "initial_position_km" => [6778.1363, 0.0, 0.0],
        "initial_velocity_km_s" => [0.0, 7.6685585713854145, 0.0],
        "final_position_km" => [5275.519248418085, 4255.821945696241, 0.0],
        "final_velocity_km_s" => [-4.814896084241612, 5.968543277040851, 0.0],
        "initial_specific_energy_km2_s2" => -29.40339528138435,
        "final_specific_energy_km2_s2" => -29.403429060342003,
        "specific_energy_change_km2_s2" => -3.377895765410699e-5,
        "atmosphere_provider_id" => "environment.provider.atmosphere.exponential_reference",
        "earth_rotation_provider_id" => "environment.provider.earth_rotation.constant_rate",
        "model_limit_count" => 7
      },
      "tolerances" => %{
        "initial_position_km" => 1.0e-12,
        "initial_velocity_km_s" => 1.0e-12,
        "final_position_km" => 1.0e-8,
        "final_velocity_km_s" => 1.0e-11,
        "initial_specific_energy_km2_s2" => 1.0e-10,
        "final_specific_energy_km2_s2" => 1.0e-10,
        "specific_energy_change_km2_s2" => 1.0e-10,
        "atmosphere_provider_id" => 0,
        "earth_rotation_provider_id" => 0,
        "model_limit_count" => 0
      },
      "evidence" => [
        "generated through OrbitalDynamics.analyze_study/2 with OrbitalDynamics.Propagators.TwoBodyDrag",
        "zero-density propagation is checked against scalar fixed-step two-body states",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "covers one 400 km equatorial LEO state over 600 seconds",
        "uses the built-in reference atmosphere and constant Earth rotation"
      ]
    },
    "fixture.propagator.j2_drag.earth_400km_24h_step_convergence" => %{
      "id" => "fixture.propagator.j2_drag.earth_400km_24h_step_convergence",
      "model_id" => "propagator.j2_drag",
      "reference_case" =>
        "24 hour 400 km circular Earth/J2000/TDB propagation with point-mass gravity, J2, reference atmospheric drag, and 10-second versus 5-second fixed-step comparison",
      "validation_level" => "educational",
      "fixture_type" => "curated_internal_convergence",
      "inputs" => %{
        "central_body" => "earth",
        "altitude_km" => 400.0,
        "duration_s" => 86_400.0,
        "output_step_s" => 3_600.0,
        "coarse_max_step_s" => 10.0,
        "fine_max_step_s" => 5.0,
        "dry_mass_kg" => 100.0,
        "propellant_mass_kg" => 20.0,
        "drag_area_m2" => 4.0,
        "drag_coefficient" => 2.2,
        "atmosphere_provider_id" => "environment.provider.atmosphere.exponential_reference",
        "atmosphere_source_revision" => "exponential-reference.v1"
      },
      "expected" => %{
        "sample_count" => 25,
        "coarse_final_position_km" => [-5345.307780382329, -4136.077089159638, 0.0],
        "coarse_final_velocity_km_s" => [4.701717395622806, -6.085095329287687, 0.0],
        "fine_final_position_km" => [-5345.308146291314, -4136.076628981799, 0.0],
        "fine_final_velocity_km_s" => [4.7017168631062605, -6.085095732989827, 0.0],
        "coarse_fine_position_delta_km" => 5.879226380308366e-4,
        "coarse_fine_velocity_delta_km_s" => 6.682434356056432e-7,
        "declared_position_tolerance_km" => 1.0e-3,
        "declared_velocity_tolerance_km_s" => 1.0e-6,
        "convergence_classification" => "pass_internal_only",
        "atmosphere_provider_id" => "environment.provider.atmosphere.exponential_reference",
        "atmosphere_source_revision" => "exponential-reference.v1",
        "model_limit_count" => 12
      },
      "tolerances" => %{
        "sample_count" => 0,
        "coarse_final_position_km" => 1.0e-8,
        "coarse_final_velocity_km_s" => 1.0e-11,
        "fine_final_position_km" => 1.0e-8,
        "fine_final_velocity_km_s" => 1.0e-11,
        "coarse_fine_position_delta_km" => 1.0e-8,
        "coarse_fine_velocity_delta_km_s" => 1.0e-11,
        "declared_position_tolerance_km" => 0,
        "declared_velocity_tolerance_km_s" => 0,
        "convergence_classification" => 0,
        "atmosphere_provider_id" => 0,
        "atmosphere_source_revision" => 0,
        "model_limit_count" => 0
      },
      "evidence" => [
        "generated through OrbitalDynamics.Propagators.J2Drag with one combined acceleration derivative",
        "10-second and 5-second fixed-step outputs are compared over the full declared 24-hour envelope",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal numerical step-convergence regression, not external truth or acceptance evidence",
        "covers one 400 km equatorial LEO state and one built-in reference atmosphere only",
        "tolerance bounds only the observed 10-second versus 5-second step difference"
      ]
    },
    "fixture.j2.circular_leo_600s" => %{
      "id" => "fixture.j2.circular_leo_600s",
      "model_id" => "propagator.j2",
      "reference_case" => "7000 km circular equatorial LEO propagated for 600 s with J2",
      "validation_level" => "educational",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "initial_position_km" => [7000.0, 0.0, 0.0],
        "initial_velocity_km_s" => [0.0, 7.546053290107542, 0.0],
        "duration_s" => 600.0,
        "output_step_s" => 120.0,
        "propagator_opts" => %{"max_step_s" => 10.0}
      },
      "expected" => %{
        "sample_count" => 6,
        "final_epoch_s" => 600.0,
        "final_position_km" => [5584.070997735894, 4217.992693724331, 0.0],
        "final_velocity_km_s" => [-4.554400191561496, 6.019254825378945, 0.0]
      },
      "tolerances" => %{
        "sample_count" => 0,
        "final_epoch_s" => 1.0e-12,
        "final_position_km" => 1.0e-5,
        "final_velocity_km_s" => 1.0e-8
      },
      "evidence" => [
        "generated by OrbitalDynamics.Propagators.J2 fixed-step RK4",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "J2 is the only perturbation",
        "covers one near-circular equatorial LEO case only"
      ]
    },
    "fixture.two_body.circular_leo_600s" => %{
      "id" => "fixture.two_body.circular_leo_600s",
      "model_id" => "propagator.two_body",
      "reference_case" => "7000 km circular equatorial LEO propagated for 600 s",
      "validation_level" => "educational",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "initial_position_km" => [7000.0, 0.0, 0.0],
        "initial_velocity_km_s" => [0.0, 7.546053290107542, 0.0],
        "duration_s" => 600.0,
        "output_step_s" => 120.0,
        "propagator_opts" => %{"max_step_s" => 10.0}
      },
      "expected" => %{
        "sample_count" => 6,
        "final_epoch_s" => 600.0,
        "final_position_km" => [5586.094941787218, 4218.4764189319985, 0.0],
        "final_velocity_km_s" => [-4.54754969549011, 6.021852873409085, 0.0]
      },
      "tolerances" => %{
        "sample_count" => 0,
        "final_epoch_s" => 1.0e-12,
        "final_position_km" => 1.0e-6,
        "final_velocity_km_s" => 1.0e-9
      },
      "evidence" => [
        "generated by OrbitalDynamics.Propagators.TwoBody fixed-step RK4",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "covers one near-circular LEO case only"
      ]
    }
  }

  def all, do: @fixtures
end
