defmodule OrbitalDynamics.Validation.ReferenceFixtures.Orbital do
  @moduledoc false

  @fixtures %{
    "fixture.event.access.equator_overhead_120s" => %{
      "id" => "fixture.event.access.equator_overhead_120s",
      "model_id" => "event.access_windows",
      "reference_case" => "manual three-sample equatorial overhead access window",
      "validation_level" => "analysis",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "ground_station" => %{
          "id" => "equator",
          "latitude_deg" => 0.0,
          "longitude_deg" => 0.0,
          "minimum_elevation_deg" => 0.0
        },
        "sample_epochs_s" => [0.0, 60.0, 120.0],
        "sample_positions" => [
          "overhead_station_500km",
          "overhead_station_500km",
          "opposite_earth_500km"
        ]
      },
      "expected" => %{
        "window_count" => 1,
        "first_window_starts_at_s" => 0.0,
        "first_window_ends_at_s" => 89.45807391804992,
        "first_window_duration_s" => 89.45807391804992,
        "first_window_sample_count" => 2,
        "first_window_max_elevation_deg" => 90.0
      },
      "tolerances" => %{
        "window_count" => 0,
        "first_window_starts_at_s" => 1.0e-12,
        "first_window_ends_at_s" => 1.0e-9,
        "first_window_duration_s" => 1.0e-9,
        "first_window_sample_count" => 0,
        "first_window_max_elevation_deg" => 1.0e-9
      },
      "evidence" => [
        "generated by OrbitalDynamics.EventDetectors.AccessWindows",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "covers simple spherical Earth access geometry only"
      ]
    },
    "fixture.event.eclipse.cylindrical_shadow_120s" => %{
      "id" => "fixture.event.eclipse.cylindrical_shadow_120s",
      "model_id" => "event.eclipses",
      "reference_case" => "manual three-sample cylindrical Earth-shadow interval",
      "validation_level" => "analysis",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "sun_direction" => [1.0, 0.0, 0.0],
        "sample_epochs_s" => [0.0, 60.0, 120.0],
        "sample_positions" => [
          "anti_sunward_inside_shadow_500km",
          "anti_sunward_inside_shadow_500km",
          "sunward_500km"
        ]
      },
      "expected" => %{
        "interval_count" => 1,
        "first_interval_starts_at_s" => 0.0,
        "first_interval_ends_at_s" => 88.8684602035115,
        "first_interval_duration_s" => 88.8684602035115,
        "first_interval_sample_count" => 2,
        "first_interval_minimum_shadow_axis_distance_km" => 0.0,
        "first_interval_maximum_shadow_margin_km" => 6378.1363
      },
      "tolerances" => %{
        "interval_count" => 0,
        "first_interval_starts_at_s" => 1.0e-12,
        "first_interval_ends_at_s" => 1.0e-9,
        "first_interval_duration_s" => 1.0e-9,
        "first_interval_sample_count" => 0,
        "first_interval_minimum_shadow_axis_distance_km" => 1.0e-12,
        "first_interval_maximum_shadow_margin_km" => 1.0e-9
      },
      "evidence" => [
        "generated by OrbitalDynamics.EventDetectors.Eclipses",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "covers cylindrical shadow geometry with fixed Sun direction only"
      ]
    },
    "fixture.event.target_visibility.equator_overhead_120s" => %{
      "id" => "fixture.event.target_visibility.equator_overhead_120s",
      "model_id" => "event.target_visibility",
      "reference_case" => "manual three-sample equatorial target visibility window",
      "validation_level" => "analysis",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "target" => %{
          "id" => "target_a",
          "latitude_deg" => 0.0,
          "longitude_deg" => 0.0,
          "minimum_elevation_deg" => 0.0,
          "priority" => 4.0
        },
        "sample_epochs_s" => [0.0, 60.0, 120.0],
        "sample_positions" => [
          "overhead_target_500km",
          "overhead_target_500km",
          "opposite_earth_500km"
        ]
      },
      "expected" => %{
        "window_count" => 1,
        "first_window_starts_at_s" => 0.0,
        "first_window_ends_at_s" => 89.45807391804992,
        "first_window_duration_s" => 89.45807391804992,
        "first_window_sample_count" => 2,
        "first_window_max_elevation_deg" => 90.0,
        "target_priority" => 4.0
      },
      "tolerances" => %{
        "window_count" => 0,
        "first_window_starts_at_s" => 1.0e-12,
        "first_window_ends_at_s" => 1.0e-9,
        "first_window_duration_s" => 1.0e-9,
        "first_window_sample_count" => 0,
        "first_window_max_elevation_deg" => 1.0e-9,
        "target_priority" => 0
      },
      "evidence" => [
        "generated by OrbitalDynamics.EventDetectors.TargetVisibility",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "covers simple spherical Earth target geometry only"
      ]
    },
    "fixture.event.ground_track.latitude_equator_60s" => %{
      "id" => "fixture.event.ground_track.latitude_equator_60s",
      "model_id" => "event.ground_track_crossings",
      "reference_case" => "manual two-sample geocentric equator crossing",
      "validation_level" => "analysis",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "crossing" => "latitude",
        "latitude_deg" => 0.0,
        "sample_epochs_s" => [0.0, 60.0],
        "sample_positions" => [
          "unit_radius_latitude_minus_45_deg",
          "unit_radius_latitude_plus_45_deg"
        ]
      },
      "expected" => %{
        "crossing_count" => 1,
        "first_crossing_epoch_s" => 30.0,
        "first_crossing_target_deg" => 0.0,
        "first_crossing_direction" => "northbound"
      },
      "tolerances" => %{
        "crossing_count" => 0,
        "first_crossing_epoch_s" => 1.0e-12,
        "first_crossing_target_deg" => 0,
        "first_crossing_direction" => 0
      },
      "evidence" => [
        "generated by OrbitalDynamics.EventDetectors.GroundTrackCrossings",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "geocentric inertial crossing only"
      ]
    },
    "fixture.j2.circular_leo_600s" => %{
      "id" => "fixture.j2.circular_leo_600s",
      "model_id" => "propagator.j2",
      "reference_case" => "7000 km circular equatorial LEO propagated for 600 s with J2",
      "validation_level" => "educational",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "initial_position_km" => [7000.0, 0.0, 0.0],
        "initial_velocity_km_s" => [0.0, 7.546053290107542, 0.0],
        "duration_s" => 600.0,
        "output_step_s" => 120.0,
        "propagator_opts" => %{"max_step_s" => 10.0}
      },
      "expected" => %{
        "sample_count" => 6,
        "final_epoch_s" => 600.0,
        "final_position_km" => [5584.070997735894, 4217.992693724331, 0.0],
        "final_velocity_km_s" => [-4.554400191561496, 6.019254825378945, 0.0]
      },
      "tolerances" => %{
        "sample_count" => 0,
        "final_epoch_s" => 1.0e-12,
        "final_position_km" => 1.0e-5,
        "final_velocity_km_s" => 1.0e-8
      },
      "evidence" => [
        "generated by OrbitalDynamics.Propagators.J2 fixed-step RK4",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "J2 is the only perturbation",
        "covers one near-circular equatorial LEO case only"
      ]
    },
    "fixture.two_body.circular_leo_600s" => %{
      "id" => "fixture.two_body.circular_leo_600s",
      "model_id" => "propagator.two_body",
      "reference_case" => "7000 km circular equatorial LEO propagated for 600 s",
      "validation_level" => "educational",
      "fixture_type" => "curated_internal_regression",
      "inputs" => %{
        "central_body" => "earth",
        "initial_position_km" => [7000.0, 0.0, 0.0],
        "initial_velocity_km_s" => [0.0, 7.546053290107542, 0.0],
        "duration_s" => 600.0,
        "output_step_s" => 120.0,
        "propagator_opts" => %{"max_step_s" => 10.0}
      },
      "expected" => %{
        "sample_count" => 6,
        "final_epoch_s" => 600.0,
        "final_position_km" => [5586.094941787218, 4218.4764189319985, 0.0],
        "final_velocity_km_s" => [-4.54754969549011, 6.021852873409085, 0.0]
      },
      "tolerances" => %{
        "sample_count" => 0,
        "final_epoch_s" => 1.0e-12,
        "final_position_km" => 1.0e-6,
        "final_velocity_km_s" => 1.0e-9
      },
      "evidence" => [
        "generated by OrbitalDynamics.Propagators.TwoBody fixed-step RK4",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal regression fixture, not an external truth model",
        "covers one near-circular LEO case only"
      ]
    }
  }

  def all, do: @fixtures
end
