defmodule OrbitalDynamics.Validation.ReferenceFixtures.TimelineActivityStateArtifacts do
  @moduledoc false

  @fixtures %{
    "fixture.artifact.timeline_activity_lifecycle_state.v1" => %{
      "id" => "fixture.artifact.timeline_activity_lifecycle_state.v1",
      "model_id" => "artifact.timeline_activity_lifecycle_state.v1",
      "reference_case" => "checked-in single-activity lifecycle-state artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/timeline_activity_lifecycle_state_v1.json",
        "contract" => "timeline_activity_lifecycle_state.v1"
      },
      "expected" => %{
        "schema_contract" => "timeline_activity_lifecycle_state.v1",
        "model" => "artifact_only_timeline_activity_lifecycle_state",
        "validation_level" => "artifact_contract",
        "activity_id" => "cmd_provider",
        "planned_activity_id" => "cmd_provider",
        "realized_activity_id" => "cmd_provider",
        "timeline_id" => "timeline:cmd_provider",
        "planned_timeline_id" => "timeline:cmd_provider",
        "realized_timeline_id" => "timeline:cmd_provider",
        "planned_status" => "executing",
        "realized_status" => "completed",
        "planned_status_category" => "planned",
        "realized_status_category" => "executed",
        "planned_approval_status" => "operator_review_required",
        "realized_approval_status" => "approved",
        "planned_approval_category" => "review_required",
        "realized_approval_category" => "protected",
        "planned_locked" => false,
        "realized_locked" => false,
        "planned_executed" => false,
        "realized_executed" => true,
        "status_transition_decision" => "record",
        "approval_transition_decision" => "review",
        "transition_decision" => "review",
        "review_required" => true,
        "required_operator_action" => "review_activity_approval",
        "required_operator_action_count" => 2,
        "required_operator_action_keys" => "record_timeline_change|review_activity_approval",
        "operator_action_reason_count" => 2,
        "operator_action_reason_keys" =>
          "activity_execution_recorded|approval_grant_requires_operator_authority",
        "import_action" => "review_timeline_diff",
        "status_transition_category" => "execution_recorded",
        "status_transition_operator_action_reason" => "activity_execution_recorded",
        "approval_transition_category" => "approval_granted",
        "approval_transition_operator_action_reason" =>
          "approval_grant_requires_operator_authority",
        "planned_protection_decision" => "mutable",
        "planned_protection_category" => "none",
        "planned_protection_reason" => "no_timeline_protection",
        "realized_protection_decision" => "preserve",
        "realized_protection_category" => "executed",
        "realized_protection_reason" => "activity_already_completed",
        "artifact_only" => true,
        "no_schedule_mutation" => true,
        "no_operator_authority_grant" => true,
        "no_cadence_import" => true,
        "no_command_execution" => true
      },
      "tolerances" => %{
        "required_operator_action_count" => 0,
        "operator_action_reason_count" => 0
      },
      "evidence" => [
        "generated by OrbitalDynamics.Timeline.activity_lifecycle_state/2",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2",
        "schema-linted by mix orbital_dynamics.schema.lint"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external operations validation",
        "checks single-activity lifecycle status, approval, protection, and no-authority boundary only"
      ]
    },
    "fixture.artifact.timeline_activity_status_state.v1" => %{
      "id" => "fixture.artifact.timeline_activity_status_state.v1",
      "model_id" => "artifact.timeline_activity_status_state.v1",
      "reference_case" => "checked-in single-activity status-state artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/timeline_activity_status_state_v1.json",
        "contract" => "timeline_activity_status_state.v1"
      },
      "expected" => %{
        "schema_contract" => "timeline_activity_status_state.v1",
        "model" => "artifact_only_timeline_activity_status_state",
        "validation_level" => "artifact_contract",
        "activity_id" => "obs_provider",
        "planned_activity_id" => "obs_provider",
        "realized_activity_id" => "obs_provider",
        "timeline_id" => "timeline:obs_provider",
        "planned_timeline_id" => "timeline:obs_provider",
        "realized_timeline_id" => "timeline:obs_provider",
        "planned_status" => "executing",
        "realized_status" => "completed",
        "planned_status_category" => "planned",
        "realized_status_category" => "executed",
        "transition_decision" => "record",
        "review_required" => false,
        "required_operator_action" => "record_timeline_change",
        "operator_action_reason" => "activity_execution_recorded",
        "import_action" => "import_replacement_activity",
        "status_transition_field" => "status",
        "status_transition_type" => "changed",
        "status_transition_from" => "executing",
        "status_transition_to" => "completed",
        "status_transition_from_category" => "planned",
        "status_transition_to_category" => "executed",
        "status_transition_category" => "execution_recorded",
        "status_transition_requires_operator_review" => false,
        "status_transition_operator_action_reason" => "activity_execution_recorded",
        "planned_context_status" => "executing",
        "planned_context_source_window_id" => "visibility:obs_provider",
        "realized_context_status" => "completed",
        "artifact_only" => true,
        "no_schedule_mutation" => true,
        "no_operator_authority_grant" => true,
        "no_command_execution" => true
      },
      "tolerances" => %{},
      "evidence" => [
        "generated by OrbitalDynamics.Timeline.activity_status_state/2",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2",
        "schema-linted by mix orbital_dynamics.schema.lint"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external operations validation",
        "checks single-activity status transition, import routing, and no-authority boundary only"
      ]
    },
    "fixture.artifact.timeline_activity_approval_state.v1" => %{
      "id" => "fixture.artifact.timeline_activity_approval_state.v1",
      "model_id" => "artifact.timeline_activity_approval_state.v1",
      "reference_case" => "checked-in single-activity approval-state artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/timeline_activity_approval_state_v1.json",
        "contract" => "timeline_activity_approval_state.v1"
      },
      "expected" => %{
        "schema_contract" => "timeline_activity_approval_state.v1",
        "model" => "artifact_only_timeline_activity_approval_state",
        "validation_level" => "artifact_contract",
        "activity_id" => "cmd_provider",
        "planned_activity_id" => "cmd_provider",
        "realized_activity_id" => "cmd_provider",
        "timeline_id" => "timeline:cmd_provider",
        "planned_timeline_id" => "timeline:cmd_provider",
        "realized_timeline_id" => "timeline:cmd_provider",
        "planned_approval_status" => "operator_review_required",
        "realized_approval_status" => "approved",
        "planned_approval_category" => "review_required",
        "realized_approval_category" => "protected",
        "transition_decision" => "review",
        "review_required" => true,
        "required_operator_action" => "review_activity_approval",
        "operator_action_reason" => "approval_grant_requires_operator_authority",
        "import_action" => "review_timeline_diff",
        "approval_transition_field" => "approval_status",
        "approval_transition_type" => "changed",
        "approval_transition_from" => "operator_review_required",
        "approval_transition_to" => "approved",
        "approval_transition_from_category" => "review_required",
        "approval_transition_to_category" => "protected",
        "approval_transition_category" => "approval_granted",
        "approval_transition_requires_operator_review" => true,
        "approval_transition_operator_action_reason" =>
          "approval_grant_requires_operator_authority",
        "planned_context_approval_status" => "operator_review_required",
        "planned_context_source_window_id" => "command:cmd_provider",
        "realized_context_approval_status" => "approved",
        "artifact_only" => true,
        "no_schedule_mutation" => true,
        "no_operator_authority_grant" => true,
        "no_command_execution" => true
      },
      "tolerances" => %{},
      "evidence" => [
        "generated by OrbitalDynamics.Timeline.activity_approval_state/2",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2",
        "schema-linted by mix orbital_dynamics.schema.lint"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external operations validation",
        "checks single-activity approval transition, operator-review routing, and no-authority boundary only"
      ]
    },
    "fixture.artifact.timeline_lifecycle_state_summary.v1" => %{
      "id" => "fixture.artifact.timeline_lifecycle_state_summary.v1",
      "model_id" => "artifact.timeline_lifecycle_state_summary.v1",
      "reference_case" => "checked-in aggregate lifecycle-state summary artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/timeline_lifecycle_state_summary_v1.json",
        "contract" => "timeline_lifecycle_state_summary.v1"
      },
      "expected" => %{
        "schema_contract" => "timeline_lifecycle_state_summary.v1",
        "model" => "artifact_only_timeline_lifecycle_state_summary",
        "source" => "validation.timeline_lifecycle_state_summary",
        "validation_level" => "artifact_contract",
        "planned_activity_count" => 5,
        "realized_activity_count" => 3,
        "row_count" => 4,
        "row_derived_row_count" => 4,
        "review_row_count" => 2,
        "row_derived_review_row_count" => 2,
        "recordable_count" => 1,
        "row_derived_recordable_count" => 1,
        "preserved_count" => 1,
        "row_derived_preserved_count" => 1,
        "review_required_count" => 2,
        "row_derived_review_required_count" => 2,
        "duplicate_timeline_identity_count" => 1,
        "row_derived_duplicate_timeline_identity_count" => 1,
        "invalid_activity_input_count" => 0,
        "row_derived_invalid_activity_input_count" => 0,
        "transition_decision_counts" => %{"none" => 1, "record" => 1, "review" => 2},
        "row_derived_transition_decision_counts" => %{
          "none" => 1,
          "record" => 1,
          "review" => 2
        },
        "required_operator_action_counts" => %{
          "none" => 1,
          "record_timeline_change" => 1,
          "review_activity_approval" => 1,
          "review_duplicate_timeline_identity" => 1
        },
        "row_derived_required_operator_action_counts" => %{
          "none" => 1,
          "record_timeline_change" => 1,
          "review_activity_approval" => 1,
          "review_duplicate_timeline_identity" => 1
        },
        "operator_action_reason_counts" => %{
          "activity_execution_recorded" => 2,
          "approval_grant_requires_operator_authority" => 1,
          "duplicate_timeline_identity" => 1
        },
        "row_derived_operator_action_reason_counts" => %{
          "activity_execution_recorded" => 2,
          "approval_grant_requires_operator_authority" => 1,
          "duplicate_timeline_identity" => 1
        },
        "import_action_counts" => %{
          "import_replacement_activity" => 1,
          "record_preserved_activity" => 1,
          "review_timeline_diff" => 2
        },
        "row_derived_import_action_counts" => %{
          "import_replacement_activity" => 1,
          "record_preserved_activity" => 1,
          "review_timeline_diff" => 2
        },
        "planned_status_category_counts" => %{"executed" => 1, "planned" => 2},
        "row_derived_planned_status_category_counts" => %{"executed" => 1, "planned" => 2},
        "realized_status_category_counts" => %{"executed" => 3},
        "row_derived_realized_status_category_counts" => %{"executed" => 3},
        "planned_approval_category_counts" => %{
          "other" => 1,
          "protected" => 1,
          "review_required" => 1
        },
        "row_derived_planned_approval_category_counts" => %{
          "other" => 1,
          "protected" => 1,
          "review_required" => 1
        },
        "realized_approval_category_counts" => %{"other" => 1, "protected" => 2},
        "row_derived_realized_approval_category_counts" => %{"other" => 1, "protected" => 2},
        "status_transition_category_counts" => %{"execution_recorded" => 2},
        "row_derived_status_transition_category_counts" => %{"execution_recorded" => 2},
        "approval_transition_category_counts" => %{"approval_granted" => 1},
        "row_derived_approval_transition_category_counts" => %{"approval_granted" => 1},
        "recordable_timeline_keys" => "timeline:obs_record",
        "row_derived_recordable_timeline_keys" => "timeline:obs_record",
        "preserved_timeline_keys" => "timeline:done_keep",
        "row_derived_preserved_timeline_keys" => "timeline:done_keep",
        "review_timeline_keys" => "timeline:cmd_provider|timeline:dup",
        "row_derived_review_timeline_keys" => "timeline:cmd_provider|timeline:dup",
        "review_activity_keys" => "cmd_provider|dup_a|dup_b",
        "row_derived_review_activity_keys" => "cmd_provider|dup_a|dup_b",
        "invalid_activity_input_keys" => "",
        "review_timeline_ids_by_required_operator_action" => %{
          "review_activity_approval" => ["timeline:cmd_provider"],
          "review_duplicate_timeline_identity" => ["timeline:dup"]
        },
        "row_derived_review_timeline_ids_by_required_operator_action" => %{
          "review_activity_approval" => ["timeline:cmd_provider"],
          "review_duplicate_timeline_identity" => ["timeline:dup"]
        },
        "review_timeline_ids_by_operator_action_reason" => %{
          "activity_execution_recorded" => ["timeline:cmd_provider"],
          "approval_grant_requires_operator_authority" => ["timeline:cmd_provider"],
          "duplicate_timeline_identity" => ["timeline:dup"]
        },
        "row_derived_review_timeline_ids_by_operator_action_reason" => %{
          "activity_execution_recorded" => ["timeline:cmd_provider"],
          "approval_grant_requires_operator_authority" => ["timeline:cmd_provider"],
          "duplicate_timeline_identity" => ["timeline:dup"]
        },
        "review_timeline_ids_by_approval_transition_category" => %{
          "approval_granted" => ["timeline:cmd_provider"]
        },
        "row_derived_review_timeline_ids_by_approval_transition_category" => %{
          "approval_granted" => ["timeline:cmd_provider"]
        },
        "execution_boundary" => "artifact_only_no_schedule_mutation",
        "operator_authority" => "not_granted_by_summary",
        "cadence_import" => "not_performed_by_summary",
        "command_execution" => "not_performed_by_summary",
        "identity_match" => "planned and realized rows are paired by timeline identity"
      },
      "tolerances" => %{
        "row_count" => 0,
        "row_derived_row_count" => 0,
        "review_required_count" => 0,
        "row_derived_review_required_count" => 0,
        "duplicate_timeline_identity_count" => 0,
        "row_derived_duplicate_timeline_identity_count" => 0
      },
      "evidence" => [
        "generated by OrbitalDynamics.Timeline.lifecycle_state_summary/3",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2",
        "schema-linted by mix orbital_dynamics.schema.lint"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external operations validation",
        "checks aggregate lifecycle row routing, review identity maps, and no-authority boundary only"
      ]
    },
    "fixture.artifact.timeline_activity_state.v1" => %{
      "id" => "fixture.artifact.timeline_activity_state.v1",
      "model_id" => "artifact.timeline_activity_state.v1",
      "reference_case" => "checked-in timeline activity state artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/timeline_activity_state_v1.json",
        "contract" => "timeline_activity_state.v1"
      },
      "expected" => %{
        "schema_contract" => "timeline_activity_state.v1",
        "model" => "artifact_only_timeline_activity_state",
        "validation_level" => "artifact_contract",
        "state_status" => "review_required",
        "row_count" => 2,
        "row_derived_row_count" => 2,
        "review_required" => true,
        "activity_id" => "cmd_lock",
        "timeline_id" => "timeline:cmd_lock",
        "planned_timeline_id" => "timeline:cmd_lock",
        "feedback_kind" => "command",
        "match_strategy" => "unmatched_planned",
        "planned_status" => "approved",
        "planned_protection_decision" => "preserve",
        "planned_protection_category" => "locked_or_approved",
        "planned_protection_reason" => "activity_locked_or_approved",
        "status_transition_category" => "status_removed",
        "activity_keys" => "cmd_lock|cmd_new",
        "review_activity_keys" => "cmd_lock|cmd_new",
        "status_counts" => %{"planned_only" => 1, "realized_only" => 1},
        "row_derived_status_counts" => %{"planned_only" => 1, "realized_only" => 1},
        "feedback_kind_counts" => %{"command" => 2},
        "row_derived_feedback_kind_counts" => %{"command" => 2},
        "match_strategy_counts" => %{
          "unmatched_planned" => 1,
          "unmatched_realized" => 1
        },
        "row_derived_match_strategy_counts" => %{
          "unmatched_planned" => 1,
          "unmatched_realized" => 1
        },
        "cadence_import_status_counts" => %{"missing" => 1},
        "row_derived_cadence_import_status_counts" => %{"missing" => 1, "unknown" => 1},
        "planned_protection_decision_counts" => %{"preserve" => 1},
        "row_derived_planned_protection_decision_counts" => %{
          "preserve" => 1,
          "unknown" => 1
        },
        "row_derived_status_transition_category_counts" => %{
          "status_added" => 1,
          "status_removed" => 1
        },
        "activity_ids_by_status" => %{
          "planned_only" => ["cmd_lock"],
          "realized_only" => ["cmd_new"]
        },
        "row_derived_activity_ids_by_status" => %{
          "planned_only" => ["cmd_lock"],
          "realized_only" => ["cmd_new"]
        },
        "row_derived_activity_ids_by_match_strategy" => %{
          "unmatched_planned" => ["cmd_lock"],
          "unmatched_realized" => ["cmd_new"]
        },
        "artifact_only" => true,
        "no_schedule_mutation" => true,
        "no_command_execution" => true,
        "source" => "timeline_feedback.reconcile",
        "model_limit_count" => 5
      },
      "tolerances" => %{
        "row_count" => 0,
        "row_derived_row_count" => 0,
        "model_limit_count" => 0
      },
      "evidence" => [
        "generated by OrbitalDynamics.TimelineFeedback.activity_state/3",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2",
        "schema-linted by mix orbital_dynamics.schema.lint"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external execution validation",
        "checks activity-state row routing, review identity, preservation evidence, and no-command/no-mutation boundary only"
      ]
    },
    "fixture.artifact.timeline_activity_precondition_summary.v1" => %{
      "id" => "fixture.artifact.timeline_activity_precondition_summary.v1",
      "model_id" => "artifact.timeline_activity_precondition_summary.v1",
      "reference_case" => "checked-in timeline activity precondition summary artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/timeline_activity_precondition_summary_v1.json",
        "contract" => "timeline_activity_precondition_summary.v1"
      },
      "expected" => %{
        "schema_contract" => "timeline_activity_precondition_summary.v1",
        "model" => "artifact_only_timeline_activity_precondition_summary",
        "validation_level" => "artifact_contract",
        "activity_id" => "cmd_source",
        "timeline_id" => "timeline:cmd_source",
        "activity_type" => "command",
        "precondition_status" => "blocked",
        "blocked_precondition_count" => 2,
        "review_precondition_count" => 1,
        "blocked_precondition_type_keys" => "payload_unavailable|resource_block_declared",
        "review_precondition_type_keys" => "degraded_mode",
        "precondition_count" => 3,
        "row_derived_precondition_status_counts" => %{
          "blocked" => 2,
          "review_required" => 1
        },
        "row_derived_precondition_type_counts" => %{
          "degraded_mode" => 1,
          "payload_unavailable" => 1,
          "resource_block_declared" => 1
        },
        "timeline_identity_activity_id" => "cmd_source",
        "timeline_identity_timeline_id" => "timeline:cmd_source",
        "execution_boundary" => "artifact_only_no_schedule_mutation",
        "operator_authority" => "not_granted_by_precondition_summary",
        "resource_authority" => "not_reserved_by_precondition_summary"
      },
      "tolerances" => %{},
      "evidence" => [
        "generated by OrbitalDynamics.Timeline.activity_precondition_summary/1",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external validation evidence",
        "checks artifact-only precondition status/count routing and no-authority assumptions"
      ]
    }
  }

  def all, do: @fixtures
end
