defmodule OrbitalDynamics.Validation.ReferenceFixtures.TimelineTransitionArtifacts do
  @moduledoc false

  @fixtures %{
    "fixture.artifact.timeline_transition_application_summary.v1" => %{
      "id" => "fixture.artifact.timeline_transition_application_summary.v1",
      "model_id" => "artifact.timeline_transition_application_summary.v1",
      "reference_case" => "checked-in timeline transition application summary artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/timeline_transition_application_summary_v1.json",
        "contract" => "timeline_transition_application_summary.v1"
      },
      "expected" => %{
        "schema_contract" => "timeline_transition_application_summary.v1",
        "model" => "artifact_only_timeline_transition_application_summary",
        "validation_level" => "artifact_contract",
        "source_artifact_type" => "timeline_transition_application_report.v1",
        "source" => "timeline.activities",
        "source_activity_count" => 2,
        "replacement_activity_count" => 3,
        "application_count" => 3,
        "selected_activity_count" => 2,
        "review_required_count" => 2,
        "preserved_source_count" => 1,
        "recorded_replacement_count" => 0,
        "withheld_review_count" => 1,
        "review_application_count" => 2,
        "application_status_counts" => %{
          "operator_review_required" => 1,
          "source_preserved_pending_review" => 1,
          "source_unchanged" => 1
        },
        "transition_decision_counts" => %{
          "none" => 1,
          "preserve_source" => 1,
          "review" => 1
        },
        "required_operator_action_counts" => %{
          "none" => 1,
          "review_added_activity" => 1,
          "review_changed_protected_activity" => 1
        },
        "status_transition_category_counts" => %{"status_added" => 1},
        "approval_transition_category_counts" => %{"approval_review_required" => 1},
        "row_derived_application_status_counts" => %{
          "operator_review_required" => 1,
          "source_preserved_pending_review" => 1
        },
        "row_derived_transition_decision_counts" => %{
          "preserve_source" => 1,
          "review" => 1
        },
        "row_derived_required_operator_action_counts" => %{
          "review_added_activity" => 1,
          "review_changed_protected_activity" => 1
        },
        "row_derived_status_transition_category_counts" => %{"status_added" => 1},
        "row_derived_approval_transition_category_counts" => %{
          "approval_review_required" => 1
        },
        "review_timeline_ids_by_required_operator_action" => %{
          "review_added_activity" => ["timeline:new_cmd"],
          "review_changed_protected_activity" => ["timeline:cmd_lock"]
        },
        "row_derived_review_timeline_ids_by_required_operator_action" => %{
          "review_added_activity" => ["timeline:new_cmd"],
          "review_changed_protected_activity" => ["timeline:cmd_lock"]
        },
        "selected_activity_keys" => "cmd_lock|obs_keep",
        "selected_timeline_keys" => "timeline:cmd_lock|timeline:obs_keep",
        "review_activity_keys" => "cmd_lock|new_cmd",
        "review_timeline_keys" => "timeline:cmd_lock|timeline:new_cmd",
        "withheld_review_timeline_keys" => "timeline:new_cmd",
        "execution_boundary" => "artifact_only_no_schedule_mutation",
        "operator_authority" => "not_granted_by_summary",
        "model_limit_count" => 4
      },
      "tolerances" => %{
        "source_activity_count" => 0,
        "replacement_activity_count" => 0,
        "application_count" => 0,
        "selected_activity_count" => 0,
        "review_required_count" => 0,
        "preserved_source_count" => 0,
        "recorded_replacement_count" => 0,
        "withheld_review_count" => 0,
        "review_application_count" => 0,
        "model_limit_count" => 0
      },
      "evidence" => [
        "generated by OrbitalDynamics.Timeline.transition_application_summary/3",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external transition validation evidence",
        "checks transition-application summary counts, review routing, and no-authority assumptions"
      ]
    },
    "fixture.artifact.timeline_transition_application_selected_integrity_summary.v1" => %{
      "id" => "fixture.artifact.timeline_transition_application_selected_integrity_summary.v1",
      "model_id" => "artifact.timeline_transition_application_summary.v1",
      "reference_case" => "checked-in transition application selected-integrity summary artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" =>
          "study_results/timeline_transition_application_selected_integrity_summary_v1.json",
        "contract" => "timeline_transition_application_summary.v1"
      },
      "expected" => %{
        "schema_contract" => "timeline_transition_application_summary.v1",
        "model" => "artifact_only_timeline_transition_application_summary",
        "validation_level" => "artifact_contract",
        "source_artifact_type" => "timeline_transition_application_report.v1",
        "source" => "fixture.timeline.transition_application.selected_integrity",
        "source_activity_count" => 2,
        "replacement_activity_count" => 1,
        "application_count" => 2,
        "selected_activity_count" => 1,
        "review_required_count" => 2,
        "preserved_source_count" => 1,
        "recorded_replacement_count" => 0,
        "withheld_review_count" => 1,
        "review_application_count" => 2,
        "selected_timeline_integrity_issue_count" => 1,
        "selected_timeline_integrity_review_count" => 1,
        "selected_timeline_integrity_issue_type_counts" => %{
          "missing_dependency_activity" => 1
        },
        "row_derived_selected_timeline_integrity_issue_type_counts" => %{
          "missing_dependency_activity" => 1
        },
        "row_derived_selected_required_operator_action_counts" => %{
          "review_changed_protected_activity" => 1
        },
        "row_derived_selected_review_timeline_ids_by_required_operator_action" => %{
          "review_changed_protected_activity" => ["timeline:cmd_lock"]
        },
        "row_derived_selected_missing_dependency_activity_keys" => "cmd_prereq",
        "application_status_counts" => %{
          "operator_review_required" => 1,
          "source_preserved_pending_review" => 1
        },
        "transition_decision_counts" => %{"preserve_source" => 1, "review" => 1},
        "required_operator_action_counts" => %{
          "review_changed_protected_activity" => 1,
          "review_removed_activity" => 1
        },
        "status_transition_category_counts" => %{"status_removed" => 1},
        "approval_transition_category_counts" => %{"approval_removed" => 1},
        "row_derived_application_status_counts" => %{
          "operator_review_required" => 1,
          "source_preserved_pending_review" => 1
        },
        "row_derived_transition_decision_counts" => %{
          "preserve_source" => 1,
          "review" => 1
        },
        "row_derived_required_operator_action_counts" => %{
          "review_changed_protected_activity" => 1,
          "review_removed_activity" => 1
        },
        "row_derived_status_transition_category_counts" => %{"status_removed" => 1},
        "row_derived_approval_transition_category_counts" => %{"approval_removed" => 1},
        "review_timeline_ids_by_required_operator_action" => %{
          "review_changed_protected_activity" => ["timeline:cmd_lock"],
          "review_removed_activity" => ["timeline:cmd_prereq"]
        },
        "row_derived_review_timeline_ids_by_required_operator_action" => %{
          "review_changed_protected_activity" => ["timeline:cmd_lock"],
          "review_removed_activity" => ["timeline:cmd_prereq"]
        },
        "selected_activity_keys" => "cmd_lock",
        "selected_timeline_keys" => "timeline:cmd_lock",
        "review_activity_keys" => "cmd_lock|cmd_prereq",
        "review_timeline_keys" => "timeline:cmd_lock|timeline:cmd_prereq",
        "withheld_review_timeline_keys" => "timeline:cmd_prereq",
        "execution_boundary" => "artifact_only_no_schedule_mutation",
        "operator_authority" => "not_granted_by_summary",
        "model_limit_count" => 4
      },
      "tolerances" => %{
        "source_activity_count" => 0,
        "replacement_activity_count" => 0,
        "application_count" => 0,
        "selected_activity_count" => 0,
        "review_required_count" => 0,
        "preserved_source_count" => 0,
        "recorded_replacement_count" => 0,
        "withheld_review_count" => 0,
        "review_application_count" => 0,
        "selected_timeline_integrity_issue_count" => 0,
        "selected_timeline_integrity_review_count" => 0,
        "model_limit_count" => 0
      },
      "evidence" => [
        "generated by OrbitalDynamics.timeline_transition_application_summary/3",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external transition validation evidence",
        "checks compact selected-integrity summary routing and no-authority assumptions"
      ]
    },
    "fixture.artifact.timeline_transition_application_report.v1" => %{
      "id" => "fixture.artifact.timeline_transition_application_report.v1",
      "model_id" => "artifact.timeline_transition_application_report.v1",
      "reference_case" => "checked-in timeline transition application artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" => "study_results/timeline_transition_application_report_v1.json",
        "contract" => "timeline_transition_application_report.v1"
      },
      "expected" => %{
        "schema_contract" => "timeline_transition_application_report.v1",
        "model" => "artifact_only_timeline_transition_application",
        "source" => "fixture.timeline.transition_application",
        "source_activity_count" => 3,
        "replacement_activity_count" => 3,
        "application_count" => 4,
        "selected_activity_count" => 2,
        "preserved_source_count" => 1,
        "recorded_replacement_count" => 0,
        "review_required_count" => 3,
        "withheld_review_count" => 2,
        "selected_timeline_integrity_issue_count" => 0,
        "selected_timeline_integrity_review_count" => 0,
        "application_status_counts" => %{
          "operator_review_required" => 2,
          "source_preserved_pending_review" => 1,
          "source_unchanged" => 1
        },
        "row_derived_application_status_counts" => %{
          "operator_review_required" => 2,
          "source_preserved_pending_review" => 1,
          "source_unchanged" => 1
        },
        "transition_decision_counts" => %{"none" => 1, "preserve_source" => 1, "review" => 2},
        "row_derived_transition_decision_counts" => %{
          "none" => 1,
          "preserve_source" => 1,
          "review" => 2
        },
        "status_transition_counts" => %{"added" => 1, "removed" => 1},
        "row_derived_status_transition_counts" => %{"added" => 1, "removed" => 1},
        "status_transition_category_counts" => %{"status_added" => 1, "status_removed" => 1},
        "row_derived_status_transition_category_counts" => %{
          "status_added" => 1,
          "status_removed" => 1
        },
        "approval_transition_counts" => %{"added" => 1, "removed" => 1},
        "row_derived_approval_transition_counts" => %{"added" => 1, "removed" => 1},
        "approval_transition_category_counts" => %{
          "approval_removed" => 1,
          "approval_review_required" => 1
        },
        "row_derived_approval_transition_category_counts" => %{
          "approval_removed" => 1,
          "approval_review_required" => 1
        },
        "required_operator_action_counts" => %{
          "none" => 1,
          "review_added_activity" => 1,
          "review_changed_protected_activity" => 1,
          "review_removed_activity" => 1
        },
        "row_derived_required_operator_action_counts" => %{
          "none" => 1,
          "review_added_activity" => 1,
          "review_changed_protected_activity" => 1,
          "review_removed_activity" => 1
        },
        "application_ids_by_status" => %{
          "operator_review_required" => [
            "timeline_diff:timeline:new_cmd",
            "timeline_diff:timeline:old_contact"
          ],
          "source_preserved_pending_review" => ["timeline_diff:timeline:cmd_lock"],
          "source_unchanged" => ["timeline_diff:timeline:obs_keep"]
        },
        "row_derived_application_ids_by_status" => %{
          "operator_review_required" => [
            "timeline_diff:timeline:new_cmd",
            "timeline_diff:timeline:old_contact"
          ],
          "source_preserved_pending_review" => ["timeline_diff:timeline:cmd_lock"],
          "source_unchanged" => ["timeline_diff:timeline:obs_keep"]
        },
        "execution_boundary" => "artifact_only_no_schedule_mutation",
        "review_gate" =>
          "review-required transitions withhold replacement selection until an operator decision",
        "model_limit_count" => 4
      },
      "tolerances" => %{
        "source_activity_count" => 0,
        "replacement_activity_count" => 0,
        "application_count" => 0,
        "selected_activity_count" => 0,
        "preserved_source_count" => 0,
        "recorded_replacement_count" => 0,
        "review_required_count" => 0,
        "withheld_review_count" => 0,
        "selected_timeline_integrity_issue_count" => 0,
        "selected_timeline_integrity_review_count" => 0,
        "model_limit_count" => 0
      },
      "evidence" => [
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2",
        "schema-linted by mix orbital_dynamics.schema.lint"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external timeline mutation validation",
        "checks transition application counts, review-gate routing, selected-activity counts, and no-schedule-mutation boundary only"
      ]
    },
    "fixture.artifact.timeline_transition_application_selected_integrity.v1" => %{
      "id" => "fixture.artifact.timeline_transition_application_selected_integrity.v1",
      "model_id" => "artifact.timeline_transition_application_report.v1",
      "reference_case" => "checked-in transition application selected-integrity review artifact",
      "validation_level" => "artifact_contract",
      "fixture_type" => "curated_internal_artifact_regression",
      "inputs" => %{
        "artifact_path" =>
          "study_results/timeline_transition_application_selected_integrity_v1.json",
        "contract" => "timeline_transition_application_report.v1"
      },
      "expected" => %{
        "schema_contract" => "timeline_transition_application_report.v1",
        "model" => "artifact_only_timeline_transition_application",
        "source" => "fixture.timeline.transition_application.selected_integrity",
        "source_activity_count" => 2,
        "replacement_activity_count" => 1,
        "application_count" => 2,
        "selected_activity_count" => 1,
        "preserved_source_count" => 1,
        "recorded_replacement_count" => 0,
        "review_required_count" => 2,
        "withheld_review_count" => 1,
        "selected_timeline_integrity_issue_count" => 1,
        "selected_timeline_integrity_review_count" => 1,
        "selected_timeline_integrity_issue_type_counts" => %{
          "missing_dependency_activity" => 1
        },
        "row_derived_selected_timeline_integrity_issue_type_counts" => %{
          "missing_dependency_activity" => 1
        },
        "row_derived_selected_required_operator_action_counts" => %{
          "review_changed_protected_activity" => 1
        },
        "row_derived_selected_application_ids_by_required_operator_action" => %{
          "review_changed_protected_activity" => ["timeline_diff:timeline:cmd_lock"]
        },
        "row_derived_selected_missing_dependency_activity_keys" => "cmd_prereq",
        "application_status_counts" => %{
          "operator_review_required" => 1,
          "source_preserved_pending_review" => 1
        },
        "row_derived_application_status_counts" => %{
          "operator_review_required" => 1,
          "source_preserved_pending_review" => 1
        },
        "required_operator_action_counts" => %{
          "review_changed_protected_activity" => 1,
          "review_removed_activity" => 1
        },
        "row_derived_required_operator_action_counts" => %{
          "review_changed_protected_activity" => 1,
          "review_removed_activity" => 1
        },
        "application_ids_by_status" => %{
          "operator_review_required" => ["timeline_diff:timeline:cmd_prereq"],
          "source_preserved_pending_review" => ["timeline_diff:timeline:cmd_lock"]
        },
        "row_derived_application_ids_by_status" => %{
          "operator_review_required" => ["timeline_diff:timeline:cmd_prereq"],
          "source_preserved_pending_review" => ["timeline_diff:timeline:cmd_lock"]
        },
        "execution_boundary" => "artifact_only_no_schedule_mutation",
        "review_gate" =>
          "review-required transitions withhold replacement selection until an operator decision",
        "model_limit_count" => 4
      },
      "tolerances" => %{
        "source_activity_count" => 0,
        "replacement_activity_count" => 0,
        "application_count" => 0,
        "selected_activity_count" => 0,
        "preserved_source_count" => 0,
        "recorded_replacement_count" => 0,
        "review_required_count" => 0,
        "withheld_review_count" => 0,
        "selected_timeline_integrity_issue_count" => 0,
        "selected_timeline_integrity_review_count" => 0,
        "model_limit_count" => 0
      },
      "evidence" => [
        "generated by OrbitalDynamics.timeline_transition_application_report/3",
        "checked by OrbitalDynamics.Validation.verify_reference_fixture/2"
      ],
      "known_limits" => [
        "internal checked-in artifact regression, not external timeline mutation validation",
        "checks selected-activity integrity review routing and no-schedule-mutation boundary only"
      ]
    }
  }

  def all, do: @fixtures
end
