defmodule OrbitalDynamics.CandidateRefresh.Capabilities do
  @moduledoc false

  alias OrbitalDynamics.CandidateRefresh.CandidateActivityFields
  alias OrbitalDynamics.CandidateRefresh.CandidateDiffReport
  alias OrbitalDynamics.CandidateRefresh.ModelLimits

  @unavailable_availability_aliases ["outage", "down", "offline"]
  @unavailable_station_tokens ["unavailable", "maintenance" | @unavailable_availability_aliases]
  @station_availability_precedence %{
    "unavailable" => 5,
    "maintenance" => 5,
    "reserved" => 4,
    "reduced_capacity" => 3,
    "available" => 1
  }
  @station_capacity_fraction_paths [
    ["availability"],
    ["capacity_fraction"],
    ["station_capacity_fraction"],
    ["capacity_pack_capacity_fraction"],
    ["throughput_model", "availability"],
    ["throughput_model", "station_capacity_fraction"],
    ["throughput_model", "capacity_fraction"],
    ["capacity_model", "availability"],
    ["capacity_model", "station_capacity_fraction"],
    ["capacity_model", "capacity_fraction"],
    ["activity_context", "availability"],
    ["activity_context", "station_capacity_fraction"],
    ["activity_context", "capacity_fraction"]
  ]
  @station_capacity_percent_paths [
    ["capacity_percent"],
    ["station_capacity_percent"],
    ["throughput_model", "capacity_percent"],
    ["throughput_model", "station_capacity_percent"],
    ["capacity_model", "capacity_percent"],
    ["capacity_model", "station_capacity_percent"],
    ["activity_context", "capacity_percent"],
    ["activity_context", "station_capacity_percent"]
  ]
  @station_capacity_value_paths for(
                                  path <- @station_capacity_fraction_paths,
                                  do: {:fraction, path}
                                ) ++
                                  for(
                                    path <- @station_capacity_percent_paths,
                                    do: {:percent, path}
                                  )
  @resource_availability_value_aliases %{
    "payload_available" => ["payload_available?"],
    "antenna_available" => ["antenna_available?"],
    "spacecraft_available" => ["spacecraft_available?"]
  }
  @resource_availability_boolean_aliases %{
    "spacecraft_available" => ["spacecraft_availability"]
  }
  @resource_availability_status_aliases %{
    "payload_available" => ["payload_status"],
    "antenna_available" => ["antenna_status"],
    "spacecraft_available" => ["spacecraft_status"]
  }
  @resource_availability_aliases Map.new(@resource_availability_value_aliases, fn {field, aliases} ->
                                   {field,
                                    aliases ++
                                      Map.get(@resource_availability_boolean_aliases, field, []) ++
                                      Map.fetch!(@resource_availability_status_aliases, field)}
                                 end)
  @resource_margin_aliases %{
    "storage_margin" => ["storage_capacity_margin"],
    "downlink_margin" => ["downlink_capacity_margin"],
    "battery_state_of_charge" => ["battery_soc"]
  }
  @resource_power_margin_source_aliases ["battery_state_of_charge", "battery_soc"]
  @resource_availability_true_tokens ~w(true yes y available nominal operational enabled 1)
  @resource_availability_false_tokens ~w(false no n unavailable offline down outage maintenance disabled 0)
  @provider_direction_aliases %{
    "cmd" => "command",
    "commanding" => "command",
    "commands" => "command",
    "sband_command" => "command",
    "s_band_command" => "command",
    "uplink" => "uplink",
    "up" => "uplink",
    "up_link" => "uplink",
    "dl" => "downlink",
    "down" => "downlink",
    "downlinking" => "downlink",
    "downlink" => "downlink",
    "down_link" => "downlink",
    "tracking" => "tracking",
    "track" => "tracking",
    "track_ing" => "tracking",
    "tracking_pass" => "tracking",
    "health" => "health_check",
    "health_check" => "health_check",
    "healthcheck" => "health_check",
    "health_check_window" => "health_check",
    "contact" => "contact"
  }
  @operational_timeline_dependency_integrity_issue_fields ~w(
    missing_dependency_activity_ids
    missing_dependency_timeline_ids
    dependency_cycle_activity_ids
    dependency_cycle_timeline_ids
    dependency_order_violation_activity_ids
    dependency_order_violation_timeline_ids
  )
  @operational_timeline_exclusivity_integrity_issue_fields ~w(
    exclusivity_violation_activity_ids
    exclusivity_violation_timeline_ids
    exclusivity_violation_group
  )
  @operational_timeline_integrity_issue_fields @operational_timeline_dependency_integrity_issue_fields ++
                                                 @operational_timeline_exclusivity_integrity_issue_fields

  def capabilities do
    capabilities(default_metadata())
  end

  def capabilities(metadata) when is_map(metadata) do
    %{
      artifact_contract: "candidate_refresh.v1",
      planner: "OrbitalDynamics.CandidateRefresh.V1",
      model: :accepted_planning_state_to_sampled_windows_v1,
      validation_level: :artifact_contract,
      executable_refresh: %{
        opt_in: true,
        bundle_id: "candidate_refresh.earth_j2_drag_access_eclipse.v1",
        execution_mode: :offline_deterministic,
        input_contract: "accepted_planning_state.v1",
        report_contract: "candidate_refresh_execution.v1",
        candidate_sources: [:ground_station_access],
        archived_event_families: [:eclipse],
        network_access: false
      },
      inputs: [
        :accepted_planning_state,
        :mission_state,
        :remaining_horizon,
        :refreshed_event_results,
        :ground_network,
        :station_calendar,
        :station_calendar_report,
        :station_calendar_precedence_summary,
        :station_calendar_provider,
        :contact_intents,
        :contact_intent_summary,
        :targets,
        :prior_candidate_activities,
        :resource_summaries,
        :resource_projection_report,
        :resource_projection_flow_summary,
        :resource_filter_report,
        :resource_filter_summary,
        :contact_filter_report,
        :link_capacity_summary,
        :relay_data_path_summary,
        :operational_feedback,
        :timeline_feedback_report,
        :operational_timeline_report,
        :timeline_integrity_report,
        :timeline_activity_state,
        :timeline_activity_status_state,
        :timeline_activity_approval_state,
        :timeline_activity_lifecycle_state,
        :timeline_activity_precondition_summary,
        :timeline_preservation_report,
        :timeline_preservation_status,
        :timeline_diff_report,
        :timeline_diff_summary,
        :timeline_lifecycle_state_summary,
        :timeline_dependency_impact_summary,
        :timeline_publication_summary,
        :timeline_transition_application_report,
        :timeline_transition_application_summary,
        :objective_satisfaction_report,
        :objective_tradeoff_report,
        :score_term_report,
        :constraint_report,
        :candidate_diff_report,
        :candidate_rejection_report,
        :freshness_report,
        :refresh_budget_report,
        :schema_validation_report,
        :schema_validation_batch_report,
        :operational_readiness_report,
        :operational_import_eligibility_summary,
        :operational_readiness_gate_summary,
        :operational_execution_boundary_summary,
        :command_window_report,
        :maneuver_review_report,
        :provider_counteroffer_report,
        :provider_counteroffer_review_summary,
        :provider_counteroffer_import_readiness_summary,
        :provider_counteroffer_plan_impact_summary,
        :contact_allocation_report,
        :contact_allocation_summary,
        :contact_allocation_station_pressure_summary,
        :contact_allocation_reservation_conflict_summary,
        :contact_allocation_capacity_pack_summary,
        :contact_allocation_provider_reservation_request_summary,
        :station_reservation_report,
        :station_reservation_review_summary,
        :station_reservation_hold_summary,
        :station_reservation_hold_import_readiness_summary,
        :contact_contention_report,
        :contact_contention_resolution_report,
        :contact_contention_resolution_summary,
        :link_capacity_report,
        :quality_gate_report,
        :operational_quality_gate_summary,
        :operational_quality_gate_unavailable_resource_summary,
        :operational_quality_gate_operator_training_summary,
        :operational_quality_gate_schema_validation_summary,
        :operational_quality_gate_import_readiness_summary,
        :model_acceptance_report,
        :validation_safety_case_summary
      ],
      outputs: [
        :candidate_refresh_execution,
        :refreshed_windows,
        :candidate_activities,
        :contact_intents,
        :candidate_diff_report,
        :candidate_rejection_report,
        :freshness_report,
        :refresh_budget_report,
        :resource_filter_report,
        :contact_filter_report,
        :contact_allocation_report,
        :source_window_lineage
      ],
      public_facades: [
        :candidate_refresh,
        :candidate_refresh_source_report_summary,
        :candidate_refresh_operational_readiness_replay_summary,
        :candidate_refresh_quality_gate_replay_summary,
        :candidate_refresh_model_acceptance_replay_summary,
        :candidate_refresh_validation_safety_case_replay_summary,
        :candidate_refresh_freshness_replay_summary,
        :candidate_refresh_refresh_budget_replay_summary,
        :candidate_refresh_schema_validation_replay_summary,
        :candidate_refresh_candidate_diff_replay_summary,
        :candidate_refresh_candidate_rejection_replay_summary,
        :candidate_refresh_provider_counteroffer_replay_summary,
        :candidate_refresh_contact_contention_replay_summary,
        :candidate_refresh_contact_contention_resolution_replay_summary,
        :candidate_refresh_contact_allocation_replay_summary,
        :candidate_refresh_link_capacity_replay_summary,
        :candidate_refresh_contact_filter_replay_summary,
        :candidate_refresh_resource_filter_replay_summary,
        :candidate_refresh_resource_projection_replay_summary,
        :candidate_refresh_storage_downlink_pressure_replay_summary,
        :candidate_refresh_station_calendar_replay_summary,
        :candidate_refresh_station_reservation_replay_summary,
        :candidate_refresh_command_window_replay_summary,
        :candidate_refresh_maneuver_review_replay_summary,
        :candidate_refresh_contact_intent_replay_summary,
        :candidate_refresh_timeline_activity_state_replay_summary,
        :candidate_refresh_timeline_activity_status_state_replay_summary,
        :candidate_refresh_timeline_activity_approval_state_replay_summary,
        :candidate_refresh_timeline_activity_lifecycle_state_replay_summary,
        :candidate_refresh_timeline_activity_precondition_replay_summary,
        :candidate_refresh_timeline_preservation_replay_summary,
        :candidate_refresh_timeline_integrity_replay_summary,
        :candidate_refresh_timeline_diff_replay_summary,
        :candidate_refresh_timeline_lifecycle_state_replay_summary,
        :candidate_refresh_timeline_dependency_impact_replay_summary,
        :candidate_refresh_timeline_publication_replay_summary,
        :candidate_refresh_timeline_transition_application_replay_summary,
        :candidate_refresh_objective_gap_replay_summary,
        :candidate_refresh_constraint_replay_summary,
        :candidate_refresh_timeline_feedback_replay_summary,
        :candidate_refresh_operational_timeline_replay_summary
      ],
      source_report_helpers: [
        :source_report_summary,
        :candidate_diff_replay_summary,
        :candidate_rejection_replay_summary,
        :provider_counteroffer_replay_summary,
        :contact_contention_replay_summary,
        :contact_contention_resolution_replay_summary,
        :contact_allocation_replay_summary,
        :link_capacity_replay_summary,
        :contact_filter_replay_summary,
        :resource_filter_replay_summary,
        :resource_projection_replay_summary,
        :storage_downlink_pressure_replay_summary,
        :station_calendar_replay_summary,
        :station_reservation_replay_summary,
        :command_window_replay_summary,
        :maneuver_review_replay_summary,
        :contact_intent_replay_summary,
        :timeline_activity_state_replay_summary,
        :timeline_activity_status_state_replay_summary,
        :timeline_activity_approval_state_replay_summary,
        :timeline_activity_lifecycle_state_replay_summary,
        :timeline_activity_precondition_replay_summary,
        :timeline_preservation_replay_summary,
        :timeline_integrity_replay_summary,
        :timeline_diff_replay_summary,
        :timeline_lifecycle_state_replay_summary,
        :timeline_dependency_impact_replay_summary,
        :timeline_publication_replay_summary,
        :timeline_transition_application_replay_summary,
        :objective_gap_replay_summary,
        :constraint_replay_summary,
        :timeline_feedback_replay_summary,
        :operational_timeline_replay_summary,
        :operational_readiness_replay_summary,
        :quality_gate_replay_summary,
        :model_acceptance_replay_summary,
        :validation_safety_case_replay_summary,
        :freshness_replay_summary,
        :refresh_budget_replay_summary,
        :schema_validation_replay_summary
      ],
      source_report_summary_semantics: [
        :source_report_contract_counts,
        :source_report_family_counts,
        :source_report_row_counts,
        :source_report_counts_by_family,
        :source_report_row_counts_by_family,
        :source_report_counts_by_contract,
        :source_report_row_counts_by_contract,
        :source_report_counts_by_trust_boundary_status,
        :source_report_row_counts_by_trust_boundary_status,
        :source_report_paths,
        :source_report_paths_by_family,
        :source_report_paths_by_contract,
        :source_report_paths_by_trust_boundary_status,
        :source_report_trust_boundary_status_counts,
        :source_report_status_count_maps,
        :source_report_readiness_quality_gate_count_maps,
        :source_report_readiness_quality_gate_analysis_mode_count_maps,
        :source_report_adapter_boundary_count_maps,
        :source_report_resource_availability_count_maps,
        :source_report_station_availability_reason_ids,
        :source_report_station_availability_reason_count_maps,
        :source_report_station_pressure_count_maps,
        :source_report_contact_allocation_capacity_pack_routing_maps,
        :source_report_contact_allocation_capacity_pack_demand_maps,
        :source_report_contact_allocation_provider_reservation_request_routing_maps,
        :source_report_contact_allocation_direction_routing_maps,
        :source_report_link_capacity_routing_count_maps,
        :source_report_link_capacity_direction_lists,
        :source_report_link_capacity_direction_routing_maps,
        :source_report_link_capacity_contact_pressure_routing_maps,
        :source_report_link_capacity_source_window_routing_maps,
        :source_report_link_capacity_spacecraft_routing_maps,
        :source_report_link_capacity_station_calendar_routing_maps,
        :source_report_link_capacity_adjusted_throughput_maps,
        :source_report_constraint_routing_count_maps,
        :source_report_constraint_id_routing_maps,
        :source_report_constraint_activity_routing_maps,
        :source_report_resource_projection_routing_count_maps,
        :source_report_resource_projection_direction_lists,
        :source_report_resource_projection_direction_routing_maps,
        :source_report_resource_projection_activity_pressure_routing_maps,
        :source_report_resource_filter_routing_count_maps,
        :source_report_resource_filter_direction_lists,
        :source_report_resource_filter_direction_routing_maps,
        :source_report_resource_filter_suppression_reason_candidate_routing_maps,
        :source_report_resource_filter_blocking_candidate_routing_maps,
        :source_report_contact_contention_routing_count_maps,
        :source_report_contact_contention_capacity_pack_demand_maps,
        :source_report_contact_contention_direction_routing_maps,
        :source_report_contact_contention_resolution_direction_routing_maps,
        :source_report_contact_contention_resolution_required_action_routing_maps,
        :source_report_candidate_diff_routing_count_maps,
        :source_report_candidate_rejection_routing_count_maps,
        :source_report_objective_gap_routing_count_maps,
        :source_report_objective_gap_aggregate_routing_maps,
        :source_report_objective_gap_activity_routing_maps,
        :source_report_contact_intent_station_feedback_count_maps,
        :source_report_contact_intent_capacity_pack_demand_maps,
        :source_report_contact_intent_direction_lists,
        :source_report_contact_intent_direction_routing_maps,
        :source_report_contact_filter_direction_lists,
        :source_report_contact_filter_direction_routing_maps,
        :source_report_contact_filter_station_suppression_count_maps,
        :source_report_station_calendar_affected_contact_count_maps,
        :source_report_station_calendar_provider_contention_count_maps,
        :source_report_station_calendar_direction_routing_maps,
        :source_report_station_reservation_report_count_maps,
        :source_report_station_reservation_direction_routing_maps,
        :source_report_station_reservation_evidence_counts,
        :source_report_station_reservation_hold_summary_maps,
        :source_report_station_reservation_hold_import_readiness_maps,
        :source_report_timeline_diff_routing_count_maps,
        :source_report_timeline_diff_activity_routing_maps,
        :source_report_timeline_activity_state_routing_maps,
        :source_report_timeline_activity_status_state_routing_maps,
        :source_report_timeline_activity_approval_state_routing_maps,
        :source_report_timeline_activity_lifecycle_state_routing_maps,
        :source_report_timeline_activity_precondition_routing_maps,
        :source_report_timeline_integrity_routing_maps,
        :source_report_timeline_lifecycle_state_routing_maps,
        :source_report_timeline_dependency_impact_routing_maps,
        :source_report_timeline_publication_routing_maps,
        :source_report_timeline_transition_application_routing_count_maps,
        :source_report_timeline_transition_application_selected_activity_routing_maps,
        :source_report_command_window_direction_routing_maps,
        :source_report_command_window_feedback_count_maps,
        :source_report_command_window_required_action_routing_maps,
        :source_report_maneuver_review_feedback_count_maps,
        :source_report_maneuver_review_maneuver_routing_maps,
        :source_report_maneuver_review_required_action_routing_maps,
        :source_report_provider_counteroffer_routing_maps,
        :source_report_provider_counteroffer_review_summary_maps,
        :source_report_provider_counteroffer_import_readiness_maps,
        :source_report_freshness_status_count_maps,
        :source_report_refresh_budget_count_maps,
        :source_report_schema_validation_count_maps,
        :source_report_quality_gate_import_readiness_maps,
        :source_report_quality_gate_row_derived_counts,
        :source_report_operational_readiness_branch_replay_summary,
        :source_report_quality_gate_branch_replay_summary,
        :source_report_model_acceptance_branch_replay_summary,
        :source_report_validation_safety_case_branch_replay_summary,
        :source_report_validation_safety_case_row_derived_counts,
        :source_report_freshness_branch_replay_summary,
        :source_report_refresh_budget_branch_replay_summary,
        :source_report_schema_validation_branch_replay_summary,
        :source_report_candidate_diff_branch_replay_summary,
        :source_report_candidate_rejection_branch_replay_summary,
        :source_report_provider_counteroffer_branch_replay_summary,
        :source_report_contact_contention_branch_replay_summary,
        :source_report_contact_contention_resolution_branch_replay_summary,
        :source_report_contact_allocation_branch_replay_summary,
        :source_report_link_capacity_branch_replay_summary,
        :source_report_contact_filter_branch_replay_summary,
        :source_report_resource_filter_branch_replay_summary,
        :source_report_resource_projection_branch_replay_summary,
        :source_report_storage_downlink_pressure_branch_replay_summary,
        :source_report_storage_downlink_pressure_provider_routing_maps,
        :source_report_station_calendar_branch_replay_summary,
        :source_report_station_reservation_branch_replay_summary,
        :source_report_command_window_branch_replay_summary,
        :source_report_maneuver_review_branch_replay_summary,
        :source_report_contact_intent_branch_replay_summary,
        :source_report_timeline_activity_state_branch_replay_summary,
        :source_report_timeline_activity_status_state_branch_replay_summary,
        :source_report_timeline_activity_approval_state_branch_replay_summary,
        :source_report_timeline_activity_lifecycle_state_branch_replay_summary,
        :source_report_timeline_activity_precondition_branch_replay_summary,
        :source_report_timeline_preservation_branch_replay_summary,
        :source_report_timeline_integrity_branch_replay_summary,
        :source_report_timeline_diff_branch_replay_summary,
        :source_report_timeline_dependency_impact_branch_replay_summary,
        :source_report_timeline_publication_branch_replay_summary,
        :source_report_timeline_transition_application_branch_replay_summary,
        :source_report_objective_gap_branch_replay_summary,
        :source_report_constraint_branch_replay_summary,
        :source_report_timeline_feedback_activity_routing_maps,
        :source_report_timeline_feedback_import_status_routing_maps,
        :source_report_timeline_feedback_branch_replay_summary,
        :source_report_operational_timeline_activity_routing_maps,
        :source_report_operational_timeline_row_routing_maps,
        :source_report_operational_timeline_branch_replay_summary,
        :source_report_timeline_lifecycle_state_branch_replay_summary,
        :source_report_operational_readiness_routing_maps,
        :source_report_model_acceptance_routing_maps,
        :source_report_validation_safety_case_routing_maps
      ],
      resource_availability_aliases: metadata_value(metadata, :resource_availability_aliases),
      resource_margin_aliases: metadata_value(metadata, :resource_margin_aliases),
      resource_power_margin_source_aliases:
        metadata_value(metadata, :resource_power_margin_source_aliases),
      resource_availability_true_tokens:
        metadata_value(metadata, :resource_availability_true_tokens),
      resource_availability_false_tokens:
        metadata_value(metadata, :resource_availability_false_tokens),
      provider_direction_aliases: metadata_value(metadata, :provider_direction_aliases),
      station_unavailable_aliases: metadata_value(metadata, :station_unavailable_aliases),
      station_unavailable_tokens: metadata_value(metadata, :station_unavailable_tokens),
      station_availability_precedence: metadata_value(metadata, :station_availability_precedence),
      station_capacity_fraction_paths: metadata_value(metadata, :station_capacity_fraction_paths),
      station_capacity_percent_paths: metadata_value(metadata, :station_capacity_percent_paths),
      station_capacity_value_paths:
        capacity_value_path_metadata(metadata_value(metadata, :station_capacity_value_paths)),
      prior_candidate_optional_stable_identity_fields:
        metadata_value(metadata, :prior_candidate_optional_stable_identity_fields),
      station_calendar_id_list_fields: metadata_value(metadata, :station_calendar_id_list_fields),
      station_calendar_number_list_fields:
        metadata_value(metadata, :station_calendar_number_list_fields),
      event_timing_keys: metadata_value(metadata, :event_timing_keys),
      operational_timeline_integrity_issue_fields:
        metadata_value(metadata, :operational_timeline_integrity_issue_fields),
      operational_timeline_dependency_integrity_issue_fields:
        metadata_value(metadata, :operational_timeline_dependency_integrity_issue_fields),
      operational_timeline_exclusivity_integrity_issue_fields:
        metadata_value(metadata, :operational_timeline_exclusivity_integrity_issue_fields),
      freshness_model: :accepted_snapshot_horizon_and_quality_freshness,
      candidate_diff_model: :candidate_id_set_diff_with_semantic_change_reasons,
      row_semantics: [
        :canonical_event_order_identity_generation,
        :event_timing_metadata_keys,
        :prior_candidate_optional_stable_identity_fields,
        :direction_scoped_station_calendar,
        :station_calendar_id_list_fields,
        :station_calendar_reservation_expiration_context,
        :provider_direction_aliases,
        :station_calendar_entry_identity_preservation,
        :station_reservation_identity_match,
        :station_reservation_owner_match,
        :station_reservation_match_status_counts,
        :operational_feedback_unit_interval_input_validation,
        :operational_feedback_invalid_entry_review,
        :station_capacity_value_paths,
        :source_operational_timeline_report_activity_feedback,
        :source_operational_timeline_report_integrity_provenance,
        :operational_timeline_integrity_issue_fields,
        :source_timeline_feedback_report_feedback,
        :source_timeline_diff_removed_downlink_feedback,
        :source_timeline_diff_removed_observation_objectives,
        :source_timeline_diff_changed_downlink_shortfall_feedback,
        :source_timeline_diff_changed_contact_success_feedback,
        :source_timeline_diff_changed_observation_objectives,
        :source_timeline_diff_changed_observation_quality_feedback,
        :source_timeline_diff_changed_command_success_feedback,
        :source_timeline_diff_changed_maneuver_success_feedback,
        :source_timeline_transition_application_replay,
        :source_timeline_diff_review_import_replay,
        :source_realized_activity_feedback_replay,
        :source_realized_feedback_review_import_replay,
        :source_command_window_report_command_success_feedback,
        :source_maneuver_review_report_maneuver_feedback,
        :source_timeline_feedback_report_input_provenance,
        :source_operational_timeline_report_input_provenance,
        :source_timeline_integrity_report_input_provenance,
        :source_timeline_activity_state_input_provenance,
        :source_timeline_activity_lifecycle_state_input_provenance,
        :source_timeline_preservation_input_provenance,
        :source_timeline_diff_report_input_provenance,
        :source_timeline_diff_summary_input_provenance,
        :source_timeline_lifecycle_state_summary_input_provenance,
        :source_timeline_dependency_impact_summary_input_provenance,
        :source_timeline_transition_application_report_input_provenance,
        :source_timeline_transition_application_summary_input_provenance,
        :source_command_window_report_input_provenance,
        :source_maneuver_review_report_input_provenance,
        :source_objective_satisfaction_report_objectives,
        :source_objective_tradeoff_report_objectives,
        :source_score_term_report_objectives,
        :source_constraint_report_downlink_objectives,
        :source_resource_projection_report_downlink_objectives,
        :source_contact_contention_resolution_report_downlink_objectives,
        :source_contact_allocation_report_downlink_objectives,
        :source_link_capacity_report_downlink_objectives,
        :source_link_capacity_report_station_throughput_feedback,
        :source_station_calendar_report_station_feedback,
        :source_contact_intent_station_feedback,
        :source_contact_intent_input_provenance,
        :source_contact_intent_summary_input_provenance,
        :source_contact_filter_report_station_feedback,
        :source_contact_allocation_report_station_feedback,
        :source_contact_allocation_unavailable_resource_contact_filtering,
        :contact_allocation_policy_handoff,
        :contact_allocation_reduced_capacity_policy_handoff,
        :source_resource_projection_report_resource_feedback,
        :source_resource_filter_report_resource_feedback,
        :resource_margin_aliases,
        :resource_power_margin_source_aliases,
        :resource_availability_aliases,
        :source_candidate_diff_report_input_provenance,
        :source_candidate_rejection_report_input_provenance,
        :source_quality_gate_unavailable_resource_contact_filtering,
        :source_operational_readiness_unavailable_resource_contact_filtering,
        :source_provider_counteroffer_report_input_provenance,
        :source_provider_counteroffer_review_summary_input_provenance,
        :source_provider_counteroffer_import_readiness_summary_input_provenance,
        :source_provider_counteroffer_plan_impact_summary_input_provenance,
        :source_freshness_report_input_provenance,
        :source_refresh_budget_report_input_provenance,
        :source_operational_readiness_report_input_provenance,
        :source_operational_import_eligibility_summary_input_provenance,
        :source_operational_readiness_gate_summary_input_provenance,
        :source_operational_execution_boundary_summary_input_provenance,
        :source_quality_gate_report_input_provenance,
        :source_operational_quality_gate_summary_input_provenance,
        :source_operational_quality_gate_unavailable_resource_summary_input_provenance,
        :source_operational_quality_gate_operator_training_summary_input_provenance,
        :source_operational_quality_gate_schema_validation_summary_input_provenance,
        :source_operational_quality_gate_import_readiness_summary_input_provenance,
        :source_model_acceptance_report_input_provenance,
        :source_validation_safety_case_summary_input_provenance,
        :source_operational_readiness_review_import_replay,
        :source_timeline_dependency_impact_review_import_replay,
        :source_schema_validation_report_input_provenance,
        :source_schema_validation_batch_report_input_provenance,
        :source_station_calendar_report_input_provenance,
        :source_station_calendar_precedence_summary_input_provenance,
        :source_constraint_report_input_provenance,
        :source_objective_satisfaction_report_input_provenance,
        :source_objective_tradeoff_report_input_provenance,
        :source_score_term_report_input_provenance,
        :source_resource_projection_report_input_provenance,
        :source_resource_projection_flow_summary_input_provenance,
        :source_resource_filter_report_input_provenance,
        :source_resource_filter_summary_input_provenance,
        :source_contact_filter_report_input_provenance,
        :source_link_capacity_report_input_provenance,
        :source_link_capacity_summary_input_provenance,
        :source_relay_data_path_summary_input_provenance,
        :source_contact_allocation_report_input_provenance,
        :source_contact_allocation_summary_input_provenance,
        :source_contact_allocation_station_pressure_summary_input_provenance,
        :source_contact_allocation_reservation_conflict_summary_input_provenance,
        :source_contact_allocation_capacity_pack_summary_input_provenance,
        :source_contact_allocation_provider_reservation_request_summary_input_provenance,
        :source_station_reservation_review_summary_input_provenance,
        :source_station_reservation_hold_summary_input_provenance,
        :source_station_reservation_hold_import_readiness_summary_input_provenance,
        :source_contact_contention_report_input_provenance,
        :source_contact_contention_resolution_report_input_provenance,
        :source_contact_contention_resolution_summary_input_provenance,
        :source_report_summary,
        :source_report_summary_routing_maps,
        :mission_state_target_resource_and_ground_network_fallbacks,
        :mission_state_spacecraft_identity_precedence,
        :accepted_planning_state_spacecraft_state_fallback,
        :accepted_planning_state_target_fallback,
        :accepted_planning_state_ground_network_fallback,
        :accepted_planning_state_resource_summary_fallback,
        :mission_state_current_epoch_fallback,
        :accepted_planning_state_current_epoch_fallback,
        :mission_state_remaining_horizon_fallback,
        :accepted_planning_state_remaining_horizon_fallback,
        :mission_state_station_calendar_fallback,
        :mission_state_station_calendar_provider_list_fallback,
        :accepted_planning_state_station_calendar_fallback,
        :accepted_planning_state_station_calendar_provider_list_fallback,
        :station_calendar_provider_precedence,
        :run_input_source_provenance
      ],
      known_limits: ModelLimits.atoms()
    }
  end

  defp default_metadata do
    %{
      resource_availability_aliases: @resource_availability_aliases,
      resource_margin_aliases: @resource_margin_aliases,
      resource_power_margin_source_aliases: @resource_power_margin_source_aliases,
      resource_availability_true_tokens: @resource_availability_true_tokens,
      resource_availability_false_tokens: @resource_availability_false_tokens,
      provider_direction_aliases: @provider_direction_aliases,
      station_unavailable_aliases: @unavailable_availability_aliases,
      station_unavailable_tokens: @unavailable_station_tokens,
      station_availability_precedence: @station_availability_precedence,
      station_capacity_fraction_paths: @station_capacity_fraction_paths,
      station_capacity_percent_paths: @station_capacity_percent_paths,
      station_capacity_value_paths: @station_capacity_value_paths,
      prior_candidate_optional_stable_identity_fields:
        CandidateDiffReport.prior_candidate_optional_stable_identity_fields(),
      station_calendar_id_list_fields: CandidateDiffReport.station_calendar_id_list_fields(),
      station_calendar_number_list_fields:
        CandidateDiffReport.station_calendar_number_list_fields(),
      event_timing_keys: CandidateActivityFields.event_timing_keys(),
      operational_timeline_integrity_issue_fields: @operational_timeline_integrity_issue_fields,
      operational_timeline_dependency_integrity_issue_fields:
        @operational_timeline_dependency_integrity_issue_fields,
      operational_timeline_exclusivity_integrity_issue_fields:
        @operational_timeline_exclusivity_integrity_issue_fields
    }
  end

  defp metadata_value(metadata, key), do: Map.fetch!(metadata, key)

  defp capacity_value_path_metadata(paths) do
    Enum.map(paths, fn {unit, path} -> %{unit: unit, path: path} end)
  end
end
