defmodule OrbitalDynamics.Schema.ActivityContextJsonSchema do
  @moduledoc false

  def schema(opts) do
    stable_id_pattern = Keyword.fetch!(opts, :stable_id_pattern)
    stable_id_array_schema = Keyword.fetch!(opts, :stable_id_array_schema)
    string_array_schema = Keyword.fetch!(opts, :string_array_schema)
    number_array_schema = Keyword.fetch!(opts, :number_array_schema)
    numeric_map_schema = Keyword.fetch!(opts, :numeric_map_schema)
    provenance_schema = Keyword.fetch!(opts, :provenance_schema)
    timeline_identity_schema = Keyword.fetch!(opts, :timeline_identity_schema)

    candidate_activity_source_window_schema =
      Keyword.fetch!(opts, :candidate_activity_source_window_schema)

    actual_data_rate_throughput_derivation_schema =
      Keyword.fetch!(opts, :actual_data_rate_throughput_derivation_schema)

    execution_uncertainty_schema = Keyword.fetch!(opts, :execution_uncertainty_schema)
    numeric_triplet_schema = Keyword.fetch!(opts, :numeric_triplet_schema)
    probability_schema = Keyword.fetch!(opts, :probability_schema)

    %{
      "type" => "object",
      "additionalProperties" => true,
      "properties" => %{
        "activity_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "planned_activity_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "matched_planned_activity_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "timeline_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "scenario_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "spacecraft_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "ground_station_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "target_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "target_ids" => stable_id_array_schema,
        "objective_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "objective_ids" => stable_id_array_schema,
        "objective_type" => %{"type" => "string"},
        "source_target_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "source_target" => %{"type" => "object", "additionalProperties" => true},
        "target_latitude_deg" => %{"type" => "number"},
        "target_longitude_deg" => %{"type" => "number"},
        "target_minimum_elevation_deg" => %{"type" => "number"},
        "target_priority" => %{"type" => "number"},
        "target_priority_source" => %{"type" => "string"},
        "target_priority_objective_ids" => stable_id_array_schema,
        "target_priority_objective_type" => %{"type" => "string"},
        "observation_objective_ids" => stable_id_array_schema,
        "observation_objective_count" => %{"type" => "integer", "minimum" => 0},
        "observation_objective_source" => %{"type" => "string"},
        "observation_objective_types" => string_array_schema,
        "collection_latency_objective_ids" => stable_id_array_schema,
        "collection_latency_objective_count" => %{"type" => "integer", "minimum" => 0},
        "collection_latency_objective_source" => %{"type" => "string"},
        "collection_latency_objective_types" => string_array_schema,
        "source_window_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "source_event_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "source_branch_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "source_timeline_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "source_event_type" => %{"type" => "string"},
        "source_event_provenance" => provenance_schema,
        "activity_type" => %{"type" => "string"},
        "type" => %{"type" => "string"},
        "source_window_type" => %{"type" => "string"},
        "direction" => %{"type" => "string"},
        "status" => %{"type" => "string"},
        "approval_status" => %{"type" => "string"},
        "allow_overlap" => %{"type" => "boolean"},
        "feedback_source" => %{"type" => "string"},
        "feedback_scope" => %{"type" => "string"},
        "trust_boundary" => %{"type" => "string"},
        "derivation_reason" => %{"type" => "string"},
        "derivation_reasons" => string_array_schema,
        "feedback_status" => %{"type" => "string"},
        "realized_status" => %{"type" => "string"},
        "timeline_identity" => timeline_identity_schema,
        "resource_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "collection_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "collection_ids" => stable_id_array_schema,
        "product_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "product_ids" => stable_id_array_schema,
        "payload_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "payload_ids" => stable_id_array_schema,
        "instrument_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "instrument_ids" => stable_id_array_schema,
        "starts_at_s" => %{"type" => "number"},
        "ends_at_s" => %{"type" => "number"},
        "duration_s" => %{"type" => "number"},
        "setup_duration_s" => %{"type" => "number", "minimum" => 0.0},
        "cooldown_duration_s" => %{"type" => "number", "minimum" => 0.0},
        "telemetry_confirmation_required" => %{"type" => "boolean"},
        "telemetry_confirmation_status" => %{"type" => "string"},
        "actual_starts_at_s" => %{"type" => "number"},
        "actual_ends_at_s" => %{"type" => "number"},
        "score" => %{"type" => "number"},
        "score_terms" => numeric_map_schema,
        "source_window" => candidate_activity_source_window_schema,
        "feasibility_status" => %{"type" => "string"},
        "repair_reason" => %{"type" => "string"},
        "changed_fields" => string_array_schema,
        "candidate_diff_changed_fields" => string_array_schema,
        "candidate_diff_changed_field_count" => %{"type" => "integer", "minimum" => 0},
        "estimated_throughput_mb" => %{"type" => "number"},
        "planned_estimated_throughput_mb" => %{"type" => "number"},
        "required_downlink_mb" => %{"type" => "number"},
        "required_volume_mb" => %{"type" => "number"},
        "required_data_volume_mb" => %{"type" => "number"},
        "target_downlink_mb" => %{"type" => "number"},
        "target_volume_mb" => %{"type" => "number"},
        "target_data_volume_mb" => %{"type" => "number"},
        "min_downlink_mb" => %{"type" => "number"},
        "candidate_downlink_mb" => %{"type" => "number"},
        "planned_data_volume_mb" => %{"type" => "number"},
        "planned_volume_mb" => %{"type" => "number"},
        "selected_downlink_mb" => %{"type" => "number"},
        "selected_data_volume_mb" => %{"type" => "number"},
        "selected_volume_mb" => %{"type" => "number"},
        "actual_data_volume_mb" => %{"type" => "number"},
        "actual_volume_mb" => %{"type" => "number"},
        "delivered_data_volume_mb" => %{"type" => "number"},
        "received_data_volume_mb" => %{"type" => "number"},
        "selected_downlink_shortfall_mb" => %{"type" => "number"},
        "selected_data_volume_shortfall_mb" => %{"type" => "number"},
        "data_volume_shortfall_mb" => %{"type" => "number"},
        "actual_data_volume_shortfall_mb" => %{"type" => "number"},
        "missing_data_volume_mb" => %{"type" => "number"},
        "required_data_volume_gap_mb" => %{"type" => "number"},
        "actual_throughput_mb" => %{"type" => "number"},
        "actual_data_rate_throughput_derivation" => actual_data_rate_throughput_derivation_schema,
        "throughput_completion_fraction" => %{
          "type" => "number",
          "minimum" => 0.0,
          "maximum" => 1.0
        },
        "completed_fraction" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "contact_success" => %{"type" => "boolean"},
        "contact_result" => %{"type" => "string"},
        "contact_success_factor" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "contact_success_factor_source" => %{"type" => "string"},
        "command_success" => %{"type" => "boolean"},
        "command_result" => %{"type" => "string"},
        "command_success_factor" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "command_success_factor_source" => %{"type" => "string"},
        "command_authority_status" => %{"type" => "string"},
        "required_authority" => %{"type" => "string"},
        "command_safety_status" => %{"type" => "string"},
        "command_authorized" => %{"type" => "boolean"},
        "command_safety_checked" => %{"type" => "boolean"},
        "observation_success" => %{"type" => "boolean"},
        "observation_result" => %{"type" => "string"},
        "observation_success_factor" => %{
          "type" => "number",
          "minimum" => 0.0,
          "maximum" => 1.0
        },
        "observation_success_factor_source" => %{"type" => "string"},
        "maneuver_success" => %{"type" => "boolean"},
        "maneuver_result" => %{"type" => "string"},
        "maneuver_success_factor" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "maneuver_success_factor_source" => %{"type" => "string"},
        "feedback_weight" => %{"type" => "number"},
        "feedback_weight_source" => %{"type" => "string"},
        "execution_uncertainty" => execution_uncertainty_schema,
        "execution_uncertainty_status" => %{"type" => "string"},
        "execution_uncertainty_source" => %{"type" => "string"},
        "delta_v_km_s" => numeric_triplet_schema,
        "delta_v_3sigma_km_s" => numeric_triplet_schema,
        "delta_v_magnitude_km_s" => %{"type" => "number"},
        "delta_v_3sigma_magnitude_km_s" => %{"type" => "number"},
        "timing_3sigma_s" => %{"type" => "number"},
        "link_protocol" => %{"type" => "string"},
        "frequency_band" => %{"type" => "string"},
        "modulation" => %{"type" => "string"},
        "coding_scheme" => %{"type" => "string"},
        "polarization" => %{"type" => "string"},
        "data_rate_mbps" => %{"type" => "number"},
        "link_margin_db" => %{"type" => "number"},
        "snr_db" => %{"type" => "number"},
        "eb_no_db" => %{"type" => "number"},
        "bit_error_rate" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "packet_loss_rate" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "frame_loss_rate" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "carrier_lock" => %{"type" => "boolean"},
        "symbol_lock" => %{"type" => "boolean"},
        "link_quality_status" => %{"type" => "string"},
        "eclipse_overlap_fraction" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "eclipse_overlap_s" => %{"type" => "number"},
        "lighting_condition" => %{"type" => "string"},
        "lighting_condition_detail" => %{"type" => "string"},
        "lighting_condition_model" => %{"type" => "string"},
        "lighting_detail_model" => %{"type" => "string"},
        "lighting_confidence" => %{"type" => ["number", "string"]},
        "image_quality_score" => probability_schema,
        "image_quality_status" => %{"type" => "string"},
        "image_quality_source" => %{"type" => "string"},
        "cloud_cover_fraction" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "blur_score" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "pointing_mode" => %{"type" => "string"},
        "pointing_target_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "boresight_axis" => %{"type" => "string"},
        "off_nadir_angle_deg" => %{"type" => "number"},
        "slew_angle_deg" => %{"type" => "number"},
        "pointing_error_deg" => %{"type" => "number"},
        "pointing_status" => %{"type" => "string"},
        "pointing_model" => %{"type" => "string"},
        "pointing_source" => %{"type" => "string"},
        "pointing_confidence" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "attitude_mode" => %{"type" => "string"},
        "attitude_target_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "roll_deg" => %{"type" => "number"},
        "pitch_deg" => %{"type" => "number"},
        "yaw_deg" => %{"type" => "number"},
        "attitude_error_deg" => %{"type" => "number"},
        "attitude_status" => %{"type" => "string"},
        "attitude_model" => %{"type" => "string"},
        "attitude_source" => %{"type" => "string"},
        "attitude_confidence" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "thermal_zone_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "temperature_c" => %{"type" => "number"},
        "planned_temperature_c" => %{"type" => "number"},
        "actual_temperature_c" => %{"type" => "number"},
        "temperature_delta_c" => %{"type" => "number"},
        "min_operating_temperature_c" => %{"type" => "number"},
        "max_operating_temperature_c" => %{"type" => "number"},
        "thermal_margin_c" => %{"type" => "number"},
        "thermal_status" => %{"type" => "string"},
        "thermal_model" => %{"type" => "string"},
        "thermal_source" => %{"type" => "string"},
        "thermal_confidence" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "fuel_margin" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "power_margin" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "storage_margin" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "downlink_margin" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "battery_capacity_wh" => %{"type" => "number"},
        "battery_energy_used_wh" => %{"type" => "number"},
        "battery_energy_generated_wh" => %{"type" => "number", "minimum" => 0.0},
        "battery_state_of_charge" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "spacecraft_available" => %{"type" => "boolean"},
        "payload_available" => %{"type" => "boolean"},
        "antenna_available" => %{"type" => "boolean"},
        "degraded" => %{"type" => "boolean"},
        "mode" => %{"type" => "string"},
        "incompatible_activity_types" => string_array_schema,
        "suppressed_activity_types" => string_array_schema,
        "station_availability" => %{"type" => "string"},
        "capacity_pack_capacity_fraction" => %{
          "type" => "number",
          "minimum" => 0.0,
          "maximum" => 1.0
        },
        "station_contention_status" => %{"type" => "string"},
        "station_calendar_entry_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "station_calendar_provider_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "station_calendar_provider_entry_id" => %{
          "type" => "string",
          "pattern" => stable_id_pattern
        },
        "station_calendar_directions" => string_array_schema,
        "station_calendar_status" => %{"type" => "string"},
        "station_calendar_overlap_count" => %{"type" => "integer", "minimum" => 0},
        "station_calendar_overlap_entry_ids" => stable_id_array_schema,
        "station_calendar_overlap_availabilities" => string_array_schema,
        "station_calendar_entry_ambiguous" => %{"type" => "boolean"},
        "station_calendar_ambiguous_entry_count" => %{"type" => "integer", "minimum" => 0},
        "station_calendar_ambiguous_entry_ids" => stable_id_array_schema,
        "station_calendar_reservation_overlap_count" => %{"type" => "integer", "minimum" => 0},
        "station_calendar_reservation_ids" => stable_id_array_schema,
        "station_calendar_reserved_by" => string_array_schema,
        "station_calendar_reservation_statuses" => string_array_schema,
        "station_calendar_reservation_expires_at_s" => number_array_schema,
        "station_calendar_trust_boundary_status" => %{"type" => "string"},
        "station_reservation_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "station_reservation_expires_at_s" => %{"type" => "number"},
        "station_reserved_by" => %{"type" => "string"},
        "station_reservation_status" => %{"type" => "string"},
        "station_reservation_match_status" => %{"type" => "string"},
        "source_station_calendar_entry" => %{
          "type" => "object",
          "additionalProperties" => true
        },
        "source_station_calendar_overlaps" => %{
          "type" => "array",
          "items" => %{"type" => "object", "additionalProperties" => true}
        },
        "dependency_activity_ids" => stable_id_array_schema,
        "dependency_timeline_ids" => stable_id_array_schema,
        "exclusive_with_activity_ids" => stable_id_array_schema,
        "exclusive_with_timeline_ids" => stable_id_array_schema,
        "timeline_integrity_status" => %{"type" => "string"},
        "timeline_integrity_issue_count" => %{"type" => "integer", "minimum" => 0},
        "timeline_integrity_issue_types" => string_array_schema,
        "timeline_integrity_issues" => %{
          "type" => "array",
          "items" => %{"type" => "object", "additionalProperties" => true}
        },
        "missing_dependency_activity_ids" => stable_id_array_schema,
        "missing_dependency_timeline_ids" => stable_id_array_schema,
        "self_dependency_activity_ids" => stable_id_array_schema,
        "self_dependency_timeline_ids" => stable_id_array_schema,
        "duplicate_dependency_activity_ids" => stable_id_array_schema,
        "duplicate_dependency_timeline_ids" => stable_id_array_schema,
        "duplicate_exclusivity_activity_ids" => stable_id_array_schema,
        "duplicate_exclusivity_timeline_ids" => stable_id_array_schema,
        "dependency_cycle_activity_ids" => stable_id_array_schema,
        "dependency_cycle_timeline_ids" => stable_id_array_schema,
        "dependency_order_violation_activity_ids" => stable_id_array_schema,
        "dependency_order_violation_timeline_ids" => stable_id_array_schema,
        "exclusivity_violation_activity_ids" => stable_id_array_schema,
        "exclusivity_violation_timeline_ids" => stable_id_array_schema,
        "exclusivity_violation_group" => %{"type" => "string"}
      }
    }
  end
end
