defmodule OrbitalDynamics.Schema.CadenceImportRowHandoffCallbacks do
  @moduledoc false

  def build(local) when is_list(local) do
    [
      validate_approval_requirement_handoff_matches_source:
        &OrbitalDynamics.Schema.PolicyPlanHandoffContracts.validate_approval_requirement_matches_source/3,
      validate_cadence_source_review_approval_requirement_handoff_matches:
        &OrbitalDynamics.Schema.PolicyPlanHandoffContracts.validate_cadence_source_review_approval_requirement_matches/3,
      validate_cadence_source_review_battery_handoff_matches:
        &OrbitalDynamics.Schema.ResourceProjectionHandoffContracts.validate_cadence_source_review_battery_handoff_matches/3,
      validate_cadence_source_review_candidate_diff_handoff_matches:
        &OrbitalDynamics.Schema.CandidateHandoffContracts.validate_cadence_source_review_candidate_diff_matches/3,
      validate_cadence_source_review_candidate_rejection_handoff_matches:
        &OrbitalDynamics.Schema.CandidateHandoffContracts.validate_cadence_source_review_candidate_rejection_matches/3,
      validate_cadence_source_review_command_window_handoff_matches:
        &OrbitalDynamics.Schema.CommandWindowManeuverHandoffContracts.validate_cadence_source_review_command_window_matches/3,
      validate_cadence_source_review_constraint_handoff_matches:
        &OrbitalDynamics.Schema.OptimizationHandoffContracts.validate_cadence_source_review_constraint_matches/3,
      validate_cadence_source_review_contact_allocation_capacity_pack_handoff_matches:
        &OrbitalDynamics.Schema.ContactAllocationHandoffContracts.validate_cadence_source_review_capacity_pack_matches/3,
      validate_cadence_source_review_contact_allocation_handoff_matches:
        &OrbitalDynamics.Schema.ContactAllocationHandoffContracts.validate_cadence_source_review_allocation_matches/3,
      validate_cadence_source_review_contact_contention_handoff_matches:
        &OrbitalDynamics.Schema.ContactContentionHandoffContracts.validate_cadence_source_review_matches/3,
      validate_cadence_source_review_contact_intent_handoff_matches:
        &OrbitalDynamics.Schema.ContactReviewHandoffContracts.validate_cadence_source_review_contact_intent_matches/3,
      validate_cadence_source_review_execution_handoff_matches:
        &OrbitalDynamics.Schema.SourceReviewHandoffContracts.validate_execution_matches/3,
      validate_cadence_source_review_freshness_handoff_matches:
        &OrbitalDynamics.Schema.SourceReviewHandoffContracts.validate_freshness_matches/3,
      validate_cadence_source_review_link_capacity_handoff_matches:
        &OrbitalDynamics.Schema.LinkCapacityHandoffContracts.validate_cadence_source_review_matches/3,
      validate_cadence_source_review_maneuver_review_handoff_matches:
        &OrbitalDynamics.Schema.CommandWindowManeuverHandoffContracts.validate_cadence_source_review_maneuver_review_matches/3,
      validate_cadence_source_review_objective_satisfaction_handoff_matches:
        &OrbitalDynamics.Schema.OptimizationHandoffContracts.validate_cadence_source_review_objective_satisfaction_matches/3,
      validate_cadence_source_review_objective_tradeoff_handoff_matches:
        &OrbitalDynamics.Schema.OptimizationHandoffContracts.validate_cadence_source_review_objective_tradeoff_matches/3,
      validate_cadence_source_review_operational_readiness_handoff_matches:
        &OrbitalDynamics.Schema.SourceReviewHandoffContracts.validate_operational_readiness_matches/3,
      validate_cadence_source_review_operational_timeline_handoff_matches:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_cadence_source_review_operational_timeline_matches/3,
      validate_cadence_source_review_pareto_frontier_handoff_matches:
        &OrbitalDynamics.Schema.StrategyHandoffContracts.validate_cadence_source_review_pareto_frontier_matches/3,
      validate_cadence_source_review_plan_delta_handoff_matches:
        &OrbitalDynamics.Schema.PolicyPlanHandoffContracts.validate_cadence_source_review_plan_delta_matches/3,
      validate_cadence_source_review_policy_escalation_handoff_matches:
        &OrbitalDynamics.Schema.SourceReviewHandoffContracts.validate_policy_escalation_matches/3,
      validate_cadence_source_review_provider_calendar_contention_handoff_matches:
        &OrbitalDynamics.Schema.ContactAllocationHandoffContracts.validate_cadence_source_review_provider_calendar_contention_matches/3,
      validate_cadence_source_review_provider_counteroffer_handoff_matches:
        &OrbitalDynamics.Schema.ContactReviewHandoffContracts.validate_cadence_source_review_provider_counteroffer_matches/3,
      validate_cadence_source_review_quality_gate_handoff_matches:
        &OrbitalDynamics.Schema.SourceReviewHandoffContracts.validate_quality_gate_matches/3,
      validate_cadence_source_review_ranking_comparison_handoff_matches:
        &OrbitalDynamics.Schema.StrategyHandoffContracts.validate_cadence_source_review_ranking_comparison_matches/3,
      validate_cadence_source_review_realized_feedback_handoff_matches:
        &OrbitalDynamics.Schema.RiskFeedbackHandoffContracts.validate_cadence_source_review_realized_feedback_matches/3,
      validate_cadence_source_review_refresh_budget_handoff_matches:
        &OrbitalDynamics.Schema.SourceReviewHandoffContracts.validate_refresh_budget_matches/3,
      validate_cadence_source_review_resource_projection_context_handoff_matches:
        &OrbitalDynamics.Schema.ResourceProjectionHandoffContracts.validate_cadence_source_review_context_handoff_matches/3,
      validate_cadence_source_review_resource_projection_count_handoff_matches:
        &OrbitalDynamics.Schema.ResourceProjectionHandoffContracts.validate_cadence_source_review_count_handoff_matches/3,
      validate_cadence_source_review_risk_explanation_handoff_matches:
        &OrbitalDynamics.Schema.RiskFeedbackHandoffContracts.validate_cadence_source_review_risk_explanation_matches/3,
      validate_cadence_source_review_schema_validation_handoff_matches:
        &OrbitalDynamics.Schema.SourceReviewHandoffContracts.validate_schema_validation_matches/3,
      validate_cadence_source_review_score_term_handoff_matches:
        &OrbitalDynamics.Schema.OptimizationHandoffContracts.validate_cadence_source_review_score_term_matches/3,
      validate_cadence_source_review_station_calendar_handoff_matches:
        &OrbitalDynamics.Schema.StationCalendarHandoffContracts.validate_cadence_source_review_matches/3,
      validate_cadence_source_review_strategy_recommendation_handoff_matches:
        &OrbitalDynamics.Schema.StrategyHandoffContracts.validate_cadence_source_review_strategy_recommendation_matches/3,
      validate_cadence_source_review_strategy_tradeoff_handoff_matches:
        &OrbitalDynamics.Schema.StrategyHandoffContracts.validate_cadence_source_review_strategy_tradeoff_matches/3,
      validate_cadence_source_review_suppression_duplicate_matches:
        &OrbitalDynamics.Schema.SuppressionHandoffContracts.validate_cadence_source_review_matches/3,
      validate_cadence_source_review_timeline_activity_precondition_handoff_matches:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_cadence_source_review_timeline_activity_precondition_matches/3,
      validate_cadence_source_review_timeline_dependency_impact_handoff_matches:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_cadence_source_review_timeline_dependency_impact_matches/3,
      validate_cadence_source_review_timeline_diff_handoff_matches:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_cadence_source_review_timeline_diff_matches/3,
      validate_cadence_source_review_timeline_lifecycle_state_handoff_matches:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_cadence_source_review_timeline_lifecycle_state_matches/3,
      validate_cadence_source_review_timeline_preservation_handoff_matches:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_cadence_source_review_timeline_preservation_matches/3,
      validate_cadence_source_review_timeline_protection_handoff_matches:
        &OrbitalDynamics.Schema.SourceReviewHandoffContracts.validate_timeline_protection_matches/3,
      validate_cadence_source_review_timeline_publication_handoff_matches:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_cadence_source_review_timeline_publication_matches/3,
      validate_cadence_source_review_timeline_transition_application_handoff_matches:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_cadence_source_review_timeline_transition_application_matches/3,
      validate_cadence_source_review_warning_handoff_matches:
        &OrbitalDynamics.Schema.SourceReviewHandoffContracts.validate_warning_matches/3,
      validate_candidate_diff_handoff_matches_source:
        &OrbitalDynamics.Schema.CandidateHandoffContracts.validate_candidate_diff_matches_source/3,
      validate_candidate_rejection_handoff_matches_source:
        &OrbitalDynamics.Schema.CandidateHandoffContracts.validate_candidate_rejection_matches_source/3,
      validate_command_window_handoff_matches_source:
        &OrbitalDynamics.Schema.CommandWindowManeuverHandoffContracts.validate_command_window_matches_source/3,
      validate_constraint_handoff_matches_source:
        &OrbitalDynamics.Schema.OptimizationHandoffContracts.validate_constraint_matches_source/3,
      validate_contact_allocation_handoff_fields:
        fetch!(local, :validate_contact_allocation_handoff_fields),
      validate_contact_allocation_handoff_matches_source:
        &OrbitalDynamics.Schema.ContactAllocationHandoffContracts.validate_allocation_matches_source/3,
      validate_contact_contention_handoff_matches_source:
        &OrbitalDynamics.Schema.ContactContentionHandoffContracts.validate_matches_source/3,
      validate_contact_intent_handoff_matches_source:
        &OrbitalDynamics.Schema.ContactReviewHandoffContracts.validate_contact_intent_matches_source/3,
      validate_link_capacity_handoff_count_lists:
        &OrbitalDynamics.Schema.LinkCapacityHandoffContracts.validate_count_lists/3,
      validate_link_capacity_handoff_matches_source:
        &OrbitalDynamics.Schema.LinkCapacityHandoffContracts.validate_matches_source/3,
      validate_maneuver_review_handoff_matches_source:
        &OrbitalDynamics.Schema.CommandWindowManeuverHandoffContracts.validate_maneuver_review_matches_source/3,
      validate_objective_satisfaction_handoff_matches_source:
        &OrbitalDynamics.Schema.OptimizationHandoffContracts.validate_objective_satisfaction_matches_source/3,
      validate_objective_tradeoff_handoff_matches_source:
        &OrbitalDynamics.Schema.OptimizationHandoffContracts.validate_objective_tradeoff_matches_source/3,
      validate_operational_timeline_handoff_matches_source:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_operational_timeline_matches_source/3,
      validate_operator_review_row_links: fetch!(local, :validate_operator_review_row_links),
      validate_optional_timeline_activity_precondition_summary_source:
        fetch!(local, :validate_optional_timeline_activity_precondition_summary_source),
      validate_optional_timeline_activity_state_source:
        fetch!(local, :validate_optional_timeline_activity_state_source),
      validate_optional_timeline_dependency_impact_source_row:
        fetch!(local, :validate_optional_timeline_dependency_impact_source_row),
      validate_optional_timeline_diff_summary_source:
        fetch!(local, :validate_optional_timeline_diff_summary_source),
      validate_optional_timeline_integrity_source_row:
        fetch!(local, :validate_optional_timeline_integrity_source_row),
      validate_optional_timeline_lifecycle_state_source_row:
        fetch!(local, :validate_optional_timeline_lifecycle_state_source_row),
      validate_optional_timeline_preservation_source_row:
        fetch!(local, :validate_optional_timeline_preservation_source_row),
      validate_optional_timeline_protection_summary:
        fetch!(local, :validate_optional_timeline_protection_summary),
      validate_optional_timeline_publication_summary_source:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_optional_timeline_publication_summary_source/3,
      validate_optional_timeline_transition_application_row:
        fetch!(local, :validate_optional_timeline_transition_application_row),
      validate_optional_timeline_transition_application_summary_source:
        fetch!(local, :validate_optional_timeline_transition_application_summary_source),
      validate_pareto_frontier_handoff_matches_source:
        &OrbitalDynamics.Schema.StrategyHandoffContracts.validate_pareto_frontier_matches_source/3,
      validate_plan_delta_handoff_matches_source:
        &OrbitalDynamics.Schema.PolicyPlanHandoffContracts.validate_plan_delta_matches_source/3,
      validate_provider_calendar_contention_handoff_matches_source:
        &OrbitalDynamics.Schema.ContactAllocationHandoffContracts.validate_provider_calendar_contention_matches_source/3,
      validate_provider_counteroffer_handoff_matches_source:
        &OrbitalDynamics.Schema.ContactReviewHandoffContracts.validate_provider_counteroffer_matches_source/3,
      validate_ranking_comparison_handoff_matches_source:
        &OrbitalDynamics.Schema.StrategyHandoffContracts.validate_ranking_comparison_matches_source/3,
      validate_realized_feedback_handoff_matches_source:
        &OrbitalDynamics.Schema.RiskFeedbackHandoffContracts.validate_realized_feedback_matches_source/3,
      validate_resource_projection_battery_handoff_fields:
        &OrbitalDynamics.Schema.ResourceProjectionHandoffContracts.validate_battery_handoff_fields/3,
      validate_resource_projection_battery_handoff_matches_source:
        &OrbitalDynamics.Schema.ResourceProjectionHandoffContracts.validate_battery_handoff_matches_source/3,
      validate_resource_projection_count_handoff_matches_source:
        &OrbitalDynamics.Schema.ResourceProjectionHandoffContracts.validate_count_handoff_matches_source/3,
      validate_resource_projection_flow_summary_context_matches_source:
        &OrbitalDynamics.Schema.ResourceProjectionHandoffContracts.validate_flow_summary_context_matches_source/3,
      validate_resource_projection_remaining_handoff_fields:
        &OrbitalDynamics.Schema.ResourceProjectionHandoffContracts.validate_remaining_handoff_fields/3,
      validate_risk_explanation_handoff_matches_source:
        &OrbitalDynamics.Schema.RiskFeedbackHandoffContracts.validate_risk_explanation_matches_source/3,
      validate_score_term_handoff_matches_source:
        &OrbitalDynamics.Schema.OptimizationHandoffContracts.validate_score_term_matches_source/3,
      validate_selected_timeline_integrity_fields:
        fetch!(local, :validate_selected_timeline_integrity_fields),
      validate_source_operational_readiness_gate_handoff_matches:
        &OrbitalDynamics.Schema.OperationalReadinessHandoffContracts.validate_gate_matches_source/3,
      validate_source_quality_gate_row_handoff_matches:
        &OrbitalDynamics.Schema.QualityGateHandoffContracts.validate_row_matches_source/3,
      validate_station_calendar_handoff_matches_source:
        &OrbitalDynamics.Schema.StationCalendarHandoffContracts.validate_matches_source/3,
      validate_strategy_branch_comparison_handoff_matches_source:
        &OrbitalDynamics.Schema.StrategyHandoffContracts.validate_branch_comparison_matches_source/3,
      validate_strategy_recommendation_handoff_matches_source:
        &OrbitalDynamics.Schema.StrategyHandoffContracts.validate_strategy_recommendation_matches_source/3,
      validate_strategy_tradeoff_handoff_matches_source:
        &OrbitalDynamics.Schema.StrategyHandoffContracts.validate_strategy_tradeoff_matches_source/3,
      validate_suppression_handoff_matches_source:
        &OrbitalDynamics.Schema.SuppressionHandoffContracts.validate_matches_source/3,
      validate_timeline_diff_handoff_matches_source:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_timeline_diff_matches_source/3,
      validate_timeline_publication_handoff_matches_source:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_timeline_publication_matches_source_summary/3,
      validate_timeline_transition_application_handoff_matches_source:
        &OrbitalDynamics.Schema.TimelineHandoffContracts.validate_timeline_transition_application_matches_source/3
    ]
  end

  defp fetch!(local, name), do: Keyword.fetch!(local, name)
end
