defmodule OrbitalDynamics.Schema.CampaignRegistryContracts do
  @moduledoc false

  def contracts do
    %{
      "campaign_plan.v1" => %{
        "schema_contract" => "campaign_plan.v1",
        "artifact_family" => "campaign_plan",
        "schema_version" => 1,
        "required_fields" => [
          "schema_version",
          "generated_at",
          "planner",
          "plan_id",
          "study_id",
          "planning_horizon",
          "activities",
          "proposed_contacts",
          "contact_intents",
          "candidate_activities",
          "ranked_timelines",
          "warnings",
          "assumptions",
          "provenance",
          "ranking_explanation"
        ],
        "optional_fields" => [
          "optimizer_contract",
          "score_term_report",
          "objective_tradeoff_report",
          "constraint_report",
          "contact_allocation_report",
          "cadence_import_manifest",
          "command_window_report",
          "link_capacity_report",
          "contact_filter_report",
          "station_calendar_report",
          "target_commitments",
          "contact_contention_report",
          "contact_contention_resolution_report",
          "resource_filter_report",
          "resource_projection_report",
          "resource_projection_flow_summary",
          "timeline_activity_precondition_summaries",
          "timeline_integrity_report",
          "objective_satisfaction_report",
          "operational_timeline_report",
          "operator_review_package",
          "operational_readiness_report",
          "quality_gate_report"
        ],
        "nested_contracts" => [
          "planned_activity.v1",
          "proposed_contact.v1",
          "optimizer_contract.v1",
          "score_term_report.v1",
          "objective_tradeoff_report.v1",
          "constraint_report.v1",
          "contact_allocation_report.v1",
          "cadence_import_manifest.v1",
          "command_window_report.v1",
          "link_capacity_report.v1",
          "contact_filter_report.v1",
          "station_calendar_report.v1",
          "contact_contention_report.v1",
          "contact_contention_resolution_report.v1",
          "resource_filter_report.v1",
          "resource_projection_report.v1",
          "resource_projection_flow_summary.v1",
          "timeline_activity_precondition_summary.v1",
          "timeline_integrity_report.v1",
          "objective_satisfaction_report.v1",
          "operational_timeline_report.v1",
          "operator_review_package.v1",
          "operational_readiness_report.v1",
          "quality_gate_report.v1"
        ]
      },
      "campaign_repair.v2" => %{
        "schema_contract" => "campaign_repair.v2",
        "artifact_family" => "campaign_repair",
        "schema_version" => 2,
        "required_fields" => [
          "schema_version",
          "generated_at",
          "planner",
          "source_plan_id",
          "current_epoch_s",
          "remaining_horizon",
          "activities",
          "source_candidate_activities",
          "deltas",
          "approval_requirements",
          "approval_status",
          "approval_policy",
          "policy_decision",
          "warnings",
          "realized_state_snapshot",
          "repair_policy",
          "scoring_policy",
          "score",
          "score_terms",
          "assumptions",
          "provenance",
          "repair_metadata"
        ],
        "optional_fields" => [
          "study_id",
          "source_planner",
          "change_summary",
          "preserved_activities",
          "approval_rule_matches",
          "operational_timeline_report",
          "timeline_transition_application_report",
          "command_window_report",
          "operator_review_package",
          "cadence_import_manifest",
          "source_operational_readiness_report",
          "source_quality_gate_report",
          "source_contact_intents",
          "source_resource_summaries",
          "source_candidate_diff_report",
          "source_freshness_report",
          "source_refresh_budget_report",
          "source_contact_allocation_report",
          "source_contact_contention_report",
          "source_contact_contention_resolution_report",
          "source_link_capacity_report",
          "source_station_reservation_report",
          "source_station_calendar_report",
          "source_contact_filter_report",
          "source_resource_filter_report",
          "source_resource_projection_report",
          "source_timeline_feedback_report",
          "objective_tradeoff_report",
          "constraint_report",
          "contact_allocation_report",
          "score_term_report",
          "link_capacity_report",
          "source_candidate_rejection_report"
        ],
        "nested_contracts" => [
          "planned_activity.v1",
          "plan_delta.v1",
          "approval_requirement.v1",
          "operational_timeline_report.v1",
          "timeline_transition_application_report.v1",
          "command_window_report.v1",
          "operator_review_package.v1",
          "cadence_import_manifest.v1",
          "operational_readiness_report.v1",
          "quality_gate_report.v1",
          "contact_intent.v1",
          "resource_summary.v1",
          "candidate_diff_report.v1",
          "freshness_report.v1",
          "refresh_budget_report.v1",
          "station_calendar_report.v1",
          "station_reservation_report.v1",
          "contact_filter_report.v1",
          "resource_filter_report.v1",
          "resource_projection_report.v1",
          "timeline_feedback_report.v1",
          "objective_tradeoff_report.v1",
          "constraint_report.v1",
          "contact_allocation_report.v1",
          "contact_contention_report.v1",
          "contact_contention_resolution_report.v1",
          "score_term_report.v1",
          "link_capacity_report.v1",
          "candidate_rejection_report.v1"
        ]
      },
      "campaign_strategy.v3" => %{
        "schema_contract" => "campaign_strategy.v3",
        "artifact_family" => "campaign_strategy",
        "schema_version" => 3,
        "required_fields" => [
          "schema_version",
          "generated_at",
          "planner",
          "source_plan_id",
          "mission_state_snapshot",
          "branches",
          "recommendation",
          "strategy_policy",
          "approval_policy",
          "operational_feedback",
          "assumptions",
          "provenance",
          "strategy_metadata"
        ],
        "optional_fields" => [
          "branch_comparison_report",
          "ranking_comparison_report",
          "operator_review_package",
          "source_repair_id",
          "score_term_report",
          "objective_tradeoff_report",
          "pareto_frontier_report",
          "operational_feedback_provenance",
          "cadence_import_manifest"
        ],
        "nested_contracts" => [
          "strategy_branch.v1",
          "strategy_recommendation.v1",
          "branch_comparison_report.v1",
          "ranking_comparison_report.v1",
          "score_term_report.v1",
          "objective_tradeoff_report.v1",
          "pareto_frontier_report.v1",
          "approval_requirement.v1",
          "operator_review_package.v1",
          "cadence_import_manifest.v1"
        ]
      },
      "strategy_branch.v1" => %{
        "schema_contract" => "strategy_branch.v1",
        "artifact_family" => "strategy_branch",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "branch_id",
          "probability",
          "events",
          "candidate_plan",
          "repair_result",
          "score",
          "score_terms",
          "warnings",
          "risk_indicators",
          "approval_status",
          "approval_requirements",
          "policy_decision"
        ],
        "optional_fields" => [
          "label",
          "derived_source",
          "resource_impacts",
          "tradeoffs",
          "resource_projection_report"
        ],
        "nested_contracts" => ["policy_decision.v1", "approval_requirement.v1"]
      }
    }
  end
end
