defmodule OrbitalDynamics.Schema.ContactAllocationSummaryRegistryContracts do
  @moduledoc false

  def contracts do
    %{
      "contact_allocation_summary.v1" => %{
        "schema_contract" => "contact_allocation_summary.v1",
        "artifact_family" => "contact_allocation_summary",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "source_artifact_type",
          "input_contact_count",
          "allocated_contact_count",
          "returned_allocated_contact_count",
          "policy_blocked_allocated_contact_count",
          "deferred_contact_count",
          "blocked_contact_count",
          "invalid_contact_input_count",
          "status_blocked_contact_count",
          "resource_blocked_contact_count",
          "duplicate_contact_id_count",
          "reduced_capacity_pack_group_count",
          "reduced_capacity_pack_status_counts",
          "allocation_status_counts",
          "effective_allocation_status_counts",
          "allocation_reason_counts",
          "contact_ids_by_allocation_reason",
          "capacity_pack_status_counts",
          "capacity_pack_required_capacity_fraction",
          "capacity_pack_selected_required_capacity_fraction",
          "capacity_pack_deferred_required_capacity_fraction",
          "capacity_pack_required_capacity_fraction_by_status",
          "required_capacity_fraction_source_counts",
          "station_reservation_match_status_counts",
          "station_reservation_status_counts",
          "station_reserved_by_counts",
          "station_reservation_ids",
          "station_reservation_expires_at_s",
          "station_reservation_expiration_status_counts",
          "station_reservation_active_contact_count",
          "station_reservation_expired_contact_count",
          "station_reservation_missing_expiration_contact_count",
          "station_reservation_declared_expiration_contact_count",
          "station_calendar_trust_boundary_status_counts",
          "calendar_entry_trust_boundary_status_counts",
          "resource_blocking_dimension_counts",
          "allocated_contact_ids",
          "allocated_contact_ids_by_ground_station_id",
          "returned_allocated_contact_ids",
          "returned_allocated_contact_ids_by_ground_station_id",
          "deferred_contact_ids",
          "deferred_contact_ids_by_ground_station_id",
          "blocked_contact_ids",
          "blocked_contact_ids_by_ground_station_id",
          "policy_blocked_contact_ids",
          "policy_blocked_contact_ids_by_ground_station_id",
          "invalid_contact_input_ids",
          "status_blocked_contact_ids",
          "resource_blocked_contact_ids",
          "resource_blocked_contact_ids_by_blocking_dimension",
          "resource_blocked_contact_ids_by_spacecraft_id",
          "station_pressure_contact_ids_by_ground_station_id",
          "station_pressure_contact_counts_by_ground_station_id",
          "station_pressure_contact_ids_by_availability",
          "station_pressure_contact_counts_by_availability",
          "station_pressure_contact_ids_by_precedence_availability",
          "station_pressure_contact_counts_by_precedence_availability",
          "station_pressure_contact_ids_by_precedence_rank",
          "station_pressure_contact_counts_by_precedence_rank",
          "station_reservation_contact_ids_by_match_status",
          "station_reservation_contact_ids_by_status",
          "station_reservation_contact_ids_by_reserved_by",
          "station_reservation_ids_by_match_status",
          "station_reservation_ids_by_status",
          "station_reservation_ids_by_reserved_by",
          "station_reservation_contact_ids_by_expiration_status",
          "station_reservation_ids_by_expiration_status",
          "capacity_pack_contact_ids_by_status",
          "capacity_pack_contact_ids_by_ground_station_id",
          "capacity_pack_selected_contact_ids_by_ground_station_id",
          "capacity_pack_deferred_contact_ids_by_ground_station_id",
          "capacity_pack_required_capacity_fraction_by_ground_station_id",
          "capacity_pack_selected_required_capacity_fraction_by_ground_station_id",
          "capacity_pack_deferred_required_capacity_fraction_by_ground_station_id",
          "required_capacity_fraction_contact_ids_by_source",
          "reduced_capacity_packed_contact_ids",
          "reduced_capacity_deferred_contact_ids",
          "rows",
          "review_contact_ids",
          "review_row_count",
          "review_rows",
          "reduced_capacity_pack_groups",
          "assumptions"
        ],
        "optional_fields" => [
          "source",
          "station_reservation_expiration_now_s",
          "earliest_station_reservation_expires_at_s",
          "station_pressure_contact_ids_by_status",
          "station_pressure_contact_counts_by_status",
          "station_pressure_contact_ids_by_direction_and_ground_station_id",
          "model_limits"
        ],
        "nested_contracts" => ["contact_allocation_report.v1"]
      }
    }
  end
end
