defmodule OrbitalDynamics.Schema.LinkCapacityRegistryContracts do
  @moduledoc false

  def contracts do
    %{
      "link_capacity_report.v1" => %{
        "schema_contract" => "link_capacity_report.v1",
        "artifact_family" => "link_capacity_report",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "source",
          "contact_count",
          "selected_contact_count",
          "estimated_throughput_mb",
          "selected_estimated_throughput_mb",
          "rows",
          "assumptions"
        ],
        "optional_fields" => [
          "model_limits",
          "capacity_adjusted_throughput_mb",
          "selected_capacity_adjusted_throughput_mb",
          "unused_capacity_adjusted_throughput_mb",
          "selected_capacity_utilization_fraction",
          "selection_utilization_status",
          "effective_contact_count",
          "ignored_contact_count",
          "ignored_contact_ids",
          "ignored_contact_reason_counts",
          "ignored_selected_contact_count",
          "ignored_selected_contact_ids",
          "ignored_selected_contact_reason_counts",
          "ambiguous_selected_contact_id_count",
          "ambiguous_selected_contact_ids",
          "duplicate_contact_candidate_count",
          "duplicate_contact_id_count",
          "unmatched_selected_contact_count",
          "unmatched_selected_contact_ids",
          "required_downlink_mb",
          "required_downlink_contact_count",
          "required_downlink_contact_ids",
          "selected_downlink_shortfall_mb",
          "downlink_requirement_status",
          "actual_throughput_mb",
          "actual_throughput_contact_count",
          "actual_throughput_contact_ids",
          "actual_completion_contact_count",
          "actual_completion_contact_ids",
          "unmatched_actual_throughput_contact_count",
          "unmatched_actual_throughput_contact_ids",
          "ambiguous_actual_throughput_contact_count",
          "ambiguous_actual_throughput_contact_ids",
          "unmatched_actual_completion_contact_count",
          "unmatched_actual_completion_contact_ids",
          "ambiguous_actual_completion_contact_count",
          "ambiguous_actual_completion_contact_ids",
          "actual_downlink_completion_ratio",
          "actual_data_rate_throughput_derivations",
          "downlink_completion_sources",
          "invalid_contact_input_count",
          "invalid_contact_input_ids",
          "invalid_contact_inputs",
          "invalid_selected_contact_input_count",
          "invalid_selected_contact_input_ids",
          "invalid_selected_contact_inputs",
          "station_reservation_ids",
          "station_reservation_expires_at_s",
          "station_reserved_bys",
          "station_reservation_statuses",
          "invalid_policy_required_downlink_station_count",
          "invalid_policy_required_downlink_station_ids",
          "station_reservation_match_status_counts",
          "downlink_link_budget_count",
          "downlink_link_budget_ids",
          "downlink_link_budgets"
        ],
        "nested_contracts" => []
      },
      "link_capacity_summary.v1" => %{
        "schema_contract" => "link_capacity_summary.v1",
        "artifact_family" => "link_capacity_summary",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "source_artifact_type",
          "source",
          "station_count",
          "contact_count",
          "effective_contact_count",
          "ignored_contact_count",
          "selected_contact_count",
          "ignored_selected_contact_count",
          "required_downlink_contact_count",
          "actual_throughput_contact_count",
          "actual_completion_contact_count",
          "unmatched_actual_throughput_contact_count",
          "ambiguous_actual_throughput_contact_count",
          "unmatched_actual_completion_contact_count",
          "ambiguous_actual_completion_contact_count",
          "invalid_contact_input_count",
          "invalid_selected_contact_input_count",
          "invalid_policy_required_downlink_station_count",
          "selected_downlink_shortfall_mb",
          "actual_downlink_shortfall_mb",
          "capacity_adjusted_throughput_mb",
          "selected_capacity_adjusted_throughput_mb",
          "unused_capacity_adjusted_throughput_mb",
          "ignored_contact_reason_counts",
          "ignored_selected_contact_reason_counts",
          "station_reservation_match_status_counts",
          "station_reservation_ids",
          "station_reservation_expires_at_s",
          "station_reserved_bys",
          "station_reservation_statuses",
          "contact_ids",
          "selected_contact_ids",
          "ignored_contact_ids",
          "ignored_selected_contact_ids",
          "required_downlink_contact_ids",
          "actual_throughput_contact_ids",
          "actual_completion_contact_ids",
          "unmatched_actual_throughput_contact_ids",
          "ambiguous_actual_throughput_contact_ids",
          "unmatched_actual_completion_contact_ids",
          "ambiguous_actual_completion_contact_ids",
          "ambiguous_selected_contact_ids",
          "unmatched_selected_contact_ids",
          "invalid_contact_input_ids",
          "invalid_selected_contact_input_ids",
          "invalid_policy_required_downlink_station_ids",
          "ground_station_ids",
          "shortfall_ground_station_ids",
          "actual_shortfall_ground_station_ids",
          "selected_downlink_shortfall_mb_by_ground_station_id",
          "actual_downlink_shortfall_mb_by_ground_station_id",
          "ground_station_ids_by_station_availability",
          "ground_station_ids_by_reservation_match_status",
          "ground_station_ids_by_reservation_status",
          "ground_station_ids_by_reserved_by",
          "station_calendar_entry_ids_by_ground_station_id",
          "station_calendar_provider_ids_by_ground_station_id",
          "station_calendar_provider_entry_ids_by_ground_station_id",
          "station_reservation_ids_by_ground_station_id",
          "ignored_contact_ids_by_ground_station_id",
          "selected_contact_ids_by_ground_station_id",
          "capacity_adjusted_throughput_mb_by_ground_station_id",
          "selected_capacity_adjusted_throughput_mb_by_ground_station_id",
          "unused_capacity_adjusted_throughput_mb_by_ground_station_id",
          "required_downlink_contact_ids_by_ground_station_id",
          "actual_throughput_contact_ids_by_ground_station_id",
          "actual_completion_contact_ids_by_ground_station_id",
          "unmatched_actual_throughput_contact_ids_by_ground_station_id",
          "ambiguous_actual_throughput_contact_ids_by_ground_station_id",
          "unmatched_actual_completion_contact_ids_by_ground_station_id",
          "ambiguous_actual_completion_contact_ids_by_ground_station_id",
          "assumptions"
        ],
        "optional_fields" => [
          "model_limits",
          "downlink_requirement_status",
          "actual_downlink_requirement_status",
          "selection_utilization_status",
          "station_calendar_entry_ids",
          "station_calendar_provider_ids",
          "station_calendar_provider_entry_ids"
        ],
        "nested_contracts" => ["link_capacity_report.v1"]
      }
    }
  end
end
