defmodule OrbitalDynamics.Schema.OperationalQualityGateRegistryContracts do
  @moduledoc false

  def contracts do
    %{
      "operational_quality_gate_summary.v1" => %{
        "schema_contract" => "operational_quality_gate_summary.v1",
        "artifact_family" => "operational_quality_gate_summary",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "source",
          "source_artifact_type",
          "source_artifact_id",
          "source_quality_gate_report_id",
          "source_readiness_report_id",
          "readiness_level",
          "import_classification",
          "status",
          "handoff_only",
          "execution_allowed",
          "cadence_write_allowed",
          "operator_authority_granted",
          "execution_boundary",
          "gate_count",
          "passed_gate_count",
          "review_gate_count",
          "analysis_gate_count",
          "blocked_gate_count",
          "non_passed_gate_count",
          "gate_status_counts",
          "gate_classification_counts",
          "gate_ids_by_status",
          "gate_ids_by_classification",
          "quality_gate_row_ids_by_status",
          "quality_gate_row_ids_by_classification",
          "passed_gate_ids",
          "review_required_gate_ids",
          "analysis_only_gate_ids",
          "blocked_gate_ids",
          "non_passed_gate_ids",
          "non_passed_quality_gate_row_ids",
          "non_passed_rows",
          "rows",
          "assumptions",
          "model_limits"
        ],
        "optional_fields" => [],
        "nested_contracts" => ["quality_gate_report.v1"]
      },
      "operational_quality_gate_unavailable_resource_summary.v1" => %{
        "schema_contract" => "operational_quality_gate_unavailable_resource_summary.v1",
        "artifact_family" => "operational_quality_gate_unavailable_resource_summary",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "source",
          "source_artifact_type",
          "source_artifact_id",
          "source_quality_gate_report_id",
          "source_readiness_report_id",
          "resource_availability_row_count",
          "unavailable_resource_row_count",
          "unavailable_resource_pressure_count",
          "unavailable_resource_reason_counts",
          "unavailable_resource_reason_ids",
          "resource_blocking_dimension_counts",
          "blocked_contact_ids_by_blocking_dimension",
          "blocked_contact_ids_by_spacecraft_id",
          "blocked_contact_ids_by_status",
          "quality_gate_row_ids_by_status",
          "quality_gate_ids_by_status",
          "review_required_quality_gate_row_ids",
          "blocked_quality_gate_row_ids",
          "resource_availability_gate_ids",
          "assumptions",
          "model_limits"
        ],
        "optional_fields" => [
          "station_availability_reason_counts",
          "station_availability_reason_ids"
        ],
        "nested_contracts" => ["quality_gate_report.v1"]
      },
      "operational_quality_gate_operator_training_summary.v1" => %{
        "schema_contract" => "operational_quality_gate_operator_training_summary.v1",
        "artifact_family" => "operational_quality_gate_operator_training_summary",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "source",
          "source_artifact_type",
          "source_artifact_id",
          "source_quality_gate_report_id",
          "source_readiness_report_id",
          "operator_training_row_count",
          "operator_training_requirement_count",
          "operator_training_requirement_counts",
          "operator_training_requirement_ids",
          "required_operator_roles",
          "required_training_ids",
          "required_certification_ids",
          "required_qualification_ids",
          "quality_gate_row_ids_by_status",
          "quality_gate_row_ids_by_classification",
          "quality_gate_ids_by_status",
          "quality_gate_ids_by_classification",
          "review_required_quality_gate_row_ids",
          "blocked_quality_gate_row_ids",
          "review_only_quality_gate_row_ids",
          "operator_training_gate_ids",
          "operator_training_review_required",
          "assumptions",
          "model_limits"
        ],
        "optional_fields" => [],
        "nested_contracts" => ["quality_gate_report.v1"]
      },
      "operational_quality_gate_schema_validation_summary.v1" => %{
        "schema_contract" => "operational_quality_gate_schema_validation_summary.v1",
        "artifact_family" => "operational_quality_gate_schema_validation_summary",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "source",
          "source_artifact_type",
          "source_artifact_id",
          "source_quality_gate_report_id",
          "source_readiness_report_id",
          "schema_validation_row_count",
          "schema_validation_pass_count",
          "schema_validation_fail_count",
          "schema_validation_error_count",
          "schema_validation_warning_count",
          "schema_validation_remediation_count",
          "schema_validation_status_counts",
          "schema_validation_status_ids",
          "schema_validation_import_blocked",
          "quality_gate_row_ids_by_status",
          "quality_gate_ids_by_status",
          "blocked_quality_gate_row_ids",
          "review_required_quality_gate_row_ids",
          "failed_schema_validation_quality_gate_row_ids",
          "schema_validation_gate_ids",
          "assumptions",
          "model_limits"
        ],
        "optional_fields" => [],
        "nested_contracts" => ["quality_gate_report.v1"]
      },
      "operational_quality_gate_import_readiness_summary.v1" => %{
        "schema_contract" => "operational_quality_gate_import_readiness_summary.v1",
        "artifact_family" => "operational_quality_gate_import_readiness_summary",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "source",
          "source_artifact_type",
          "source_artifact_id",
          "source_quality_gate_report_id",
          "source_readiness_report_id",
          "import_readiness_row_count",
          "ready_for_import_count",
          "manifest_review_required_count",
          "blocked_import_count",
          "missing_import_count",
          "invalid_cadence_import_count",
          "current_freshness_count",
          "stale_freshness_count",
          "unknown_freshness_count",
          "freshness_status_counts",
          "freshness_status_ids",
          "import_status_counts",
          "import_status_ids",
          "cadence_import_status_counts",
          "cadence_import_status_ids",
          "freshness_review_required",
          "import_preparation_required",
          "import_blocked",
          "quality_gate_row_ids_by_status",
          "quality_gate_ids_by_status",
          "review_required_quality_gate_row_ids",
          "blocked_quality_gate_row_ids",
          "ready_quality_gate_row_ids",
          "stale_or_unknown_freshness_quality_gate_row_ids",
          "import_preparation_quality_gate_row_ids",
          "blocked_import_quality_gate_row_ids",
          "import_readiness_gate_ids",
          "assumptions",
          "model_limits"
        ],
        "optional_fields" => [
          "analysis_only_quality_gate_row_ids",
          "publication_status_counts",
          "downstream_invalidation_status_counts",
          "downstream_invalidation_reason_counts",
          "dependency_impact_status_counts",
          "publication_authority_counts",
          "source_artifact_type_counts",
          "publication_ids",
          "source_artifact_ids",
          "supersedes_artifact_ids",
          "downstream_product_ids",
          "invalidated_downstream_product_ids",
          "invalidated_downstream_product_ids_by_reason",
          "dependency_impact_row_count",
          "impacted_dependency_activity_ids",
          "impacted_dependency_timeline_ids",
          "impacted_exclusive_with_activity_ids",
          "impacted_exclusive_with_timeline_ids",
          "timeline_diff_row_count",
          "timeline_diff_changed_count",
          "timeline_diff_review_required_count",
          "changed_field_counts",
          "changed_timeline_ids",
          "review_timeline_ids",
          "timeline_ids_by_changed_field"
        ],
        "nested_contracts" => ["quality_gate_report.v1"]
      }
    }
  end
end
