defmodule OrbitalDynamics.Schema.ResourceProjectionRegistryContracts do
  @moduledoc false

  def contracts do
    %{
      "resource_projection_report.v1" => %{
        "schema_contract" => "resource_projection_report.v1",
        "artifact_family" => "resource_projection_report",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "input_resource_summary_count",
          "activity_count",
          "projected_resources",
          "assumptions"
        ],
        "optional_fields" => [
          "source",
          "model_limits",
          "valid_resource_summary_count",
          "invalid_resource_summary_input_count",
          "invalid_resource_summary_input_ids",
          "valid_activity_count",
          "invalid_activity_input_count",
          "invalid_activity_input_ids",
          "invalid_activity_inputs",
          "resource_pressure_count",
          "resource_pressure_types",
          "resource_pressure_spacecraft_ids",
          "resource_pressure_spacecraft_ids_by_type",
          "resource_pressure_activity_ids_by_type",
          "resource_source_quality_counts",
          "resource_spacecraft_ids_by_source_quality",
          "resource_trust_boundary_status_counts",
          "resource_spacecraft_ids_by_trust_boundary_status",
          "warnings"
        ],
        "nested_contracts" => []
      },
      "resource_projection_flow_summary.v1" => %{
        "schema_contract" => "resource_projection_flow_summary.v1",
        "artifact_family" => "resource_projection_flow_summary",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "schema_version",
          "model",
          "activity_count",
          "valid_activity_count",
          "invalid_activity_input_count",
          "invalid_activity_input_ids",
          "input_resource_summary_count",
          "valid_resource_summary_count",
          "invalid_resource_summary_input_count",
          "invalid_resource_summary_input_ids",
          "projected_resource_count",
          "flow_row_count",
          "resource_flow_status",
          "resource_pressure_status",
          "resource_pressure_count",
          "resource_pressure_types",
          "resource_pressure_spacecraft_ids",
          "resource_pressure_spacecraft_ids_by_type",
          "resource_pressure_activity_ids_by_type",
          "total_storage_produced_mb",
          "total_planned_downlink_mb",
          "total_storage_limited_downlinked_mb",
          "total_unused_downlink_capacity_mb",
          "total_storage_overflow_mb",
          "total_downlink_shortfall_mb",
          "actual_data_volume_evidence_count",
          "total_actual_data_volume_mb",
          "total_data_volume_delta_mb",
          "actual_data_volume_under_delivered_activity_ids",
          "actual_data_volume_over_delivered_activity_ids",
          "actual_data_volume_exact_activity_ids",
          "total_battery_energy_consumed_wh",
          "total_battery_energy_generated_wh",
          "net_battery_energy_delta_wh",
          "peak_battery_overuse_wh",
          "projected_resources",
          "activity_resource_flow",
          "model_limits",
          "assumptions"
        ],
        "optional_fields" => [
          "source",
          "total_projected_storage_remaining_mb",
          "minimum_projected_storage_remaining_mb",
          "total_projected_downlink_remaining_mb",
          "minimum_projected_downlink_remaining_mb",
          "latency_status",
          "latency_evidence_count",
          "latency_review_count",
          "latency_review_activity_ids",
          "ignored_activity_count",
          "ignored_activity_reason_counts",
          "ignored_activity_ids",
          "ignored_activity_ids_by_reason",
          "resource_pressure_ground_station_ids_by_type",
          "resource_pressure_source_window_ids_by_type",
          "resource_pressure_station_calendar_entry_ids_by_type",
          "resource_pressure_station_calendar_provider_ids_by_type",
          "resource_pressure_station_calendar_provider_entry_ids_by_type",
          "resource_pressure_station_calendar_directions_by_type",
          "resource_pressure_capacity_fractions_by_type",
          "max_planned_latency_s",
          "max_actual_latency_s"
        ],
        "nested_contracts" => ["resource_projection_report.v1"]
      }
    }
  end
end
