defmodule OrbitalDynamics.Schema.TimelineFeedbackRowJsonSchema do
  @moduledoc false

  def row(opts) do
    stable_id_pattern = Keyword.fetch!(opts, :stable_id_pattern)
    capability = Keyword.fetch!(opts, :capability)
    stable_id_array_schema = Keyword.fetch!(opts, :stable_id_array_schema)
    string_array_schema = Keyword.fetch!(opts, :string_array_schema)
    number_array_schema = Keyword.fetch!(opts, :number_array_schema)
    probability_schema = Keyword.fetch!(opts, :probability_schema)
    number_or_string_schema = Keyword.fetch!(opts, :number_or_string_schema)
    protection_decision_schema = Keyword.fetch!(opts, :protection_decision_schema)
    lifecycle_transition_schema = Keyword.fetch!(opts, :lifecycle_transition_schema)

    actual_data_rate_throughput_derivation_schema =
      Keyword.fetch!(opts, :actual_data_rate_throughput_derivation_schema)

    numeric_triplet_schema = Keyword.fetch!(opts, :numeric_triplet_schema)
    timeline_identity_schema = Keyword.fetch!(opts, :timeline_identity_schema)
    activity_context_schema = Keyword.fetch!(opts, :activity_context_schema)
    planned_activity_schema = Keyword.fetch!(opts, :planned_activity_schema)
    realized_activity_schema = Keyword.fetch!(opts, :realized_activity_schema)

    %{
      "type" => "object",
      "additionalProperties" => true,
      "required" => ["activity_id", "status"],
      "properties" => %{
        "activity_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "status" => %{
          "type" => "string",
          "enum" => capability.report_statuses
        },
        "match_strategy" => %{
          "type" => "string",
          "enum" => capability.match_strategies
        },
        "feedback_kind" => %{
          "type" => "string",
          "enum" => capability.feedback_kinds
        },
        "planned_timeline_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "realized_timeline_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "realized_activity_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "planned_type" => %{"type" => "string"},
        "planned_status" => %{"type" => "string"},
        "realized_status" => %{
          "type" => "string",
          "enum" => ["invalid" | capability.supported_realized_statuses]
        },
        "direction" => %{"type" => "string"},
        "ground_station_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "target_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "source_window_id" => %{"type" => "string"},
        "source_window_ids" => stable_id_array_schema,
        "source_window_type" => %{"type" => "string"},
        "collection_ids" => stable_id_array_schema,
        "product_ids" => stable_id_array_schema,
        "payload_ids" => stable_id_array_schema,
        "instrument_ids" => stable_id_array_schema,
        "cadence_import_status" => %{
          "type" => "string",
          "enum" => capability.cadence_import_statuses
        },
        "cadence_import_type" => %{"type" => "string"},
        "capacity_fraction" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "capacity_fraction_min" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "capacity_fraction_max" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "station_calendar_entry_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "station_calendar_provider_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "station_calendar_provider_entry_id" => %{
          "type" => "string",
          "pattern" => stable_id_pattern
        },
        "station_calendar_directions" => string_array_schema,
        "station_calendar_status" => %{"type" => "string"},
        "station_calendar_overlap_count" => %{"type" => "integer", "minimum" => 0},
        "station_calendar_overlap_entry_ids" => stable_id_array_schema,
        "station_calendar_overlap_availabilities" => string_array_schema,
        "station_calendar_entry_ambiguous" => %{"type" => "boolean"},
        "station_calendar_ambiguous_entry_count" => %{"type" => "integer", "minimum" => 0},
        "station_calendar_ambiguous_entry_ids" => stable_id_array_schema,
        "station_calendar_reservation_overlap_count" => %{"type" => "integer", "minimum" => 0},
        "station_calendar_reservation_ids" => stable_id_array_schema,
        "station_calendar_reserved_by" => string_array_schema,
        "station_calendar_reservation_statuses" => string_array_schema,
        "station_calendar_reservation_expires_at_s" => number_array_schema,
        "station_calendar_trust_boundary_status" => %{"type" => "string"},
        "station_contention_status" => %{"type" => "string"},
        "station_reservation_match_status" => %{"type" => "string"},
        "station_reservation_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "station_reservation_expires_at_s" => %{"type" => "number"},
        "station_reserved_by" => %{"type" => "string"},
        "station_reservation_status" => %{"type" => "string"},
        "source_station_calendar_entry" => %{"type" => "object", "additionalProperties" => true},
        "source_station_calendar_overlaps" => %{
          "type" => "array",
          "items" => %{"type" => "object", "additionalProperties" => true}
        },
        "planned_operator_action" => %{"type" => "string"},
        "planned_operator_action_reason" => %{"type" => "string"},
        "planned_direction" => %{"type" => "string"},
        "realized_direction" => %{"type" => "string"},
        "planned_ground_station_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "realized_ground_station_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "planned_target_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "planned_source_window_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "realized_source_window_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "dependency_activity_ids" => stable_id_array_schema,
        "dependency_timeline_ids" => stable_id_array_schema,
        "exclusive_with_activity_ids" => stable_id_array_schema,
        "exclusive_with_timeline_ids" => stable_id_array_schema,
        "identity_match_status" => %{"type" => "string"},
        "identity_mismatch_count" => %{"type" => "integer"},
        "identity_mismatch_fields" => string_array_schema,
        "direction_match_status" => %{"type" => "string"},
        "ground_station_match_status" => %{"type" => "string"},
        "target_match_status" => %{"type" => "string"},
        "source_window_match_status" => %{"type" => "string"},
        "delta_v_match_status" => %{"type" => "string"},
        "operational_feedback_status" => %{"type" => "string"},
        "operational_feedback_excluded" => %{"type" => "boolean"},
        "operational_feedback_exclusion_reason" => %{"type" => "string"},
        "execution_uncertainty_status" => %{"type" => "string"},
        "planned_protection_category" => %{"type" => "string"},
        "planned_protection_decision" => %{
          "type" => "string",
          "enum" => capability.planned_protection_decisions
        },
        "planned_protection_reason" => %{"type" => "string"},
        "source_protection_decision" => protection_decision_schema,
        "status_transition" => lifecycle_transition_schema,
        "battery_capacity_wh" => %{"type" => "number"},
        "battery_energy_used_wh" => %{"type" => "number"},
        "battery_energy_generated_wh" => %{"type" => "number", "minimum" => 0.0},
        "battery_state_of_charge" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "spacecraft_available" => %{"type" => "boolean"},
        "planned_spacecraft_available" => %{"type" => "boolean"},
        "realized_spacecraft_available" => %{"type" => "boolean"},
        "spacecraft_available_match_status" => %{"type" => "string"},
        "payload_available" => %{"type" => "boolean"},
        "planned_payload_available" => %{"type" => "boolean"},
        "realized_payload_available" => %{"type" => "boolean"},
        "payload_available_match_status" => %{"type" => "string"},
        "antenna_available" => %{"type" => "boolean"},
        "planned_antenna_available" => %{"type" => "boolean"},
        "realized_antenna_available" => %{"type" => "boolean"},
        "antenna_available_match_status" => %{"type" => "string"},
        "degraded" => %{"type" => "boolean"},
        "planned_degraded" => %{"type" => "boolean"},
        "realized_degraded" => %{"type" => "boolean"},
        "degraded_match_status" => %{"type" => "string"},
        "mode" => %{"type" => "string"},
        "planned_mode" => %{"type" => "string"},
        "realized_mode" => %{"type" => "string"},
        "mode_match_status" => %{"type" => "string"},
        "thermal_margin_c" => %{"type" => "number"},
        "eclipse_overlap_fraction" => probability_schema,
        "planned_eclipse_overlap_fraction" => probability_schema,
        "realized_eclipse_overlap_fraction" => probability_schema,
        "eclipse_overlap_s" => %{"type" => "number"},
        "planned_eclipse_overlap_s" => %{"type" => "number"},
        "realized_eclipse_overlap_s" => %{"type" => "number"},
        "lighting_condition" => %{"type" => "string"},
        "planned_lighting_condition" => %{"type" => "string"},
        "realized_lighting_condition" => %{"type" => "string"},
        "lighting_condition_match_status" => %{"type" => "string"},
        "lighting_condition_detail" => %{"type" => "string"},
        "lighting_condition_model" => %{"type" => "string"},
        "lighting_detail_model" => %{"type" => "string"},
        "lighting_confidence" => number_or_string_schema,
        "bit_error_rate" => probability_schema,
        "planned_bit_error_rate" => probability_schema,
        "realized_bit_error_rate" => probability_schema,
        "packet_loss_rate" => probability_schema,
        "planned_packet_loss_rate" => probability_schema,
        "realized_packet_loss_rate" => probability_schema,
        "frame_loss_rate" => probability_schema,
        "planned_frame_loss_rate" => probability_schema,
        "realized_frame_loss_rate" => probability_schema,
        "image_quality_score" => probability_schema,
        "planned_image_quality_score" => probability_schema,
        "realized_image_quality_score" => probability_schema,
        "image_quality_score_delta" => %{"type" => "number"},
        "image_quality_status" => %{"type" => "string"},
        "planned_image_quality_status" => %{"type" => "string"},
        "realized_image_quality_status" => %{"type" => "string"},
        "image_quality_status_match_status" => %{"type" => "string"},
        "image_quality_source" => %{"type" => "string"},
        "cloud_cover_fraction" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "planned_cloud_cover_fraction" => %{
          "type" => "number",
          "minimum" => 0.0,
          "maximum" => 1.0
        },
        "realized_cloud_cover_fraction" => %{
          "type" => "number",
          "minimum" => 0.0,
          "maximum" => 1.0
        },
        "cloud_cover_fraction_delta" => %{"type" => "number"},
        "blur_score" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "planned_blur_score" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "realized_blur_score" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "blur_score_delta" => %{"type" => "number"},
        "attitude_target_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "planned_attitude_target_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "realized_attitude_target_id" => %{"type" => "string", "pattern" => stable_id_pattern},
        "attitude_target_match_status" => %{"type" => "string"},
        "attitude_mode" => %{"type" => "string"},
        "planned_attitude_mode" => %{"type" => "string"},
        "realized_attitude_mode" => %{"type" => "string"},
        "attitude_mode_match_status" => %{"type" => "string"},
        "planned_roll_deg" => %{"type" => "number"},
        "realized_roll_deg" => %{"type" => "number"},
        "roll_delta_deg" => %{"type" => "number"},
        "planned_pitch_deg" => %{"type" => "number"},
        "realized_pitch_deg" => %{"type" => "number"},
        "pitch_delta_deg" => %{"type" => "number"},
        "planned_yaw_deg" => %{"type" => "number"},
        "realized_yaw_deg" => %{"type" => "number"},
        "yaw_delta_deg" => %{"type" => "number"},
        "attitude_error_deg" => %{"type" => "number"},
        "attitude_status" => %{"type" => "string"},
        "attitude_model" => %{"type" => "string"},
        "attitude_source" => %{"type" => "string"},
        "attitude_confidence" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "realized_statuses" => %{
          "type" => "array",
          "items" => %{
            "type" => "string",
            "enum" => ["invalid" | capability.supported_realized_statuses]
          }
        },
        "planned_starts_at_s" => %{"type" => "number"},
        "planned_ends_at_s" => %{"type" => "number"},
        "actual_starts_at_s" => %{"type" => "number"},
        "actual_ends_at_s" => %{"type" => "number"},
        "start_delta_s" => %{"type" => "number"},
        "end_delta_s" => %{"type" => "number"},
        "planned_estimated_throughput_mb" => %{"type" => "number"},
        "actual_throughput_mb" => %{"type" => "number"},
        "actual_data_rate_throughput_derivation" => actual_data_rate_throughput_derivation_schema,
        "actual_data_volume_mb" => %{"type" => "number"},
        "throughput_delta_mb" => %{"type" => "number"},
        "throughput_completion_fraction" => %{
          "type" => "number",
          "minimum" => 0.0,
          "maximum" => 1.0
        },
        "contact_success" => %{"type" => "boolean"},
        "contact_success_factor" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "contact_success_factor_source" => %{"type" => "string"},
        "command_success" => %{"type" => "boolean"},
        "command_success_factor" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "command_success_factor_source" => %{"type" => "string"},
        "command_result" => %{"type" => "string"},
        "command_authority_status" => %{"type" => "string"},
        "planned_command_authority_status" => %{"type" => "string"},
        "realized_command_authority_status" => %{"type" => "string"},
        "command_authority_status_match_status" => %{"type" => "string"},
        "required_authority" => %{"type" => "string"},
        "planned_required_authority" => %{"type" => "string"},
        "realized_required_authority" => %{"type" => "string"},
        "required_authority_match_status" => %{"type" => "string"},
        "command_safety_status" => %{"type" => "string"},
        "planned_command_safety_status" => %{"type" => "string"},
        "realized_command_safety_status" => %{"type" => "string"},
        "command_safety_status_match_status" => %{"type" => "string"},
        "command_authorized" => %{"type" => "boolean"},
        "planned_command_authorized" => %{"type" => "boolean"},
        "realized_command_authorized" => %{"type" => "boolean"},
        "command_authorized_match_status" => %{"type" => "string"},
        "command_safety_checked" => %{"type" => "boolean"},
        "planned_command_safety_checked" => %{"type" => "boolean"},
        "realized_command_safety_checked" => %{"type" => "boolean"},
        "command_safety_checked_match_status" => %{"type" => "string"},
        "observation_success" => %{"type" => "boolean"},
        "observation_success_factor" => %{
          "type" => "number",
          "minimum" => 0.0,
          "maximum" => 1.0
        },
        "observation_success_factor_source" => %{"type" => "string"},
        "maneuver_success" => %{"type" => "boolean"},
        "maneuver_success_factor" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "maneuver_success_factor_source" => %{"type" => "string"},
        "maneuver_result" => %{"type" => "string"},
        "planned_delta_v_km_s" => numeric_triplet_schema,
        "planned_delta_v_magnitude_km_s" => %{"type" => "number"},
        "completed_fraction" => %{"type" => "number", "minimum" => 0.0, "maximum" => 1.0},
        "reason" => %{"type" => "string"},
        "has_cadence_import" => %{"type" => "boolean"},
        "realized_type" => %{"type" => "string"},
        "realized_provider" => %{"type" => "string"},
        "realized_adapter" => %{"type" => "string"},
        "realized_adapter_version" => %{"type" => "string"},
        "realized_external_id" => %{"type" => "string"},
        "realized_schema_contract" => %{"type" => "string"},
        "realized_received_at" => %{"type" => "string"},
        "realized_ingested_at" => %{"type" => "string"},
        "realized_trust_boundary" => %{"type" => "string"},
        "realized_provenance" => %{"type" => "object"},
        "realized_source" => %{"type" => "object"},
        "timeline_identity" => timeline_identity_schema,
        "source_activity_context" => activity_context_schema,
        "realized_activity_context" => activity_context_schema,
        "planned_activity" => planned_activity_schema,
        "realized_activity" => realized_activity_schema
      }
    }
  end
end
