defmodule OrbitalDynamics.Schema.TimelineIntegrityRegistryContracts do
  @moduledoc false

  def contracts do
    %{
      "timeline_integrity_report.v1" => %{
        "schema_contract" => "timeline_integrity_report.v1",
        "artifact_family" => "timeline_integrity_report",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "validation_level",
          "source",
          "activity_count",
          "valid_activity_count",
          "invalid_activity_input_count",
          "timeline_integrity_status",
          "timeline_integrity_review_count",
          "timeline_integrity_issue_count",
          "timeline_integrity_issue_types",
          "timeline_integrity_issue_type_counts",
          "required_operator_action_counts",
          "operator_action_reason_counts",
          "dependency_issue_count",
          "exclusivity_issue_count",
          "review_activity_ids",
          "review_timeline_ids",
          "review_activity_ids_by_issue_type",
          "review_timeline_ids_by_issue_type",
          "review_activity_ids_by_required_operator_action",
          "review_timeline_ids_by_required_operator_action",
          "review_activity_ids_by_operator_action_reason",
          "review_timeline_ids_by_operator_action_reason",
          "dependency_review_activity_ids",
          "dependency_review_timeline_ids",
          "exclusivity_review_activity_ids",
          "exclusivity_review_timeline_ids",
          "invalid_activity_input_ids",
          "missing_dependency_activity_ids",
          "missing_dependency_timeline_ids",
          "self_dependency_activity_ids",
          "self_dependency_timeline_ids",
          "duplicate_dependency_activity_ids",
          "duplicate_dependency_timeline_ids",
          "duplicate_exclusivity_activity_ids",
          "duplicate_exclusivity_timeline_ids",
          "dependency_cycle_activity_ids",
          "dependency_cycle_timeline_ids",
          "dependency_order_violation_activity_ids",
          "dependency_order_violation_timeline_ids",
          "exclusivity_violation_activity_ids",
          "exclusivity_violation_timeline_ids",
          "rows",
          "assumptions",
          "model_limits"
        ],
        "optional_fields" => ["id", "provenance"],
        "nested_contracts" => ["operational_timeline_report.v1"]
      },
      "timeline_dependency_impact_summary.v1" => %{
        "schema_contract" => "timeline_dependency_impact_summary.v1",
        "artifact_family" => "timeline_dependency_impact_summary",
        "schema_version" => 1,
        "required_fields" => [
          "schema_contract",
          "model",
          "validation_level",
          "source",
          "source_activity_count",
          "replacement_activity_count",
          "changed_source_activity_count",
          "changed_source_timeline_count",
          "dependency_impact_status",
          "dependent_activity_count",
          "source_dependent_activity_count",
          "replacement_dependent_activity_count",
          "impacted_source_activity_ids",
          "impacted_source_timeline_ids",
          "dependent_activity_ids",
          "dependent_timeline_ids",
          "source_dependent_activity_ids",
          "source_dependent_timeline_ids",
          "replacement_dependent_activity_ids",
          "replacement_dependent_timeline_ids",
          "impacted_dependency_activity_ids",
          "impacted_dependency_timeline_ids",
          "impacted_exclusive_with_activity_ids",
          "impacted_exclusive_with_timeline_ids",
          "dependency_impact_rows",
          "assumptions",
          "model_limits"
        ],
        "optional_fields" => [],
        "nested_contracts" => ["timeline_diff_report.v1"]
      }
    }
  end
end
